SELECT no_plan();
CREATE TEMP TABLE pack_stamp AS SELECT md5(coalesce(string_agg(md5(to_jsonb(p)::text),'' ORDER BY id),'')) digest FROM payroll.statutory_packs p;
INSERT INTO auth.users(id,aud,role,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)VALUES
 ('f1410000-0000-4000-8000-000000000001','authenticated','authenticated','draft-compliance@example.test','hash',now(),'{}','{}',now(),now()),
 ('f1410000-0000-4000-8000-000000000002','authenticated','authenticated','draft-operator@example.test','hash',now(),'{}','{"statutory_rules.manage":true}',now(),now());
INSERT INTO platform_private.platform_operator_grants(user_id,is_active,can_manage_operators,can_manage_statutory_rules)VALUES
 ('f1410000-0000-4000-8000-000000000001',true,false,true),('f1410000-0000-4000-8000-000000000002',true,true,false);
SELECT ok(NOT has_function_privilege('anon','public.statutory_draft_workspace(uuid,timestamptz,uuid,integer,integer)','EXECUTE'),'anonymous cannot read legal dossiers');
SELECT ok(NOT has_function_privilege('service_role','public.statutory_draft_save(uuid,integer,uuid,text,date,date,jsonb,text)','EXECUTE'),'service role cannot invoke product draft writes');
SELECT ok(NOT has_table_privilege('authenticated','payroll.statutory_draft_versions','INSERT'),'API role cannot append versions directly');
SELECT ok(NOT has_function_privilege('authenticated','payroll.statutory_draft_actor()','EXECUTE'),'private authority helper is not a product API');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f1410000-0000-4000-8000-000000000002',true);
SELECT throws_ok($$SELECT public.statutory_draft_workspace()$$,'42501','statutory_draft_forbidden','Operator manager and editable metadata do not confer Compliance read');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,'f1411000-0000-4000-8000-000000000001','NONLEGAL-v1','2026-01-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source"}]','Create fixture')$$,'42501','statutory_draft_forbidden','Operator manager cannot create legal draft without explicit task');
SELECT set_config('request.jwt.claim.sub','f1410000-0000-4000-8000-000000000001',true);
CREATE TEMP TABLE saved AS SELECT public.statutory_draft_save(NULL,0,'f1411000-0000-4000-8000-000000000001','NONLEGAL-v1','2026-01-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source"}]','Create fixture') value;
SELECT is((SELECT value->>'state' FROM saved),'unqualified','creation can only save unqualified draft');
SELECT is(public.statutory_draft_save(NULL,0,'f1411000-0000-4000-8000-000000000001','NONLEGAL-v1','2026-01-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source"}]','Create fixture'),(SELECT value FROM saved),'same attempt returns original receipt without another version');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,'f1411000-0000-4000-8000-000000000001','NONLEGAL-v1','2026-01-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source"}]','Changed intent')$$,'PT409','statutory_draft_attempt_conflict','same attempt cannot be reused for changed intent');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,'f1411000-0000-4000-8000-000000000002','NONLEGAL-v1','2026-01-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source"}]','Create again')$$,'PT409','statutory_draft_exists','separate attempt cannot duplicate named dossier');
SELECT is(public.statutory_draft_save((SELECT(value->>'head')::uuid FROM saved),1,'f1411000-0000-4000-8000-000000000002','NONLEGAL-v1','2026-02-01','2027-01-01','[{"title":"New fixture reference","url":"https://example.test/updated"}]','Reviewed source date')->>'revision','2','edit appends new audited version');
SELECT throws_ok($$SELECT public.statutory_draft_save((SELECT(value->>'head')::uuid FROM saved),1,'f1411000-0000-4000-8000-000000000003','NONLEGAL-v1','2026-03-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source"}]','Stale editor')$$,'PT409','statutory_draft_stale','stale editor cannot overwrite current draft');
SELECT is(public.statutory_draft_workspace((SELECT(value->>'head')::uuid FROM saved))->'current'->>'effective_from','2026-02-01','current detail returns saved source dates');
SELECT is(public.statutory_draft_workspace((SELECT(value->>'head')::uuid FROM saved))->'history'->1->>'effective_from','2026-01-01','earlier effective dates remain intact in history');
SELECT is(public.statutory_draft_workspace((SELECT(value->>'head')::uuid FROM saved),NULL,NULL,NULL,1)->>'next_before_revision','2','history exposes bounded continuation');
SELECT is(public.statutory_draft_workspace((SELECT(value->>'head')::uuid FROM saved),NULL,NULL,2,1)->'history'->0->>'revision','1','history continuation returns original version once');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,gen_random_uuid(),'BAD-sources','2026-01-01',NULL,'[]','Reject empty sources')$$,'22023','statutory_draft_invalid','empty source list cannot become dossier');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,gen_random_uuid(),'BAD-links','2026-01-01',NULL,'[{"title":"Invalid source","url":"javascript:alert(1)"}]','Reject unsafe URL')$$,'22023','statutory_draft_invalid','non-HTTPS link rejected');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,gen_random_uuid(),'BAD-credentials','2026-01-01',NULL,'[{"title":"Invalid source","url":"https://user:secret@example.test/source"}]','Reject credential URL')$$,'22023','statutory_draft_invalid','embedded URL credentials rejected');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,gen_random_uuid(),'BAD-state','2026-01-01',NULL,'[{"title":"Invalid source","url":"https://example.test/source","state":"verified"}]','Reject hidden state')$$,'22023','statutory_draft_invalid','source payload cannot smuggle verified state');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,gen_random_uuid(),'BAD-duplicate','2026-01-01',NULL,'[{"title":"First source","url":"https://example.test/source"},{"title":"Second source","url":"https://example.test/source"}]','Reject duplicate source')$$,'22023','statutory_draft_invalid','duplicate source URLs rejected');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,gen_random_uuid(),'BAD-dates','infinity',NULL,'[{"title":"Fixture source","url":"https://example.test/source"}]','Reject nonfinite date')$$,'22023','statutory_draft_invalid','nonfinite start rejected');
SELECT throws_ok($$SELECT public.statutory_draft_workspace(NULL,NULL,NULL,NULL,21)$$,'22023','statutory_draft_invalid','global legal list remains bounded');
SELECT throws_ok($$SELECT public.statutory_draft_workspace(NULL,now(),NULL)$$,'22023','statutory_draft_invalid','incomplete keyset cursor rejected');
SELECT public.statutory_draft_save(NULL,0,'f1411000-0000-4000-8000-000000000004','NONLEGAL-v2','2026-01-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source2"}]','Second dossier');
CREATE TEMP TABLE first_page AS SELECT public.statutory_draft_workspace(NULL,NULL,NULL,NULL,1) value;
SELECT is(jsonb_array_length((SELECT value->'items' FROM first_page)),1,'list page contains only requested size');
SELECT ok((SELECT value->'next' FROM first_page)<>'null'::jsonb,'list page exposes continuation for remaining dossier');
SELECT isnt(public.statutory_draft_workspace(NULL,(SELECT(value->'next'->>'created')::timestamptz FROM first_page),(SELECT(value->'next'->>'id')::uuid FROM first_page),NULL,1)->'items'->0->>'id',(SELECT value->'items'->0->>'id' FROM first_page),'keyset continuation excludes prior item');
RESET ROLE;
SELECT is((SELECT count(*)::integer FROM payroll.statutory_draft_versions WHERE head_id=(SELECT(value->>'head')::uuid FROM saved)),2,'replay and stale writes do not add versions');
SELECT is((SELECT actor_id::text FROM payroll.statutory_draft_versions WHERE head_id=(SELECT(value->>'head')::uuid FROM saved) AND revision=2),'f1410000-0000-4000-8000-000000000001','version records authenticated Compliance actor');
SELECT throws_ok($$UPDATE payroll.statutory_draft_versions SET reason='Rewrite audit' WHERE head_id=(SELECT(value->>'head')::uuid FROM saved)$$,'55000','payroll_immutable','saved versions cannot be rewritten');
CREATE FUNCTION pg_temp.fail_receipt() RETURNS trigger LANGUAGE plpgsql AS $f$BEGIN RAISE EXCEPTION 'receipt_write_failed' USING ERRCODE='55000';END$f$;
CREATE TRIGGER fail_receipt BEFORE INSERT ON payroll.statutory_draft_receipts FOR EACH ROW EXECUTE FUNCTION pg_temp.fail_receipt();
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT public.statutory_draft_save((SELECT(value->>'head')::uuid FROM saved),2,'f1411000-0000-4000-8000-000000000005','NONLEGAL-v1','2026-03-01',NULL,'[{"title":"Fixture source","url":"https://example.test/source3"}]','Atomic save fixture')$$,'55000','receipt_write_failed','receipt failure rolls back version and current head together');
RESET ROLE;
DROP TRIGGER fail_receipt ON payroll.statutory_draft_receipts;
SELECT is((SELECT revision FROM payroll.statutory_draft_heads WHERE id=(SELECT(value->>'head')::uuid FROM saved)),2,'failed receipt leaves original current revision');
UPDATE platform_private.platform_operator_grants SET can_manage_statutory_rules=false,can_manage_operators=true WHERE user_id='f1410000-0000-4000-8000-000000000001';
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT public.statutory_draft_workspace((SELECT(value->>'head')::uuid FROM saved))$$,'42501','statutory_draft_forbidden','revocation immediately denies read');
SELECT throws_ok($$SELECT public.statutory_draft_save(NULL,0,'f1411000-0000-4000-8000-000000000001','NONLEGAL-v1','2026-01-01',NULL,'[{"title":"Fixture reference","url":"https://example.test/source"}]','Create fixture')$$,'42501','statutory_draft_forbidden','saved receipt does not bypass revoked authority');
RESET ROLE;
SELECT is((SELECT md5(coalesce(string_agg(md5(to_jsonb(p)::text),'' ORDER BY id),'')) FROM payroll.statutory_packs p),(SELECT digest FROM pack_stamp),'draft create/edit/replay never mutates or activates calculation packs');
SELECT * FROM finish();
