SELECT no_plan();
CREATE TEMP TABLE earning_partition_fixture AS SELECT '{"starts_on":"2026-12-31","ends_on":"2027-01-01","pay_basis":"monthly","gross_complete":true,"gross":"0.01","lines":[{"component":"base","classification":"earning","amount":"0.01","details":[{"date":"2026-12-31","_numerator":"1","_denominator":"200","compensation":"old"},{"date":"2027-01-01","_numerator":"1","_denominator":"200","compensation":"new"}]}]}'::jsonb employee;
CREATE TEMP TABLE earning_partition_result AS SELECT payroll.earning_date_partitions(employee) value FROM earning_partition_fixture;
SELECT ok(NOT has_function_privilege('authenticated','payroll.earning_date_partitions(jsonb)','EXECUTE'),'ordinary API cannot supply earning attribution');
SELECT is((SELECT value->'lines'->0->>'operational_date_distribution_known' FROM earning_partition_result),'true','dated monthly salary source has an operational distribution');
SELECT is(jsonb_array_length((SELECT value->'lines'->0->'months' FROM earning_partition_result)),2,'year-crossing source keeps both month fragments');
SELECT is((SELECT(value->'lines'->0->'months'->0->'fraction'->>'n')::numeric FROM earning_partition_result),1::numeric,'first year half-cent numerator preserved');
SELECT is((SELECT(value->'lines'->0->'months'->0->'fraction'->>'d')::numeric FROM earning_partition_result),200::numeric,'first year exact denominator preserved');
SELECT is((SELECT value->'lines'->0->'months'->1->>'year' FROM earning_partition_result),'2027','second year retained');
SELECT is((SELECT value->'lines'->0->'months'->0->>'rounded_amount' FROM earning_partition_result),NULL::text,'half-cent fragments are not independently rounded into duplicate cents');
SELECT is((SELECT value->'lines'->0->>'amount' FROM earning_partition_result),'0.01','saved one-cent total remains authoritative');
SELECT is((SELECT value->'lines'->0->'months'->0->'source_part_indexes' FROM earning_partition_result),'[0]'::jsonb,'fragment references first original source part');
SELECT is((SELECT value->'lines'->0->'months'->1->'source_part_indexes' FROM earning_partition_result),'[1]'::jsonb,'fragment references second original source version');
SELECT is((SELECT value->'lines'->0->>'legal_earning_attribution_known' FROM earning_partition_result),'false','source dates do not automatically prove legal earning attribution');
SELECT is((SELECT value->>'financially_qualified' FROM earning_partition_result),'false','operational partition does not authorize net or lock');
SELECT is(payroll.earning_date_partitions((SELECT jsonb_set(employee,'{pay_basis}','"daily"') FROM earning_partition_fixture))->'lines'->0->>'reason','daily_payable_quantity_is_not_dated_work','manual daily salary spread does not prove work dates');
SELECT is(payroll.earning_date_partitions((SELECT jsonb_set(employee,'{lines,0,component}','"adjustment:NONLEGAL"') FROM earning_partition_fixture))->'lines'->0->>'reason','period_amount_needs_earning_scope','one-time amount is not assigned to first day/payment date');
SELECT is(payroll.earning_date_partitions((SELECT jsonb_set(employee,'{lines,0,details,0}','{"_numerator":"1","_denominator":"200"}') FROM earning_partition_fixture))->'lines'->0->>'operational_date_distribution_known','false','missing date remains unknown rather than guessing');
SELECT throws_ok($$SELECT payroll.earning_date_partitions((SELECT jsonb_set(employee,'{lines,0,details,0,date}','"2026-12-30"') FROM earning_partition_fixture))$$,'22023','payroll_earning_dates_invalid','date outside employment/period earning scope refused');
SELECT throws_ok($$SELECT payroll.earning_date_partitions((SELECT jsonb_set(employee,'{lines,0,details,0,date}','"2026-12-32"') FROM earning_partition_fixture))$$,'22023','payroll_earning_dates_invalid','nonexistent date refused');
SELECT throws_ok($$SELECT payroll.earning_date_partitions((SELECT jsonb_set(employee,'{lines,0,details,0,_denominator}','"0"') FROM earning_partition_fixture))$$,'22023','payroll_earning_dates_invalid','zero denominator refused');
SELECT throws_ok($$SELECT payroll.earning_date_partitions((SELECT jsonb_set(employee,'{lines,0,details,0,_numerator}','"1.1"') FROM earning_partition_fixture))$$,'22023','payroll_earning_dates_invalid','fractional numerator not an exact rational source');
SELECT throws_ok($$SELECT payroll.earning_date_partitions((SELECT jsonb_set(employee,'{lines,0,amount}','"0.02"') FROM earning_partition_fixture))$$,'22023','payroll_earning_source_mismatch','saved amount must equal rounded full source total');
\ir cube4_employee_statutory_source_fixture.sql
CREATE FUNCTION pg_temp.partitions() RETURNS jsonb LANGUAGE sql AS $$ SELECT pg_temp.employee()->'statutory_sources'->'earning_partitions' $$;
SELECT is((SELECT l->>'operational_date_distribution_known' FROM jsonb_array_elements(pg_temp.partitions()->'lines')l WHERE l->>'component'='base'),'false','actual daily total remains undated in public calculate path');
SELECT is((SELECT jsonb_array_length(l->'months') FROM jsonb_array_elements(pg_temp.partitions()->'lines')l WHERE l->>'component'=current_setting('test.component')::jsonb->>'id'),2,'actual recurring salary distribution spans January/February');
SELECT is((SELECT(l->'months'->0->'fraction'->>'n')::numeric*31-(l->'months'->0->'fraction'->>'d')::numeric*2100 FROM jsonb_array_elements(pg_temp.partitions()->'lines')l WHERE l->>'component'=current_setting('test.component')::jsonb->>'id'),0::numeric,'actual January fraction retains7of31 allowance dates');
SELECT is((SELECT(l->'months'->1->'fraction'->>'n')::numeric*31-(l->'months'->1->'fraction'->>'d')::numeric*7200 FROM jsonb_array_elements(pg_temp.partitions()->'lines')l WHERE l->>'component'=current_setting('test.component')::jsonb->>'id'),0::numeric,'actual February fraction retains24of31 allowance dates');
SELECT is((SELECT l->>'reason' FROM jsonb_array_elements(pg_temp.partitions()->'lines')l WHERE l->>'component' LIKE 'adjustment:%'),'period_amount_needs_earning_scope','actual approved bonus retains period scope');
SELECT is(pg_temp.employee()->>'net',NULL::text,'new actual annotation preserves unqualified net');
SELECT * FROM finish();
