BEGIN;
SELECT no_plan();
INSERT INTO auth.users(id,email,encrypted_password,email_confirmed_at,raw_app_meta_data,raw_user_meta_data,aud,role,created_at,updated_at) VALUES
('f5000000-0000-4000-8000-000000000001','cube5-operator@example.test','hash',now(),'{}','{}','authenticated','authenticated',now(),now()),
('f5000000-0000-4000-8000-000000000002','cube5-employee@example.test','hash',now(),'{}','{}','authenticated','authenticated',now(),now()),
('f5000000-0000-4000-8000-000000000003','cube5-unlinked@example.test','hash',now(),'{}','{}','authenticated','authenticated',now(),now());
\ir ../../scripts/cube5-qa-fixture.sql
SELECT set_config('test.cube5_fixture',pg_temp.seed_cube5_fixture('f5000000-0000-4000-8000-000000000001','f5000000-0000-4000-8000-000000000002')::text,true);
SELECT set_config('test.tenant',(current_setting('test.cube5_fixture')::jsonb->>'tenant_id'),true);
SELECT set_config('test.source',(current_setting('test.cube5_fixture')::jsonb->>'external_source_id'),true);
SELECT set_config('test.mobile',(current_setting('test.cube5_fixture')::jsonb->>'mobile_source_id'),true);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000002',true);
SELECT set_config('test.snapshot',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)::text,true);
SELECT is(current_setting('test.snapshot')::jsonb->>'available','true','linked entitled employee can capture');
SELECT is(current_setting('test.snapshot')::jsonb->>'timezone_name','UTC','trusted policy timezone is returned');
SELECT is(current_setting('test.snapshot')::jsonb->>'next_direction','in','first mobile action is check in');
SELECT set_config('test.attempt',jsonb_build_object('id','f5600000-0000-4000-8000-000000000001','direction','in','happened_at',now()-interval '1 minute','scope',current_setting('test.snapshot')::jsonb->>'scope','policy_version',1,'location',NULL)::text,true);
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb)->>'state','accepted','own punch reaches actual canonical Time flow');
SELECT is(public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','out','accepted check in exposes next checkout action');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb)->>'state','duplicate','response-loss retry returns authoritative duplicate');
SELECT is(public.attendance_mobile_attempt(current_setting('test.tenant')::uuid,'f5600000-0000-4000-8000-000000000001',current_setting('test.snapshot')::jsonb->>'scope')->>'state','accepted','reload reconciliation confirms accepted receipt');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb||'{"employee_id":"f5ffffff-0000-4000-8000-000000000001"}'::jsonb)->>'state','rejected','client employee override is not accepted');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb||'{"scope":"another-account"}'::jsonb)->>'reason','scope_changed','scope changed pending attempt cannot cross identity');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb||'{"direction":"out"}'::jsonb)->>'reason','conflict','same event key with changed payload conflicts');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb||jsonb_build_object('id','f5600000-0000-4000-8000-000000000002','direction','out','happened_at',now()))->>'state','accepted','two nearby legitimate distinct punches remain distinct');
SELECT is(public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','in','checkout exposes next start action');
SELECT is(public.attendance_mobile_attempt(current_setting('test.tenant')::uuid,'f5600000-0000-4000-8000-000000000003',current_setting('test.snapshot')::jsonb->>'scope')->>'reason','cancelled','missing reconciliation claims a terminal cancellation');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb||jsonb_build_object('id','f5600000-0000-4000-8000-000000000003','happened_at',now()))->>'reason','cancelled','delayed request cannot arrive after terminal missing reconciliation');
SELECT throws_ok($$SELECT public.attendance_mobile_snapshot('f5ffffff-0000-4000-8000-000000000001')$$,'42501','channel_self_forbidden','cross tenant self access denied');
SELECT throws_ok($$SELECT public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'unauthorized','unknown',now(),'in')$$,'42501','channel_forbidden','employee cannot call operator channel ingest');
RESET ROLE;
SELECT is((SELECT count(*)::integer FROM time.manual_punches WHERE tenant_id=current_setting('test.tenant')::uuid),2,'retries and cancellations create exactly two canonical events');
SELECT is((SELECT count(*)::integer FROM time.interpretations WHERE tenant_id=current_setting('test.tenant')::uuid),2,'each legitimate mobile punch invokes existing Time interpretation');
SELECT is(has_function_privilege('anon','public.attendance_channel_submit(uuid,uuid,text,text,timestamp with time zone,text,text)','EXECUTE'),false,'generic ingest has no unauthenticated access');
SELECT is(has_function_privilege('authenticated','time.channel_process(uuid,uuid,uuid)','EXECUTE'),false,'internal gateway cannot bypass public authorization');
SELECT is(has_table_privilege('authenticated','time.channel_events','SELECT'),false,'source events are available through authorized bounded RPC only');
SELECT set_config('test.geofence','{"geofence":true,"retention_seconds":300,"latitude":30,"longitude":31,"radius_m":100,"tolerance_m":10,"max_accuracy_m":50,"max_age_seconds":30,"failure_action":"reject"}',true);
SELECT is(time.channel_geofence_result(current_setting('test.geofence')::jsonb,jsonb_build_object('latitude',30,'longitude',31,'accuracy',10,'captured_at',now()),now()),'inside','server geofence accepts inside evidence');
SELECT is(time.channel_geofence_result(current_setting('test.geofence')::jsonb,jsonb_build_object('latitude',31,'longitude',31,'accuracy',10,'captured_at',now()),now()),'outside','server geofence identifies outside evidence');
SELECT is(time.channel_geofence_result(current_setting('test.geofence')::jsonb,jsonb_build_object('latitude',30,'longitude',31,'accuracy',51,'captured_at',now()),now()),'accuracy','low accuracy never becomes inside');
SELECT is(time.channel_geofence_result(current_setting('test.geofence')::jsonb,NULL,now()),'unavailable','missing location never bypasses policy');
SELECT is(time.channel_geofence_result(current_setting('test.geofence')::jsonb,jsonb_build_object('latitude',30,'longitude',31,'accuracy',10,'captured_at',now()-interval '31 seconds'),now()),'stale','stale location is explicit');
SELECT is(time.validate_channel_config('mobile','{"geofence":true,"retention_seconds":300}'),false,'incomplete geofence has no invented defaults');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);
SELECT set_config('test.unmapped',public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'unknown-event','unknown-key',now()-interval '2 minutes','in')::text,true);
SELECT is(current_setting('test.unmapped')::jsonb->>'state','unmapped','unknown identity is retained as actionable mapping exception');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'unknown-key',(current_setting('test.cube5_fixture')::jsonb->>'employee_id')::uuid,(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now()-interval '1 day',NULL,true)$$,'mapping correction is tenant scoped');
SELECT is(public.attendance_channel_reprocess(current_setting('test.tenant')::uuid,(current_setting('test.unmapped')::jsonb->>'event_id')::uuid)->>'state','accepted','retained unmapped event reprocesses into Time');
SELECT is(public.attendance_channel_reprocess(current_setting('test.tenant')::uuid,(current_setting('test.unmapped')::jsonb->>'event_id')::uuid)->>'state','duplicate','reprocess is idempotent');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'unknown-event','unknown-key',now()-interval '2 minutes','in')->>'state','duplicate','stable external replay is observable');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'unknown-event','changed-key',now(),'out')->>'reason','conflict','external replay changed payload conflicts');
SELECT throws_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'cross-scope','f5ffffff-0000-4000-8000-000000000001',(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now(),NULL,true)$$,'22023','channel_mapping_scope_invalid','foreign employee mapping rejected authoritatively');
SELECT lives_ok($$SELECT public.attendance_channel_save_source(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'مصدر تجريبي','external',(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,false,'{}','Synthetic disable')$$,'source disabled by versioned append');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'new-disabled','unknown-key',now(),'in')->>'reason','disabled','disabled source denies new capture');
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000003',true);
SELECT throws_ok($$SELECT public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)$$,'42501','channel_self_forbidden','missing membership or permission denied');
RESET ROLE;
SELECT is((SELECT count(*)::integer FROM time.channel_events WHERE tenant_id=current_setting('test.tenant')::uuid),3,'disable preserves prior events without accepting new source event');
SELECT throws_ok($$DELETE FROM time.channel_events WHERE tenant_id=current_setting('test.tenant')::uuid$$,'55000','attendance_evidence_append_only','source receipt evidence cannot be deleted');
-- Finite backend guard deltas: real public endpoints, frozen provenance and current Time semantics.
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);
SELECT lives_ok($$SELECT public.attendance_channel_save_source(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'مصدر تجريبي','external',(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,true,'{}','Synthetic enable')$$,'source can resume without replacing history');
SELECT is(jsonb_array_length(public.attendance_channel_sources(current_setting('test.tenant')::uuid,1,0)->'items'),1,'source listing is bounded');
SELECT is(public.attendance_channel_sources(current_setting('test.tenant')::uuid,1,0)->>'has_more','true','source list exposes next page');
SELECT throws_ok($$SELECT public.attendance_channel_sources(current_setting('test.tenant')::uuid,51,0)$$,'22023','channel_page_invalid','source page size cannot be unbounded');
SELECT is(public.attendance_channel_events(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,1,0)->'items'->0->>'state','accepted','replay observations never overwrite accepted processing state');
SELECT is(jsonb_array_length(public.attendance_channel_event_detail(current_setting('test.tenant')::uuid,(current_setting('test.unmapped')::jsonb->>'event_id')::uuid)->'replays'),3,'reprocess and identical/conflicting replay remain visible diagnostics');
SELECT set_config('test.poison',public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'replay-before-map','later-mapped',now()-interval '3 minutes','in')::text,true);
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'replay-before-map','later-mapped',now()-interval '3 minutes','in')->>'state','duplicate','unmapped identical replay is an observation');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'replay-before-map','malicious-change',now(),'out')->>'reason','conflict','unmapped conflicting replay is rejected');
SELECT is(public.attendance_channel_events(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,20,0)->'items' @> jsonb_build_array(jsonb_build_object('id',current_setting('test.poison')::jsonb->>'event_id','state','unmapped')),true,'unmapped responsibility survives all replay observations');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'later-mapped',(current_setting('test.cube5_fixture')::jsonb->>'employee_id')::uuid,(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now()-interval '1 day',NULL,true)$$,'original identity mapped after conflict');
SELECT is(public.attendance_channel_reprocess(current_setting('test.tenant')::uuid,(current_setting('test.poison')::jsonb->>'event_id')::uuid)->>'state','accepted','conflicting replay cannot poison original retained evidence');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'historical',(current_setting('test.cube5_fixture')::jsonb->>'employee_id')::uuid,(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now()-interval '10 days',now()-interval '1 day',true)$$,'historical effective mapping interval retained');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'historical',(current_setting('test.cube5_fixture')::jsonb->>'employee_id')::uuid,(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now()-interval '1 day',NULL,true)$$,'new interval does not erase earlier mapping');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'historic-event','historical',now()-interval '2 days','in')->>'state','accepted','late replay resolves event-time historical mapping');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'historical',(current_setting('test.cube5_fixture')::jsonb->>'employee_id')::uuid,(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now()-interval '5 days',NULL,true)$$,'overlap is visible instead of being guessed');
SELECT set_config('test.ambiguous',public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'ambiguous-map','historical',now()-interval '3 days','in')::text,true);
SELECT is(current_setting('test.ambiguous')::jsonb->>'reason','mapping_ambiguous','overlapping effective mappings are explicit exception');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'historical',(current_setting('test.cube5_fixture')::jsonb->>'employee_id')::uuid,(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now()-interval '5 days',NULL,false)$$,'deactivation is append-only for the exact interval');
SELECT is(public.attendance_channel_reprocess(current_setting('test.tenant')::uuid,(current_setting('test.ambiguous')::jsonb->>'event_id')::uuid)->>'state','accepted','mapping overlap correction reprocesses original identity once');
RESET ROLE;
INSERT INTO platform_core.tenant_sites(tenant_id,id,legal_entity_id,display_name,is_default,is_active) VALUES(current_setting('test.tenant')::uuid,'f5140000-0000-4000-8000-000000000002','f5130000-0000-4000-8000-000000000001','Synthetic overnight UTC site',false,true);
INSERT INTO time.work_policy_templates(tenant_id,id,code,is_active,head_version) VALUES(current_setting('test.tenant')::uuid,'f5150000-0000-4000-8000-000000000002','NIGHT-QA',true,1);
INSERT INTO time.work_policy_versions(tenant_id,template_id,version,name,schedule_kind,timezone_name,work_days,shift_start,shift_end,ends_next_day,break_minutes,created_by)
VALUES(current_setting('test.tenant')::uuid,'f5150000-0000-4000-8000-000000000002',1,'Synthetic UTC overnight','fixed','UTC',ARRAY[1,2,3,4,5,6,7]::smallint[],'22:00','06:00',true,0,'f5000000-0000-4000-8000-000000000001');
SELECT set_config('test.night_employee',public.create_people_employee(current_setting('test.tenant')::uuid,'CUBE5-SYN-2','Synthetic overnight employee','f5130000-0000-4000-8000-000000000001','f5140000-0000-4000-8000-000000000002',(now() AT TIME ZONE 'UTC')::date-30,'monthly',1000,true)::text,true);
UPDATE people.work_assignments SET work_policy_template_id='f5150000-0000-4000-8000-000000000002',work_policy_version=1 WHERE tenant_id=current_setting('test.tenant')::uuid AND employment_id=(current_setting('test.night_employee')::jsonb->>'employment_id')::uuid;
SELECT set_config('test.night_in',(((now() AT TIME ZONE 'UTC')::date-2+'22:10'::time) AT TIME ZONE 'UTC')::text,true);
SELECT set_config('test.night_out',(((now() AT TIME ZONE 'UTC')::date-1+'05:50'::time) AT TIME ZONE 'UTC')::text,true);
SET LOCAL ROLE authenticated;
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'night',(current_setting('test.night_employee')::jsonb->>'employee_id')::uuid,'f5140000-0000-4000-8000-000000000002',now()-interval '10 days',NULL,true)$$,'explicit overnight identity mapping uses its own Site');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'night-in','night',current_setting('test.night_in')::timestamptz,'in')->>'state','accepted','gateway records scheduled overnight start');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'night-out','night',current_setting('test.night_out')::timestamptz,'out')->>'state','accepted','gateway records checkout after midnight');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'site-history',(current_setting('test.cube5_fixture')::jsonb->>'employee_id')::uuid,(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,now()-interval '10 days',((now() AT TIME ZONE 'UTC')::date-1)::timestamp AT TIME ZONE 'UTC',true)$$,'older mapping retains its earlier employee and Site');
SELECT lives_ok($$SELECT public.attendance_channel_map(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'site-history',(current_setting('test.night_employee')::jsonb->>'employee_id')::uuid,'f5140000-0000-4000-8000-000000000002',((now() AT TIME ZONE 'UTC')::date-1)::timestamp AT TIME ZONE 'UTC',NULL,true)$$,'new dated mapping carries a different employee and Site');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'site-history-old','site-history',current_setting('test.night_in')::timestamptz,'in')->>'state','accepted','late historical replay uses old employee Site');
SELECT is(public.attendance_channel_submit(current_setting('test.tenant')::uuid,current_setting('test.source')::uuid,'site-history-new','site-history',current_setting('test.night_out')::timestamptz,'out')->>'state','accepted','new interval uses new employee Site without retroactive remap');
RESET ROLE;
SELECT is((SELECT count(DISTINCT r.work_instance_id)::integer FROM time.channel_events e JOIN time.channel_event_results r ON r.tenant_id=e.tenant_id AND r.event_id=e.id WHERE e.tenant_id=current_setting('test.tenant')::uuid AND e.external_key='night' AND r.state='accepted'),1,'both cross-midnight punches belong to one existing Work Instance');
SELECT is((SELECT operational_date FROM time.work_instances WHERE tenant_id=current_setting('test.tenant')::uuid AND employee_id=(current_setting('test.night_employee')::jsonb->>'employee_id')::uuid LIMIT 1),(now() AT TIME ZONE 'UTC')::date-2,'overnight operational date remains the starting day in trusted UTC policy');
SELECT is((SELECT r.site_id FROM time.channel_events e JOIN time.channel_event_results r ON r.tenant_id=e.tenant_id AND r.event_id=e.id WHERE e.tenant_id=current_setting('test.tenant')::uuid AND e.event_key='site-history-old' AND r.state='accepted'),(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,'old mapping canonical provenance freezes old Site');
SELECT is((SELECT r.site_id FROM time.channel_events e JOIN time.channel_event_results r ON r.tenant_id=e.tenant_id AND r.event_id=e.id WHERE e.tenant_id=current_setting('test.tenant')::uuid AND e.event_key='site-history-new' AND r.state='accepted'),'f5140000-0000-4000-8000-000000000002'::uuid,'new mapping canonical provenance freezes new Site');
SET LOCAL ROLE authenticated;
SELECT throws_ok(format('SELECT public.attendance_channel_save_source(%L::uuid,%L::uuid,%L,%L,%L::uuid,true,%L::jsonb,%L)',current_setting('test.tenant'),current_setting('test.mobile'),'الحضور من الهاتف','mobile',current_setting('test.cube5_fixture')::jsonb->>'site_id',(current_setting('test.geofence')::jsonb-key)::text,'Missing required configuration'),'22023','channel_config_invalid','public source configuration rejects missing '||key)
FROM unnest(ARRAY['geofence','retention_seconds','latitude','longitude','radius_m','tolerance_m','max_accuracy_m','max_age_seconds','failure_action'])key;
SELECT lives_ok($$SELECT public.attendance_channel_save_source(current_setting('test.tenant')::uuid,current_setting('test.mobile')::uuid,'الحضور من الهاتف','mobile',(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,true,current_setting('test.geofence')::jsonb,'Synthetic geofence reject')$$,'explicit complete geofence policy activates version two');
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000002',true);
SELECT set_config('test.gf_attempt',jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','happened_at',now(),'scope',current_setting('test.snapshot')::jsonb->>'scope','policy_version',2,'location',jsonb_build_object('latitude',30,'longitude',31,'accuracy',10,'captured_at',now()))::text,true);
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb)->>'state','accepted','public own endpoint accepts valid inside evidence');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb||jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','location',jsonb_build_object('latitude',31,'longitude',31,'accuracy',10,'captured_at',now())))->>'reason','outside','public own endpoint rejects outside');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb||jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','location',jsonb_build_object('latitude',30,'longitude',31,'accuracy',51,'captured_at',now())))->>'reason','accuracy','public own endpoint rejects insufficient accuracy');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb||jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','location',NULL))->>'reason','unavailable','public own endpoint rejects unavailable location');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb||jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','location',jsonb_build_object('latitude',30,'longitude',31,'accuracy',10,'captured_at',now()-interval '31 seconds')))->>'reason','stale','public own endpoint rejects stale location');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb||jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','location',jsonb_build_object('latitude',30,'longitude',31,'accuracy',NULL,'captured_at',now())))->>'reason','unavailable','JSON null accuracy fails closed through public endpoint');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb||jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','location',jsonb_build_object('latitude',30,'longitude',31,'captured_at',now())))->>'reason','unavailable','missing accuracy fails closed through public endpoint');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.gf_attempt')::jsonb||jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','location',jsonb_build_object('latitude',30,'longitude',31,'accuracy',10,'captured_at',now(),'arbitrary_blob','not-permitted')))->>'reason','unavailable','unknown location payload fields are rejected at public boundary');
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);
SELECT lives_ok($$SELECT public.attendance_channel_save_source(current_setting('test.tenant')::uuid,current_setting('test.mobile')::uuid,'الحضور من الهاتف','mobile',(current_setting('test.cube5_fixture')::jsonb->>'site_id')::uuid,true,current_setting('test.geofence')::jsonb||'{"failure_action":"review"}','Synthetic geofence review')$$,'review policy is explicit version three');
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000002',true);
SELECT set_config('test.review_attempt',jsonb_build_object('id',gen_random_uuid(),'direction',public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','happened_at',now(),'scope',current_setting('test.snapshot')::jsonb->>'scope','policy_version',3,'location',jsonb_build_object('latitude',31,'longitude',31,'accuracy',10,'captured_at',now()))::text,true);
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.review_attempt')::jsonb)->>'state','accepted','explicit review policy retains canonical event with review flag');
RESET ROLE;
SELECT set_config('test.review_event',(SELECT id::text FROM time.channel_events WHERE tenant_id=current_setting('test.tenant')::uuid AND event_key=current_setting('test.review_attempt')::jsonb->>'id'),true);
SELECT set_config('test.review_instance',(SELECT work_instance_id::text FROM time.channel_event_results WHERE tenant_id=current_setting('test.tenant')::uuid AND event_id=current_setting('test.review_event')::uuid AND canonical_punch_id IS NOT NULL ORDER BY id DESC LIMIT 1),true);
SELECT is((SELECT exception_code FROM time.interpretations WHERE tenant_id=current_setting('test.tenant')::uuid AND work_instance_id=current_setting('test.review_instance')::uuid ORDER BY version DESC LIMIT 1),'channel_location_review','geofence exception reaches existing Time review state');
SELECT is(time.has_unresolved_channel_review(current_setting('test.tenant')::uuid,current_setting('test.review_instance')::uuid),true,'review exception blocks approved facts until governed closure');
SELECT is((SELECT count(*)::integer FROM time.channel_location_evidence l JOIN time.channel_events e ON e.tenant_id=l.tenant_id AND e.id=l.event_id WHERE e.tenant_id=current_setting('test.tenant')::uuid AND e.validation='unavailable'),0,'malformed or extra-field location payload is never persisted as precise evidence');
SELECT cmp_ok(time.purge_expired_channel_location(now()+interval '301 seconds'),'>',0,'trusted task purge actually removes expired precise evidence');
SELECT is((SELECT count(*)::integer FROM time.channel_location_evidence WHERE tenant_id=current_setting('test.tenant')::uuid),0,'location retention purge leaves no expired coordinates');
SELECT is((SELECT validation FROM time.channel_events WHERE tenant_id=current_setting('test.tenant')::uuid AND id=current_setting('test.review_event')::uuid),'outside','retention purge preserves frozen validation');
SELECT is((SELECT source_version FROM time.channel_events WHERE tenant_id=current_setting('test.tenant')::uuid AND id=current_setting('test.review_event')::uuid),3,'retention purge preserves capture policy version');
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);
SELECT is(public.attendance_channel_review(current_setting('test.tenant')::uuid,current_setting('test.review_event')::uuid,'accept','Synthetic reviewed evidence')->>'state','reviewed','authorized location review closes through existing Time interpretation');
SELECT is(public.attendance_channel_review(current_setting('test.tenant')::uuid,current_setting('test.review_event')::uuid,'accept','Synthetic reviewed evidence')->>'state','unchanged','location review is idempotent');
RESET ROLE;
SELECT is(time.has_unresolved_channel_review(current_setting('test.tenant')::uuid,current_setting('test.review_instance')::uuid),false,'explicit review decision clears review gate without rewriting evidence');
SELECT set_config('test.last_punch',(SELECT id::text FROM time.manual_punches WHERE tenant_id=current_setting('test.tenant')::uuid AND work_instance_id=current_setting('test.review_instance')::uuid ORDER BY happened_at DESC,id DESC LIMIT 1),true);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);
SELECT lives_ok($$SELECT public.correct_manual_attendance_punch(current_setting('test.tenant')::uuid,current_setting('test.review_instance')::uuid,current_setting('test.last_punch')::uuid,'replace','in',now()+interval '1 second','Synthetic corrected direction')$$,'existing correction replaces source direction and instant');
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000002',true);
SELECT is(public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','out','mobile expected state applies latest replacement instead of raw source direction');
RESET ROLE;
SELECT set_config('test.other_punch',(SELECT id::text FROM time.manual_punches WHERE tenant_id=current_setting('test.tenant')::uuid AND work_instance_id=current_setting('test.review_instance')::uuid AND id<>current_setting('test.last_punch')::uuid ORDER BY happened_at DESC,id DESC LIMIT 1),true);
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);
SELECT lives_ok($$SELECT public.correct_manual_attendance_punch(current_setting('test.tenant')::uuid,current_setting('test.review_instance')::uuid,current_setting('test.other_punch')::uuid,'replace','out',now()+interval '2 seconds','Synthetic corrected checkout')$$,'existing correction can explicitly restore checkout state');
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000002',true);
SELECT is(public.attendance_mobile_snapshot(current_setting('test.tenant')::uuid)->>'next_direction','in','corrected checkout exposes start action');
RESET ROLE;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000002',true);
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,'{"id":"malformed"}')->>'state','rejected','malformed timestamp and UUID produce authoritative failure');
SELECT lives_ok($$DO $d$ BEGIN FOR i IN 1..20 LOOP PERFORM public.attendance_mobile_punch(current_setting('test.tenant')::uuid,'{}'); END LOOP; END $d$;$$,'rejected malformed attempts count toward bounded rate limit');
SELECT is(public.attendance_mobile_punch(current_setting('test.tenant')::uuid,current_setting('test.attempt')::jsonb)->>'reason','rate','server limits repeated capture including failures');
RESET ROLE;
SELECT is((SELECT count(*)::integer FROM time.mobile_capture_requests WHERE tenant_id=current_setting('test.tenant')::uuid AND actor_user_id='f5000000-0000-4000-8000-000000000002'),20,'rate-limited attempts cannot grow persisted request count past bound per minute');
UPDATE platform_core.tenant_memberships SET access_state='inactive' WHERE tenant_id=current_setting('test.tenant')::uuid AND user_id='f5000000-0000-4000-8000-000000000002';
SET LOCAL ROLE authenticated;
SELECT throws_ok($$SELECT public.attendance_mobile_attempt(current_setting('test.tenant')::uuid,'f5600000-0000-4000-8000-000000000001',current_setting('test.snapshot')::jsonb->>'scope')$$,'42501','channel_self_forbidden','membership revocation blocks pending attempt reconciliation');
RESET ROLE;
UPDATE platform_core.tenant_capability_entitlements SET valid_until=now()-interval '1 second' WHERE tenant_id=current_setting('test.tenant')::uuid AND capability_key='hr.attendance';
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','f5000000-0000-4000-8000-000000000001',true);
SELECT throws_ok($$SELECT public.attendance_channel_review(current_setting('test.tenant')::uuid,current_setting('test.review_event')::uuid,'accept','Synthetic disabled entitlement')$$,'42501','channel_review_forbidden','channel review follows existing Time mutation entitlement gate');
SELECT lives_ok($$SELECT public.attendance_channel_sources(current_setting('test.tenant')::uuid,20,0)$$,'entitlement loss preserves authorized historical source read');
RESET ROLE;
SELECT * FROM finish();
ROLLBACK;
