-- Bounded runner supplies the existing isolated input fixture; all effects roll back.
SELECT set_config('test.opening','{"year":"2030","taxable_earnings":"10000","tax_withheld":"100","tax_due":"125.50","social_base":"10000","employee_social":"100","employer_social":"200","reference":"Reviewed opening source","reason":"Explicit prior cumulative facts"}',true);
SELECT set_config('test.coverage','{"coverage_start":"2030-01-01","coverage_end":"2030-01-24","tax_duration_days":"20"}',true);
SELECT lives_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb)$$,'legacy coverage remains unknown');
SELECT lives_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb)$$,'complete reviewed coverage group accepted');
SELECT lives_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"tax_duration_days":"0"}')$$,'explicit zero duration is a recorded fact, not an inferred unknown');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||'{"coverage_start":"2030-01-01"}')$$,'22023','payroll_opening_coverage_invalid','partial group rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"tax_duration_days":null}')$$,'22023','payroll_opening_coverage_invalid','null duration rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"tax_duration_days":true}')$$,'22023','payroll_opening_coverage_invalid','boolean duration rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"tax_duration_days":"NaN"}')$$,'22023','payroll_opening_coverage_invalid','nonfinite duration rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"tax_duration_days":"-1"}')$$,'22023','payroll_opening_coverage_invalid','negative duration rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"tax_duration_days":"367"}')$$,'22023','payroll_opening_coverage_invalid','one-year representation bound enforced');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"tax_duration_days":"1.001"}')$$,'22023','payroll_opening_coverage_invalid','excess duration precision rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"coverage_start":"2029-12-31"}')$$,'22023','payroll_opening_coverage_invalid','coverage must belong to opening tax year');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"coverage_end":"2030-02-30"}')$$,'22023','payroll_opening_coverage_invalid','nonexistent date rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"coverage_end":"infinity"}')$$,'22023','payroll_opening_coverage_invalid','special date rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"coverage_end":""}')$$,'22023','payroll_opening_coverage_invalid','empty date rejected');
SELECT throws_ok($$SELECT payroll.validate_input('opening_ytd',current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||'{"coverage_start":"2030-01-25"}')$$,'22023','payroll_opening_coverage_invalid','reversed coverage rejected');
SELECT ok(NOT has_function_privilege('authenticated','payroll.validate_opening_coverage(jsonb,date)','EXECUTE'),'coverage helper remains private');
CREATE FUNCTION pg_temp.save_opening(extra jsonb DEFAULT '{}',attempt uuid DEFAULT NULL) RETURNS jsonb LANGUAGE sql AS $$
 SELECT public.payroll_save_input('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','opening_ytd','c4425000-0000-4000-8000-000000000001',NULL,NULL,0,'2030-01-25',NULL,current_setting('test.opening')::jsonb||current_setting('test.coverage')::jsonb||extra,'save',COALESCE(attempt,gen_random_uuid()))
$$;
GRANT EXECUTE ON FUNCTION pg_temp.save_opening(jsonb,uuid) TO authenticated;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','c4420000-0000-4000-8000-000000000001',true);
SELECT throws_ok($$SELECT pg_temp.save_opening('{"coverage_end":"2030-01-25"}')$$,'22023','payroll_opening_coverage_invalid','coverage cannot overlap effective start of new opening context');
SELECT set_config('test.opening.saved',pg_temp.save_opening(attempt=>'c4429000-0000-4000-8000-000000000091')::text,true);
SELECT is(pg_temp.save_opening(attempt=>'c4429000-0000-4000-8000-000000000091'),current_setting('test.opening.saved')::jsonb,'actual authenticated save supports exact-intent replay');
SELECT set_config('test.opening.period',(public.payroll_save_calendar('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','2030-01-25',24,25,'ending','Africa/Cairo',0,gen_random_uuid(),public.payroll_calendar_preview('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','2030-01-25',24,25,'ending','Africa/Cairo'),'Reviewed synthetic calendar')->>'period_id'),true);
RESET ROLE;
SELECT is((SELECT data->>'tax_duration_days' FROM payroll.input_versions WHERE tenant_id='c4421000-0000-4000-8000-000000000001' AND head_id=(current_setting('test.opening.saved')::jsonb->>'id')::uuid),'20','duration is saved verbatim, not derived from24 calendar days');
SELECT ok(jsonb_path_exists(payroll.run_manifest('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001',current_setting('test.opening.period')::uuid),'$.inputs[*].version.data ? (@.coverage_start == "2030-01-01" && @.coverage_end == "2030-01-24" && @.tax_duration_days == "20")'),'review manifest snapshots exact coverage and source duration');
SELECT is((SELECT count(*)::int FROM payroll.input_versions WHERE tenant_id='c4421000-0000-4000-8000-000000000001' AND head_id=(current_setting('test.opening.saved')::jsonb->>'id')::uuid),1,'replay does not duplicate version');
SELECT throws_ok($$SELECT payroll.compile_source_changes(v.tenant_id,v.employer_id,jsonb_build_array(jsonb_build_object('type','input_revision','source_id',v.head_id,'expected_hash',payroll.source_hash(to_jsonb(v)),'fields',jsonb_build_object('effective_from',v.effective_from,'effective_until',v.effective_until,'data',v.data||'{"coverage_end":"2030-01-25"}'::jsonb,'cancelled',false))),'c4420000-0000-4000-8000-000000000001') FROM payroll.input_versions v WHERE v.tenant_id='c4421000-0000-4000-8000-000000000001' AND v.head_id=(current_setting('test.opening.saved')::jsonb->>'id')::uuid$$,'22023','payroll_opening_coverage_invalid','governed correction cannot bypass coverage boundary');
SELECT * FROM finish();
