-- Actual authenticated save -> manifest -> public calculate -> immutable candidate.
INSERT INTO platform_core.tenant_sites(tenant_id,id,legal_entity_id,display_name,is_default) VALUES('c4421000-0000-4000-8000-000000000001','c4423500-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','Statutory source site',false);
INSERT INTO people.work_assignments(tenant_id,id,employment_id,site_id,valid_from) VALUES('c4421000-0000-4000-8000-000000000001','c4426500-0000-4000-8000-000000000001','c4425000-0000-4000-8000-000000000001','c4423500-0000-4000-8000-000000000001','2030-01-01');
CREATE FUNCTION pg_temp.save(k text,d jsonb,h uuid DEFAULT NULL,r integer DEFAULT 0,op text DEFAULT 'save',ef date DEFAULT '2030-01-25') RETURNS jsonb LANGUAGE sql AS $$
 SELECT public.payroll_save_input('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001',k,CASE WHEN k IN('recurring','manual_units','adjustment') THEN 'c4425000-0000-4000-8000-000000000001'::uuid END,CASE WHEN k IN('manual_units','adjustment') THEN current_setting('test.period')::uuid END,h,r,ef,CASE WHEN k IN('manual_units','adjustment') THEN '2030-02-25'::date END,d,op,gen_random_uuid()) $$;
GRANT EXECUTE ON FUNCTION pg_temp.save(text,jsonb,uuid,integer,text,date) TO authenticated;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','c4420000-0000-4000-8000-000000000001',true);
SELECT set_config('test.period',(public.payroll_save_calendar('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','2030-01-25',24,25,'ending','Africa/Cairo',0,gen_random_uuid(),public.payroll_calendar_preview('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','2030-01-25',24,25,'ending','Africa/Cairo'),'Source annotation fixture')->>'period_id'),true);
SELECT pg_temp.save('policy','{"mode":"calendar_days","reason":"Reviewed source test"}');
SELECT set_config('test.component.data','{"key":"source_allowance","name":"Allowance","classification":"earning","calculation":"fixed","base":"","value":"300","taxable":"false","social":"true","visible":"false","active":"true","order":"10","behavior":"recurring","reason":"Reviewed source facts"}',true);
SELECT set_config('test.component',pg_temp.save('component',current_setting('test.component.data')::jsonb)::text,true);
SELECT pg_temp.save('recurring',jsonb_build_object('component_id',current_setting('test.component')::jsonb->>'id','value','300','reason','Reviewed assignment'));
SELECT set_config('test.units',pg_temp.save('manual_units','{"units":"5","source":"manual","basis":"approved_payable_total","reference":"Reviewed units","reason":"Reviewed total"}')::text,true);
SELECT pg_temp.save('manual_units','{"units":"5","source":"manual","basis":"approved_payable_total","reference":"Reviewed units","reason":"Reviewed total"}',(current_setting('test.units')::jsonb->>'id')::uuid,1,'approve');
SELECT set_config('test.bonus',pg_temp.save('component',current_setting('test.component.data')::jsonb||'{"key":"source_bonus","name":"Bonus","behavior":"period_input","taxable":"true","social":"false","visible":"true"}')::text,true);
SELECT set_config('test.adjustment.data',jsonb_build_object('component_id',current_setting('test.bonus')::jsonb->>'id','amount','40','reference','Reviewed bonus','reason','Reviewed single bonus')::text,true);
SELECT set_config('test.adjustment',pg_temp.save('adjustment',current_setting('test.adjustment.data')::jsonb)::text,true);
SELECT pg_temp.save('adjustment',current_setting('test.adjustment.data')::jsonb,(current_setting('test.adjustment')::jsonb->>'id')::uuid,1,'approve');
SELECT set_config('test.run',public.payroll_run_command('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001',current_setting('test.period')::uuid,NULL,0,'calculate','',gen_random_uuid())::text,true);
RESET ROLE;
CREATE FUNCTION pg_temp.employee() RETURNS jsonb LANGUAGE sql AS $$ SELECT output->'employees'->0 FROM payroll.candidates WHERE tenant_id='c4421000-0000-4000-8000-000000000001' AND id=(current_setting('test.run')::jsonb->>'candidate_id')::uuid $$;
CREATE FUNCTION pg_temp.line(k text) RETURNS jsonb LANGUAGE sql AS $$ SELECT l FROM jsonb_array_elements(pg_temp.employee()->'lines')l WHERE l->>'component'=k $$;
SELECT is(pg_temp.line(current_setting('test.component')::jsonb->>'id')->'details'->0->'declared_taxable','false'::jsonb,'actual recurring declared_taxable from source version');
SELECT is(pg_temp.line(current_setting('test.component')::jsonb->>'id')->'details'->0->'declared_social','true'::jsonb,'actual recurring declared_social from source version');
SELECT is(pg_temp.line(current_setting('test.component')::jsonb->>'id')->'details'->0->'declared_visible','false'::jsonb,'actual recurring declared_visible from source version');
SELECT is(pg_temp.line(current_setting('test.component')::jsonb->>'id')->'details'->0->>'component_version',(SELECT id::text FROM payroll.input_versions WHERE head_id=(current_setting('test.component')::jsonb->>'id')::uuid),'actual recurring exact source version');
SELECT is(pg_temp.line('adjustment:'||(current_setting('test.adjustment')::jsonb->>'id'))->'details'->0->'declared_taxable','true'::jsonb,'actual approved bonus declared_taxable from component source');
SELECT is(pg_temp.line('adjustment:'||(current_setting('test.adjustment')::jsonb->>'id'))->'details'->0->'declared_social','false'::jsonb,'actual approved bonus declared_social from component source');
SELECT is(pg_temp.line('adjustment:'||(current_setting('test.adjustment')::jsonb->>'id'))->'details'->0->'declared_visible','true'::jsonb,'actual approved bonus declared_visible from component source');
SELECT is(pg_temp.line('adjustment:'||(current_setting('test.adjustment')::jsonb->>'id'))->'details'->0->>'component_head',current_setting('test.bonus')::jsonb->>'id','bonus binds component head separately from adjustment');
SELECT is((pg_temp.employee()->>'gross')::numeric,840::numeric,'source annotation preserves actual gross500+300+40');
SELECT is(pg_temp.employee()->>'net',NULL::text,'source facts do not invent legal net');
SELECT ok(EXISTS(SELECT 1 FROM jsonb_array_elements(payroll.review_employee_detail(pg_temp.employee())->'lines')l WHERE l->>'component' LIKE 'adjustment:%' AND l->'segments'->0->'declared_taxable'='true'::jsonb AND l->'segments'->0->>'component_version' IS NOT NULL),'real detail projection preserves bonus declaration and version');
SELECT ok((SELECT engine_version LIKE '%statutory-sources-v1' FROM payroll.candidates WHERE id=(current_setting('test.run')::jsonb->>'candidate_id')::uuid),'actual saved candidate records new engine identity');
SELECT set_config('test.old.candidate',pg_temp.employee()::text,true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.save('component',current_setting('test.component.data')::jsonb||'{"taxable":"true"}',(current_setting('test.component')::jsonb->>'id')::uuid,1,'save','2030-03-01');
RESET ROLE;
SELECT is(pg_temp.employee(),current_setting('test.old.candidate')::jsonb,'future source change never rewrites immutable calculated declarations');
SELECT * FROM finish();
