-- Actual authenticated save -> manifest -> public calculate -> immutable candidate.
INSERT INTO platform_core.tenant_sites(tenant_id,id,legal_entity_id,display_name,is_default) VALUES('c4421000-0000-4000-8000-000000000001','c4423500-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','Statutory source site',false);
INSERT INTO people.work_assignments(tenant_id,id,employment_id,site_id,valid_from) VALUES('c4421000-0000-4000-8000-000000000001','c4426500-0000-4000-8000-000000000001','c4425000-0000-4000-8000-000000000001','c4423500-0000-4000-8000-000000000001','2030-01-01');
CREATE FUNCTION pg_temp.save(k text,d jsonb,h uuid DEFAULT NULL,r integer DEFAULT 0,op text DEFAULT 'save',ef date DEFAULT '2030-01-25') RETURNS jsonb LANGUAGE sql AS $$
 SELECT public.payroll_save_input('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001',k,CASE WHEN k IN('recurring','manual_units','adjustment','opening_ytd','statutory_context') THEN 'c4425000-0000-4000-8000-000000000001'::uuid END,CASE WHEN k IN('manual_units','adjustment') THEN current_setting('test.period')::uuid END,h,r,ef,CASE WHEN k IN('manual_units','adjustment') THEN '2030-02-25'::date END,d,op,gen_random_uuid()) $$;
GRANT EXECUTE ON FUNCTION pg_temp.save(text,jsonb,uuid,integer,text,date) TO authenticated;
SET LOCAL ROLE authenticated;
SELECT set_config('request.jwt.claim.sub','c4420000-0000-4000-8000-000000000001',true);
SELECT set_config('test.period',(public.payroll_save_calendar('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','2030-01-25',24,25,'ending','Africa/Cairo',0,gen_random_uuid(),public.payroll_calendar_preview('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','2030-01-25',24,25,'ending','Africa/Cairo'),'Source annotation fixture')->>'period_id'),true);
SELECT pg_temp.save('policy','{"mode":"calendar_days","reason":"Reviewed source test"}');
SELECT set_config('test.component.data','{"key":"source_allowance","name":"Allowance","classification":"earning","calculation":"fixed","base":"","value":"300","taxable":"false","social":"true","visible":"false","active":"true","order":"10","behavior":"recurring","reason":"Reviewed source facts"}',true);
SELECT set_config('test.component',pg_temp.save('component',current_setting('test.component.data')::jsonb)::text,true);
SELECT pg_temp.save('recurring',jsonb_build_object('component_id',current_setting('test.component')::jsonb->>'id','value','300','reason','Reviewed assignment'));
SELECT set_config('test.units',pg_temp.save('manual_units','{"units":"5","source":"manual","basis":"approved_payable_total","reference":"Reviewed units","reason":"Reviewed total"}')::text,true);
SELECT pg_temp.save('manual_units','{"units":"5","source":"manual","basis":"approved_payable_total","reference":"Reviewed units","reason":"Reviewed total"}',(current_setting('test.units')::jsonb->>'id')::uuid,1,'approve');
SELECT set_config('test.bonus',pg_temp.save('component',current_setting('test.component.data')::jsonb||'{"key":"source_bonus","name":"Bonus","behavior":"period_input","taxable":"true","social":"false","visible":"true"}')::text,true);
SELECT set_config('test.adjustment.data',jsonb_build_object('component_id',current_setting('test.bonus')::jsonb->>'id','amount','40','reference','Reviewed bonus','reason','Reviewed single bonus')::text,true);
SELECT set_config('test.adjustment',pg_temp.save('adjustment',current_setting('test.adjustment.data')::jsonb)::text,true);
SELECT pg_temp.save('adjustment',current_setting('test.adjustment.data')::jsonb,(current_setting('test.adjustment')::jsonb->>'id')::uuid,1,'approve');
SELECT set_config('test.run',public.payroll_run_command('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001',current_setting('test.period')::uuid,NULL,0,'calculate','',gen_random_uuid())::text,true);
RESET ROLE;
CREATE FUNCTION pg_temp.employee() RETURNS jsonb LANGUAGE sql AS $$ SELECT output->'employees'->0 FROM payroll.candidates WHERE id=(current_setting('test.run')::jsonb->>'candidate_id')::uuid $$;
CREATE FUNCTION pg_temp.sources() RETURNS jsonb LANGUAGE sql AS $$ SELECT pg_temp.employee()->'statutory_sources' $$;
CREATE FUNCTION pg_temp.recalculate() RETURNS jsonb LANGUAGE sql AS $$ SELECT public.payroll_run_command('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001',current_setting('test.period')::uuid,(current_setting('test.run')::jsonb->>'id')::uuid,(current_setting('test.run')::jsonb->>'revision')::integer,'calculate','',gen_random_uuid()) $$;
GRANT EXECUTE ON FUNCTION pg_temp.recalculate() TO authenticated;
SELECT ok(EXISTS(SELECT 1 FROM jsonb_array_elements(pg_temp.employee()->'issues')i WHERE i->>'code'='employee_statutory_context_missing'),'actual initial candidate identifies missing employee facts');
SELECT is(pg_temp.sources()->'contexts','[]'::jsonb,'missing facts never imply not insured');
SELECT set_config('test.first.sources',pg_temp.sources()::text,true);
SET LOCAL ROLE authenticated;
SELECT set_config('test.context',pg_temp.save('statutory_context','{"tax_treatment_code":"01","insurance_status":"insured","insurance_category":"Reviewed source category","insured_wage":"100","insurance_from":"2030-01-01","reference":"Reviewed insurance record","reason":"Reviewed employee facts"}')::text,true);
SELECT pg_temp.save('opening_ytd','{"year":"2030","taxable_earnings":"0","tax_withheld":"0","tax_due":"0","social_base":"0","employee_social":"0","employer_social":"0","coverage_start":"2030-01-01","coverage_end":"2030-01-24","tax_duration_days":"20","reference":"Reviewed opening facts","reason":"Explicit prior facts"}');
SELECT set_config('test.run',pg_temp.recalculate()::text,true);
RESET ROLE;
SELECT is(jsonb_array_length(pg_temp.sources()->'contexts'),1,'actual full-period employee source resolves one span');
SELECT is(pg_temp.sources()->'contexts'->0->>'from','2030-01-25','source span starts at actual earning boundary');
SELECT is(pg_temp.sources()->'contexts'->0->>'through','2030-02-24','source span covers actual31 day cycle');
SELECT is(pg_temp.sources()->'contexts'->0->'source'->'version'->'data'->>'insured_wage','100','insured wage preserved independently of gross');
SELECT is(pg_temp.sources()->'openings'->0->'source'->'version'->'data'->>'tax_duration_days','20','prior duration remains explicit20, not31 cycle days');
SELECT is(pg_temp.sources()->'issues','[]'::jsonb,'complete reviewed facts resolve source blockers but not legal pack');
SELECT is(pg_temp.employee()->>'net',NULL::text,'complete source facts do not activate unqualified net');
SELECT set_config('test.full.sources',pg_temp.sources()::text,true);
SET LOCAL ROLE authenticated;
SELECT pg_temp.save('statutory_context','{"tax_treatment_code":"01","insurance_status":"not_insured","reference":"Reviewed status transition","reason":"Reviewed source status"}',(current_setting('test.context')::jsonb->>'id')::uuid,1,'save','2030-02-01');
SELECT set_config('test.run',pg_temp.recalculate()::text,true);
RESET ROLE;
SELECT is(jsonb_array_length(pg_temp.sources()->'contexts'),2,'inside-period change retains both dated source versions');
SELECT is(pg_temp.sources()->'contexts'->0->>'through','2030-01-31','first version ends immediately before successor');
SELECT is(pg_temp.sources()->'contexts'->1->'source'->'version'->'data'->>'insurance_status','not_insured','successor status remains explicit fact');
SELECT ok(NOT(pg_temp.sources()->'contexts'->1->'source'->'version'->'data' ? 'insured_wage'),'not-insured version has no invented zero insured wage');
SELECT is(current_setting('test.full.sources')::jsonb->'contexts'->0->>'through','2030-02-24','previous source snapshot stays unchanged');
-- Existing save helper has no until argument: use actual public command for finite expiry.
SET LOCAL ROLE authenticated;
SELECT public.payroll_save_input('c4421000-0000-4000-8000-000000000001','c4423000-0000-4000-8000-000000000001','statutory_context','c4425000-0000-4000-8000-000000000001',NULL,(current_setting('test.context')::jsonb->>'id')::uuid,2,'2030-02-10','2030-02-15','{"tax_treatment_code":"01","insurance_status":"insured","insurance_category":"Reviewed source category","insured_wage":"100","insurance_from":"2030-01-01","reference":"Reviewed expiry","reason":"Finite source coverage"}','save',gen_random_uuid());
SELECT set_config('test.run',pg_temp.recalculate()::text,true);
RESET ROLE;
SELECT is(jsonb_array_length(pg_temp.sources()->'contexts'),3,'finite source retains all3 actual spans');
SELECT is(pg_temp.sources()->'contexts'->2->>'through','2030-02-14','exclusive expiry stops current source');
SELECT ok(EXISTS(SELECT 1 FROM jsonb_array_elements(pg_temp.sources()->'issues')i WHERE i->>'code'='employee_statutory_context_missing'),'expiry produces gap instead of resurrecting older status');
SELECT ok(NOT has_function_privilege('authenticated','payroll.employee_statutory_sources(jsonb,jsonb)','EXECUTE'),'source resolver remains private');
SELECT * FROM finish();
