'use client';
import { useRef, useState, type FormEvent, type ReactNode } from 'react';
import { useRouter } from 'next/navigation';
import { mutateChannel } from './actions';
import type { Mapping, Options, Source } from './shared';
function MutationForm({tenantId,operation,children,label,created=false}:{tenantId:string;operation:'save'|'map'|'reprocess'|'review';children:ReactNode;label:string;created?:boolean}) {
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const flight=useRef(false),status=useRef<HTMLParagraphElement>(null);const router=useRouter();
  async function submit(event:FormEvent<HTMLFormElement>) {event.preventDefault();if(flight.current) return;const data=new FormData(event.currentTarget);if(operation==='map') {for(const key of ['valid_from','valid_until']) {const value=String(data.get(key)??'');if(value && !/Z$|[+-]\d{2}:\d{2}$/.test(value)) {const date=new Date(value+'Z');if(Number.isFinite(date.getTime())) data.set(key,date.toISOString());}}}flight.current=true;setBusy(true);setMessage('جارٍ حفظ الإجراء…');try {const result=await mutateChannel(tenantId,operation,data);setMessage(result.message);if(result.ok) {if(created && result.id) router.push(`/tenant/${tenantId}/attendance/sources/${result.id}`);else router.refresh();}} catch {setMessage('لم يتأكد حفظ الإجراء. بقيت القيم؛ تحقق من السجل قبل إعادة المحاولة.');} finally {flight.current=false;setBusy(false);requestAnimationFrame(()=>status.current?.focus());}}
  return <form className="auth-form channel-form" onSubmit={submit} aria-busy={busy}><fieldset disabled={busy}>{children}<button className="primary-button" type="submit">{busy?'جارٍ الحفظ…':label}</button></fieldset><p className="channel-outcome" role="status" aria-live="polite" tabIndex={-1} ref={status}>{message}</p></form>;
}
const numericFields:Array<[string,string,number,number]>=[['latitude','خط العرض',-90,90],['longitude','خط الطول',-180,180],['radius_m','نصف قطر النطاق بالمتر',10,10000],['tolerance_m','هامش السماح بالمتر',0,500],['max_accuracy_m','أقصى خطأ مسموح للموقع بالمتر',1,500],['max_age_seconds','أقصى عمر لدليل الموقع بالثانية',5,600]];
export function SourceForm({tenantId,source,options,disableOnly=false}:{tenantId:string;source?:Source;options:Options;disableOnly?:boolean}) {
  const [kind,setKind]=useState(source?.kind??''),[geofence,setGeofence]=useState(source?.config?.geofence===undefined?'':String(source.config.geofence));
  const prefix=disableOnly?'disable':'source';
  const sites=options.sites.some(s=>s.id===source?.site_id)?options.sites:source?.site_id?[{id:source.site_id,display_name:source.site_name??'موقع القناة'},...options.sites]:options.sites;
  if(disableOnly && source) return <MutationForm tenantId={tenantId} operation="save" label="إيقاف استقبال حركات جديدة"><input type="hidden" name="source" value={source.id}/><input type="hidden" name="name" value={source.name}/><input type="hidden" name="kind" value={source.kind}/><input type="hidden" name="site" value={source.site_id??''}/><input type="hidden" name="enabled" value="false"/>{Object.entries(source.config??{}).map(([key,value])=><input key={key} type="hidden" name={key} value={String(value)}/>)}<p>سيتوقف استقبال حركات جديدة. يبقى السجل والنتائج السابقة محفوظة.</p><label htmlFor={`${prefix}-reason`}>سبب الإيقاف</label><textarea id={`${prefix}-reason`} name="reason" minLength={3} maxLength={500} required/></MutationForm>;
  return <MutationForm tenantId={tenantId} operation="save" label={source?'حفظ إصدار جديد للقناة':'إنشاء القناة'} created={!source}>
    <input type="hidden" name="source" value={source?.id??''}/><label htmlFor={`${prefix}-name`}>اسم القناة</label><input id={`${prefix}-name`} name="name" defaultValue={source?.name??''} maxLength={100} required readOnly={Boolean(source)}/>
    <label htmlFor={`${prefix}-kind`}>نوع القناة</label><select id={`${prefix}-kind`} name="kind" value={kind} onChange={e=>setKind(e.target.value)} required disabled={Boolean(source)}><option value="">اختر النوع</option><option value="mobile">حضور الموظف من الهاتف</option><option value="external">مصدر خارجي</option></select>{source && <input type="hidden" name="kind" value={source.kind}/>}
    <label htmlFor={`${prefix}-site`}>موقع العمل</label><select id={`${prefix}-site`} name="site" defaultValue={source?.site_id??''} required={kind==='mobile'} disabled={Boolean(source)}><option value="">اختر الموقع</option>{sites.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select>{source && <input type="hidden" name="site" value={source.site_id??''}/>}
    <label htmlFor={`${prefix}-enabled`}>استقبال حركات جديدة</label><select id={`${prefix}-enabled`} name="enabled" defaultValue={source?String(source.enabled):''} required><option value="">اختر الحالة</option><option value="true">مفعّل</option><option value="false">موقوف</option></select>
    {kind==='mobile' && <><label htmlFor={`${prefix}-geofence`}>التحقق من نطاق الموقع</label><select id={`${prefix}-geofence`} name="geofence" value={geofence} onChange={e=>setGeofence(e.target.value)} required><option value="">اختر السياسة</option><option value="true">مطلوب</option><option value="false">غير مطلوب</option></select><label htmlFor={`${prefix}-retention`}>مدة الاحتفاظ بدليل الموقع بالثانية</label><input id={`${prefix}-retention`} name="retention_seconds" type="number" min={60} max={2592000} step={1} defaultValue={source?.config?.retention_seconds as number??''} required/><p className="field-hint">استخدم قيم سياسة الموقع والخصوصية المعتمدة. لا توجد قيم إنتاجية مفترضة هنا.</p>{geofence==='true' && <>{numericFields.map(([key,label,min,max])=><div key={key}><label htmlFor={`${prefix}-${key}`}>{label}</label><input id={`${prefix}-${key}`} name={key} type="number" step="any" min={min} max={max} defaultValue={source?.config?.[key] as number??''} required/></div>)}<label htmlFor={`${prefix}-failure`}>عند تعذر التحقق من النطاق</label><select id={`${prefix}-failure`} name="failure_action" defaultValue={source?.config?.failure_action as string??''} required><option value="">اختر النتيجة</option><option value="reject">رفض الحركة</option><option value="review">تسجيلها للمراجعة</option></select></>}</>}
    {kind==='external' && <p className="field-hint">هذه قناة عامة فقط. ربط جهاز فعلي يحتاج اعتماد بروتوكوله قبل تشغيل موصل خاص به.</p>}
    <label htmlFor={`${prefix}-reason`}>سبب إنشاء القناة أو تغييرها</label><textarea id={`${prefix}-reason`} name="reason" minLength={3} maxLength={500} required/>
  </MutationForm>;
}
function utcInstant(value:string|null|undefined) {return value?new Date(value).toISOString().slice(0,19):'';}
export function MappingForm({tenantId,sourceId,options,externalKey='',mapping}:{tenantId:string;sourceId:string;options:Options;externalKey?:string;mapping?:Mapping}) {
  const prefix=mapping?`map-${mapping.id}`:'mapping';
  const employees=mapping && !options.employees.some(e=>e.id===mapping.employee_id)?[{id:mapping.employee_id,full_name:mapping.employee_name,employee_code:''},...options.employees]:options.employees;
  const sites=mapping && !options.sites.some(s=>s.id===mapping.site_id)?[{id:mapping.site_id,display_name:mapping.site_name},...options.sites]:options.sites;
  return <MutationForm tenantId={tenantId} operation="map" label={mapping?'حفظ قرار جديد لهذه الفترة':'حفظ ربط الموظف'}><input type="hidden" name="source" value={sourceId}/><label htmlFor={`${prefix}-key`}>معرّف الموظف في المصدر</label><input id={`${prefix}-key`} name="external_key" defaultValue={mapping?.external_key??externalKey} maxLength={100} required readOnly={Boolean(mapping)}/><label htmlFor={`${prefix}-employee`}>الموظف</label><select id={`${prefix}-employee`} name="employee" defaultValue={mapping?.employee_id??''} required><option value="">اختر الموظف</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}{e.employee_code?` — ${e.employee_code}`:''}</option>)}</select><label htmlFor={`${prefix}-site`}>الموقع</label><select id={`${prefix}-site`} name="site" defaultValue={mapping?.site_id??''} required><option value="">اختر الموقع</option>{sites.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</select><label htmlFor={`${prefix}-from`}>بداية سريان الربط</label><input id={`${prefix}-from`} name={mapping?undefined:"valid_from"} type="datetime-local" step={1} defaultValue={utcInstant(mapping?.valid_from)} required readOnly={Boolean(mapping)}/><label htmlFor={`${prefix}-until`}>نهاية السريان، إن وجدت</label><input id={`${prefix}-until`} name={mapping?undefined:"valid_until"} type="datetime-local" step={1} defaultValue={utcInstant(mapping?.valid_until)} readOnly={Boolean(mapping)}/>{mapping && <><input type="hidden" name="valid_from" value={mapping.valid_from}/><input type="hidden" name="valid_until" value={mapping.valid_until??''}/></>}<p className="field-hint">الفترة بالتوقيت العالمي UTC، والنهاية غير مشمولة. يجب أن تغطي وقت الحركة. تجنب الفترات المتداخلة لنفس المعرّف.</p><label htmlFor={`${prefix}-active`}>قرار الربط</label><select id={`${prefix}-active`} name="active" defaultValue={mapping?String(!mapping.active):''} required><option value="">اختر القرار</option><option value="true">تفعيل الربط لهذه الفترة</option><option value="false">إلغاء الربط لهذه الفترة</option></select></MutationForm>;
}
export function EventActions({tenantId,eventId,canManage,canReview,needsReview}:{tenantId:string;eventId:string;canManage:boolean;canReview:boolean;needsReview:boolean}) { return <>{canManage && <MutationForm tenantId={tenantId} operation="reprocess" label="إعادة معالجة هذه الحركة"><input type="hidden" name="event" value={eventId}/></MutationForm>}{canReview && needsReview && <MutationForm tenantId={tenantId} operation="review" label="حفظ قرار المراجعة"><input type="hidden" name="event" value={eventId}/><label htmlFor="event-decision">قرار مراجعة الموقع</label><select id="event-decision" name="decision" required><option value="">اختر القرار</option><option value="accept">قبول الحركة</option><option value="exclude">استبعاد الحركة</option></select><label htmlFor="event-reason">سبب القرار</label><textarea id="event-reason" name="reason" required minLength={3} maxLength={500}/></MutationForm>}</>; }
