'use client';
import { Button, Input, Message, Select, Textarea, Field } from '@/components/ui';
import { useId } from 'react';
import { LocationPicker } from '@/components/patterns/location-picker/location-picker';
import { OfflineSubmissionNotice, useOfflineSubmission } from '@/components/offline-submission';
import styles from '../attendance-channels.module.css';
import { useRef, useState, useSyncExternalStore, type FormEvent, type ReactNode } from 'react';
import { useRouter } from 'next/navigation';
import { mutateChannel } from './actions';
import type { Mapping, Options, Source } from './shared';
const subscribeToReadiness = () => () => {};
const clientReady = () => true;
const serverReady = () => false;
function MutationForm({tenantId,operation,children,label,created=false}:{tenantId:string;operation:'save'|'map'|'reprocess'|'review';children:ReactNode;label:string;created?:boolean}) {
 const { offline, blockOfflineSubmission } = useOfflineSubmission();
 const offlineHint0 = useId();
  const ready=useSyncExternalStore(subscribeToReadiness,clientReady,serverReady);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const flight=useRef(false),status=useRef<HTMLParagraphElement>(null);const router=useRouter();
  async function submit(event:FormEvent<HTMLFormElement>) {
  if (blockOfflineSubmission(event)) return;event.preventDefault();if(flight.current) return;const data=new FormData(event.currentTarget);if(operation==='map') {for(const key of ['valid_from','valid_until']) {const value=String(data.get(key)??'');if(value && !/Z$|[+-]\d{2}:\d{2}$/.test(value)) {const date=new Date(value+'Z');if(Number.isFinite(date.getTime())) data.set(key,date.toISOString());}}}flight.current=true;setBusy(true);setMessage('جارٍ حفظ الإجراء…');try {const result=await mutateChannel(tenantId,operation,data);setMessage(result.message);if(result.ok) {if(created && result.id) router.push(`/tenant/${tenantId}/attendance/sources/${result.id}`);else router.refresh();}} catch {setMessage('لم يتأكد حفظ الإجراء. بقيت القيم؛ تحقق من السجل قبل إعادة المحاولة.');} finally {flight.current=false;setBusy(false);requestAnimationFrame(()=>status.current?.focus());}}
  const showOffline0 = offline && ready && !busy;
 return <form className="auth-form channel-form" method="post" onSubmit={submit} aria-busy={!ready||busy}><fieldset disabled={!ready||busy}>{children}<Button variant="solid"  type="submit" aria-describedby={showOffline0 ? offlineHint0 : undefined} disabled={offline}>{!ready?'جارٍ تجهيز النموذج…':busy?'جارٍ الحفظ…':label}</Button></fieldset><Message tone="info" className="channel-outcome" role="status" aria-live="polite" tabIndex={-1} ref={status}>{!ready?'جارٍ تجهيز النموذج. إذا استمر ذلك، أعد تحميل الصفحة.':message}</Message><noscript><p>يلزم تفعيل JavaScript لإرسال هذا النموذج، ثم إعادة تحميل الصفحة.</p></noscript>{showOffline0 && <OfflineSubmissionNotice id={offlineHint0} purpose="continuation" />}</form>;
}
const numericFields:Array<[string,string,number,number]>=[['latitude','خط العرض',-90,90],['longitude','خط الطول',-180,180],['radius_m','نصف قطر النطاق بالمتر',10,10000],['tolerance_m','هامش السماح بالمتر',0,500],['max_accuracy_m','أقصى خطأ مسموح للموقع بالمتر',1,500],['max_age_seconds','أقصى عمر لدليل الموقع بالثانية',5,600]];
export function SourceForm({tenantId,source,options,disableOnly=false}:{tenantId:string;source?:Source;options:Options;disableOnly?:boolean}) {
  const [kind,setKind]=useState(source?.kind??''),[geofence,setGeofence]=useState(source?.config?.geofence===undefined?'':String(source.config.geofence));
  const prefix=disableOnly?'disable':'source';
  const sites=options.sites.some(s=>s.id===source?.site_id)?options.sites:source?.site_id?[{id:source.site_id,display_name:source.site_name??'موقع القناة'},...options.sites]:options.sites;
  if(disableOnly && source) return <MutationForm tenantId={tenantId} operation="save" label="إيقاف استقبال حركات جديدة"><input type="hidden" name="source" value={source.id}/><input type="hidden" name="name" value={source.name}/><input type="hidden" name="kind" value={source.kind}/><input type="hidden" name="site" value={source.site_id??''}/><input type="hidden" name="enabled" value="false"/>{Object.entries(source.config??{}).map(([key,value])=><input key={key} type="hidden" name={key} value={String(value)}/>)}<p>سيتوقف استقبال حركات جديدة. يبقى السجل والنتائج السابقة محفوظة.</p><Field id={`${prefix}-reason`} label={<>سبب الإيقاف</>}><Textarea id={`${prefix}-reason`} name="reason" minLength={3} maxLength={500} required/></Field></MutationForm>;
  return <MutationForm tenantId={tenantId} operation="save" label={source?'حفظ إصدار جديد للقناة':'إنشاء القناة'} created={!source}>
    <fieldset className={styles.fieldGroup}><legend>هوية القناة واستقبال الحركات</legend><input type="hidden" name="source" value={source?.id??''}/><Field id={`${prefix}-name`} label={<>اسم القناة</>}><Input id={`${prefix}-name`} name="name" defaultValue={source?.name??''} maxLength={100} required readOnly={Boolean(source)}/></Field>
    <Field id={`${prefix}-kind`} label={<>نوع القناة</>}><Select id={`${prefix}-kind`} name="kind" value={kind} onChange={e=>setKind(e.target.value)} required disabled={Boolean(source)}><option value="">اختر النوع</option><option value="mobile">حضور الموظف من الهاتف</option><option value="external">مصدر خارجي</option></Select></Field>{source && <input type="hidden" name="kind" value={source.kind}/>}
    <Field id={`${prefix}-site`} label={<>موقع العمل</>}><Select id={`${prefix}-site`} name="site" defaultValue={source?.site_id??''} required={kind==='mobile'} disabled={Boolean(source)}><option value="">اختر الموقع</option>{sites.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</Select></Field>{source && <input type="hidden" name="site" value={source.site_id??''}/>}
    <Field id={`${prefix}-enabled`} label={<>استقبال حركات جديدة</>}><Select id={`${prefix}-enabled`} name="enabled" defaultValue={source?String(source.enabled):''} required><option value="">اختر الحالة</option><option value="true">مفعّل</option><option value="false">موقوف</option></Select></Field>
    </fieldset>{kind==='mobile' && <fieldset className={styles.fieldGroup}><legend>سياسة الموقع والخصوصية</legend><Field id={`${prefix}-geofence`} label={<>التحقق من نطاق الموقع</>}><Select id={`${prefix}-geofence`} name="geofence" value={geofence} onChange={e=>setGeofence(e.target.value)} required><option value="">اختر السياسة</option><option value="true">مطلوب</option><option value="false">غير مطلوب</option></Select></Field><Field id={`${prefix}-retention`} label={<>مدة الاحتفاظ بدليل الموقع بالثانية</>}><Input id={`${prefix}-retention`} name="retention_seconds" type="number" min={60} max={2592000} step={1} defaultValue={source?.config?.retention_seconds as number??''} required/></Field><p className="field-hint">استخدم قيم سياسة الموقع والخصوصية المعتمدة. لا توجد قيم إنتاجية مفترضة هنا.</p>{geofence==='true' && <><LocationPicker prefix={prefix} latitude={source?.config?.latitude as number | undefined} longitude={source?.config?.longitude as number | undefined} radius={source?.config?.radius_m as number | undefined}/>{numericFields.filter(([key])=>!['latitude','longitude','radius_m'].includes(key)).map(([key,label,min,max])=><div key={key}><Field id={`${prefix}-${key}`} label={<>{label}</>}><Input id={`${prefix}-${key}`} name={key} type="number" step="any" min={min} max={max} defaultValue={source?.config?.[key] as number??''} required/></Field></div>)}<label htmlFor={`${prefix}-failure`}>عند تعذر التحقق من النطاق</label><Select id={`${prefix}-failure`} name="failure_action" defaultValue={source?.config?.failure_action as string??''} required><option value="">اختر النتيجة</option><option value="reject">رفض الحركة</option><option value="review">تسجيلها للمراجعة</option></Select></>}</fieldset>}
    {kind==='external' && <p className="field-hint">هذه قناة عامة فقط. ربط جهاز فعلي يحتاج اعتماد بروتوكوله قبل تشغيل موصل خاص به.</p>}
    <fieldset className={styles.fieldGroup}><legend>سبب القرار</legend><Field id={`${prefix}-reason`} label={<>سبب إنشاء القناة أو تغييرها</>}><Textarea id={`${prefix}-reason`} name="reason" minLength={3} maxLength={500} required/></Field>
    </fieldset>
  </MutationForm>;
}
function utcInstant(value:string|null|undefined) {return value?new Date(value).toISOString().slice(0,19):'';}
export function MappingForm({tenantId,sourceId,options,externalKey='',mapping}:{tenantId:string;sourceId:string;options:Options;externalKey?:string;mapping?:Mapping}) {
  const prefix=mapping?`map-${mapping.id}`:'mapping';
  const employees=mapping && !options.employees.some(e=>e.id===mapping.employee_id)?[{id:mapping.employee_id,full_name:mapping.employee_name,employee_code:''},...options.employees]:options.employees;
  const sites=mapping && !options.sites.some(s=>s.id===mapping.site_id)?[{id:mapping.site_id,display_name:mapping.site_name},...options.sites]:options.sites;
  return <MutationForm tenantId={tenantId} operation="map" label={mapping?'حفظ قرار جديد لهذه الفترة':'حفظ ربط الموظف'}><input type="hidden" name="source" value={sourceId}/><Field id={`${prefix}-key`} label={<>معرّف الموظف في المصدر</>}><Input id={`${prefix}-key`} name="external_key" defaultValue={mapping?.external_key??externalKey} maxLength={100} required readOnly={Boolean(mapping)}/></Field><Field id={`${prefix}-employee`} label={<>الموظف</>}><Select id={`${prefix}-employee`} name="employee" defaultValue={mapping?.employee_id??''} required><option value="">اختر الموظف</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}{e.employee_code?` — ${e.employee_code}`:''}</option>)}</Select></Field><Field id={`${prefix}-site`} label={<>الموقع</>}><Select id={`${prefix}-site`} name="site" defaultValue={mapping?.site_id??''} required><option value="">اختر الموقع</option>{sites.map(s=><option key={s.id} value={s.id}>{s.display_name}</option>)}</Select></Field><Field id={`${prefix}-from`} label={<>بداية سريان الربط</>}><Input id={`${prefix}-from`} name={mapping?undefined:"valid_from"} type="datetime-local" step={1} defaultValue={utcInstant(mapping?.valid_from)} required readOnly={Boolean(mapping)}/></Field><Field id={`${prefix}-until`} label={<>نهاية السريان، إن وجدت</>}><Input id={`${prefix}-until`} name={mapping?undefined:"valid_until"} type="datetime-local" step={1} defaultValue={utcInstant(mapping?.valid_until)} readOnly={Boolean(mapping)}/></Field>{mapping && <><input type="hidden" name="valid_from" value={mapping.valid_from}/><input type="hidden" name="valid_until" value={mapping.valid_until??''}/></>}<p className="field-hint">الفترة بالتوقيت العالمي UTC، والنهاية غير مشمولة. يجب أن تغطي وقت الحركة. تجنب الفترات المتداخلة لنفس المعرّف.</p><Field id={`${prefix}-active`} label={<>قرار الربط</>}><Select id={`${prefix}-active`} name="active" defaultValue={mapping?String(!mapping.active):''} required><option value="">اختر القرار</option><option value="true">تفعيل الربط لهذه الفترة</option><option value="false">إلغاء الربط لهذه الفترة</option></Select></Field></MutationForm>;
}
export function EventActions({tenantId,eventId,canManage,canReview,needsReview}:{tenantId:string;eventId:string;canManage:boolean;canReview:boolean;needsReview:boolean}) { return <>{canManage && <MutationForm tenantId={tenantId} operation="reprocess" label="إعادة معالجة هذه الحركة"><input type="hidden" name="event" value={eventId}/></MutationForm>}{canReview && needsReview && <MutationForm tenantId={tenantId} operation="review" label="حفظ قرار المراجعة"><input type="hidden" name="event" value={eventId}/><Field id="event-decision" label={<>قرار مراجعة الموقع</>}><Select id="event-decision" name="decision" required><option value="">اختر القرار</option><option value="accept">قبول الحركة</option><option value="exclude">استبعاد الحركة</option></Select></Field><Field id="event-reason" label={<>سبب القرار</>}><Textarea id="event-reason" name="reason" required minLength={3} maxLength={500}/></Field></MutationForm>}</>; }
