import { DecisionPanel } from '@/components/patterns/decision-panel/decision-panel';
import Link from 'next/link';
import styles from '../../../../attendance-channels.module.css';
import { notFound } from 'next/navigation';
import { PageFrame } from '@/components/context-navigation';
import { channelReasonLabel,channelStateLabel,formatChannelInstant } from '@/lib/attendance-channel';
import { EventActions,MappingForm } from '../../../ChannelForms';
import { channelSession,channelHref,ChannelUnavailable,type EventDetail,type Options } from '../../../shared';
export const dynamic='force-dynamic';
export default async function EventPage({params,searchParams}:{params:Promise<{tenantId:string;sourceId:string;eventId:string}>;searchParams:Promise<{q?:string;siteQ?:string}>}) {
 const {tenantId,sourceId,eventId}=await params,{q='',siteQ=''}=await searchParams,session=await channelSession(tenantId);const retryHref=channelHref(`/tenant/${tenantId}/attendance/sources/${sourceId}/events/${eventId}`,{q,siteQ});if(!session) return <ChannelUnavailable tenantId={tenantId} retryHref={retryHref}/>;
 const {data,error}=await session.db.rpc('attendance_channel_event_detail',{p_tenant:tenantId,p_event:eventId});if(error) return <ChannelUnavailable tenantId={tenantId} retryHref={retryHref}/>;const event=data as EventDetail;if(event.source_id!==sourceId) notFound();
 const latest=event.results[0],options=session.access.can_manage?await session.db.rpc('attendance_channel_options',{p_tenant:tenantId,p_search:q.slice(0,100),p_limit:20}):{data:{employees:[],sites:[]},error:null};
 const siteOptions=session.access.can_manage?await session.db.rpc('attendance_channel_options',{p_tenant:tenantId,p_search:siteQ.slice(0,100),p_limit:20}):{data:{employees:[],sites:[]},error:null};
 return <PageFrame><div className="channel-page"><Link className="secondary-button" href={`/tenant/${tenantId}/attendance/sources/${sourceId}`}>العودة إلى القناة</Link><header className="workspace-page-heading"><div><h1>حركة {event.direction==='in'?'حضور':event.direction==='out'?'انصراف':'تحتاج مراجعة'}</h1><p>{event.source_name} · {channelStateLabel(latest?.state??'received')}</p><p>{formatChannelInstant(event.happened_at,'UTC')} (UTC)</p></div></header><nav className={styles.sectionNav} aria-label="أقسام الحركة"><a href="#channel-event-task">النتيجة والإجراء</a><a href="#channel-event-decisions">قرارات الموقع</a><a href="#channel-event-history">نتائج المعالجة</a>{event.replays.length>0 && <a href="#channel-event-replays">إعادة الإرسال</a>}</nav>
 <DecisionPanel id="channel-event-task" kind="مراجعة حركة حضور" title="نتيجة الحركة والخطوة التالية" values={[{label: 'القناة', value:event.source_name},{label: 'وقت الحركة',value:formatChannelInstant(event.happened_at,'UTC')},{label: 'الحالة',value:channelStateLabel(latest?.state??'received')}]} facts={[{text:'قبول الحركة أو استبعادها يحفظ قرار المراجعة وسببه؛ يبقى الدليل وسجل المعالجة محفوظين.'}]}>{latest?.reason && <p className="form-message">{channelReasonLabel(latest.reason)}</p>}{event.review_required && <p>سُجلت الحركة وتحتاج قرار مراجعة الموقع.</p>}{event.kind==='external' && latest?.state==='unmapped' && session.access.can_manage && (options.error || siteOptions.error) && <p className="form-message form-error" role="alert">تعذر تحميل خيارات الربط. <Link href={retryHref}>إعادة تحميل الخيارات</Link></p>}<EventActions tenantId={tenantId} eventId={eventId} canManage={session.access.can_manage} canReview={session.access.can_review} needsReview={event.review_required}/>{latest?.work_instance_id && <Link className="secondary-button" href={`/tenant/${tenantId}/attendance/${latest.work_instance_id}`}>فتح سجل يوم العمل</Link>}
 {event.kind==='external' && latest?.state==='unmapped' && session.access.can_manage && !options.error && !siteOptions.error && <details className="task-disclosure" open><summary>ربط هذه الحركة بموظف</summary><form method="get" className="channel-search"><label htmlFor="event-search">ابحث عن موظف</label><input id="event-search" name="q" defaultValue={q} maxLength={100}/><label htmlFor="event-site-search">ابحث عن موقع</label><input id="event-site-search" name="siteQ" defaultValue={siteQ} maxLength={100}/><button className="secondary-button">البحث</button></form><p className="field-hint">أول 20 نتيجة. بعد حفظ الربط أعد معالجة هذه الحركة.</p><MappingForm tenantId={tenantId} sourceId={sourceId} options={{employees:(options.data as Options).employees,sites:(siteOptions.data as Options).sites}} externalKey={event.external_key??''}/></details>}</DecisionPanel>
 <section className="workspace-records-panel"><h2 id="channel-event-decisions">قرارات مراجعة الموقع</h2>{event.review_decisions?.length?<ul className="record-list">{event.review_decisions.map((decision,index)=><li className="record-card" key={index}><div><h3>{decision.decision==='accept'?'قبول الحركة':'استبعاد الحركة'}</h3><p>المراجع: {decision.actor_label}</p><p>{decision.reason}</p><p>{formatChannelInstant(decision.created_at,decision.timezone_name)}{decision.timezone_name==='UTC'?' (UTC)':''}</p></div></li>)}</ul>:<p>{event.review_required?'لم يُحفظ قرار بعد. تحتاج الحركة مراجعة دليل الموقع.':'لا توجد قرارات مراجعة موقع لهذه الحركة.'}</p>}</section>
 <section className="workspace-records-panel"><h2 id="channel-event-history">سجل نتائج المعالجة</h2><ul className="record-list">{event.results.map(r=><li className="record-card" key={r.id}><div><h3>{channelStateLabel(r.state)}</h3><p>{formatChannelInstant(r.created_at,'UTC')} (UTC)</p>{r.reason && <p>{channelReasonLabel(r.reason)}</p>}</div></li>)}</ul><p className="field-hint">آخر 20 نتيجة. تبقى النتائج السابقة محفوظة بعد إعادة المعالجة.</p></section>
 {event.replays.length>0 && <section className="workspace-records-panel"><h2 id="channel-event-replays">محاولات إعادة الإرسال</h2><ul className="record-list">{event.replays.map(r=><li className="record-card" key={r.id}><div><p>{r.state==='conflict'?'رُفض إرسال بنفس الهوية وبيانات مختلفة':'إرسال مكرر دون حركة جديدة'}</p><p>{formatChannelInstant(r.created_at,'UTC')} (UTC)</p></div></li>)}</ul></section>}
 <details className="workspace-records-panel task-disclosure"><summary>تفاصيل الدعم</summary><dl><dt>معرّف الحدث في المصدر</dt><dd><bdi>{event.event_key??'غير متاح'}</bdi></dd><dt>معرّف الموظف في المصدر</dt><dd><bdi>{event.external_key??'غير متاح'}</bdi></dd><dt>إصدار سياسة القناة</dt><dd>{event.source_version}</dd><dt>وقت وصول الحركة</dt><dd>{formatChannelInstant(event.received_at,'UTC')} (UTC)</dd></dl></details></div></PageFrame>;
}
