'use client';
import { Button, Disclosure, Input, Message, Panel, Select, Textarea } from '@/components/ui';
import {useId,useState,useSyncExternalStore} from 'react';
import {OfflineSubmissionNotice,useOfflineSubmission} from '@/components/offline-submission';
import {useRouter} from 'next/navigation';
import {advanceAction} from './actions';
import {labels,type AdvanceJournal,type AdvanceOperation,type Choice} from './rules';
import styles from '../payroll.module.css';
import {uuid} from '../rules';
const event='advance-journal-change';
function read(key:string){try{return localStorage.getItem(key);}catch{return null;}}
async function write(key:string,record:AdvanceJournal|null,expectedAttempt?:string){
 if(!navigator.locks)throw new Error('safe_storage_unavailable');
 return navigator.locks.request(key,()=>{
  const raw=read(key);let current:AdvanceJournal|null=null;if(raw){const parsed:unknown=JSON.parse(raw);if(!validJournal(parsed))return false;current=parsed;}
  if(expectedAttempt?current?.attempt!==expectedAttempt:current?.resolution!==undefined&&current.resolution!=='closed_without_commit'||current!==null&&current.resolution===undefined)return false;
  if(record)localStorage.setItem(key,JSON.stringify(record));else localStorage.removeItem(key);window.dispatchEvent(new Event(event));return true;
 });
}
function subscribe(listener:()=>void){window.addEventListener('storage',listener);window.addEventListener(event,listener);return ()=>{window.removeEventListener('storage',listener);window.removeEventListener(event,listener);};}
function validJournal(value:unknown):value is AdvanceJournal{
 if(!value||typeof value!=='object')return false;const j=value as Partial<AdvanceJournal>;
 return j.version===1&&[j.actor,j.tenant,j.employer,j.attempt,j.intent?.advance,j.intent?.employment].every(v=>typeof v==='string'&&uuid(v))&&!!j.intent&&Object.hasOwn(labels,j.intent.operation)&&Number.isSafeInteger(j.intent.expected)&&j.intent.expected>=0&&!!j.intent.data&&typeof j.intent.data==='object'&&Object.entries(j.intent.data).length<=16&&Object.values(j.intent.data).every(v=>typeof v==='string'&&v.length<=500)&&(j.resolution===undefined||j.resolution==='closed_without_commit');
}
function useJournal(actor:string,tenant:string,employer:string){const key=`employee-advance:v1:${JSON.stringify([actor,tenant,employer])}`,raw=useSyncExternalStore(subscribe,()=>read(key),()=>null);let record:AdvanceJournal|null=null;try{const parsed:unknown=raw?JSON.parse(raw):null;record=validJournal(parsed)?parsed:null;}catch{/* A malformed journal must be investigated, never silently replaced. */}return {key,record,corrupt:raw!==null&&(!record||record.actor!==actor||record.tenant!==tenant||record.employer!==employer),unresolved:raw!==null&&record?.resolution!=='closed_without_commit'};}
type Scope={actor:string;tenant:string;employer:string};
export function AdvanceRecovery(props:Scope){
 const {key,record,corrupt,unresolved}=useJournal(props.actor,props.tenant,props.employer),[pending,setPending]=useState(false),[message,setMessage]=useState(''),router=useRouter();
 async function resolve(){if(!record||corrupt)return;setPending(true);setMessage('');try{const result=await advanceAction(record,true);if(result.resolution==='committed'){await write(key,null,record.attempt);setMessage('تأكد حفظ الطلب الأصلي مرة واحدة.');if(result.result)router.replace(`/tenant/${props.tenant}/payroll/advances?${new URLSearchParams({employer:props.employer,advance:result.result.id})}`);router.refresh();}else if(result.resolution==='closed_without_commit'){await write(key,{...record,resolution:'closed_without_commit'},record.attempt);setMessage('تأكد أن الطلب لم يُحفظ وأُغلقت محاولته. يمكنك مراجعة القيم المحفوظة وإرسال طلب جديد.');router.refresh();}else setMessage(result.error??'لم تتأكد النتيجة بعد.');}catch{setMessage('تعذر التحقق؛ المحاولة الأصلية والقيم محفوظة.');}finally{setPending(false);}}
 if(!record&&!corrupt&&!message)return null;
 return <Panel className={styles.card} role="status"><h2>{unresolved?'تحقّق من نتيجة الطلب السابق':'نتيجة التحقق'}</h2>{corrupt?<p>تعذر قراءة سجل المحاولة المحلية. لا ترسل عملية مالية أخرى؛ اطلب من مسؤول الدعم مراجعة هذا السجل معك.</p>:record&&<><p>{labels[record.intent.operation]} · لا تغيّر المرجع أو المبلغ قبل حسم النتيجة.</p><Disclosure summary={<>القيم الأصلية المحفوظة</>}><dl>{Object.entries(record.intent.data).map(([k,v])=><div key={k}><dt>{({principal:'أصل السلفة',amount:'المبلغ',reference:'المرجع',reason:'السبب',date:'التاريخ',count:'عدد الأقساط',installment_amount:'قيمة القسط',effective_on:'تاريخ السريان'} as Record<string,string>)[k]??'مرجع بيانات محفوظ'}</dt><dd><bdi>{v}</bdi></dd></div>)}</dl></Disclosure>{unresolved&&<Button variant="solid" type="button" disabled={pending} onClick={resolve}>{pending?'جارٍ التحقق…':'التحقق من نتيجة الطلب السابق'}</Button>}</>}{message&&<p>{message}</p>}</Panel>;
}
type Props=Scope&{operation:AdvanceOperation;advance:string;employment:string;revision:number;today:string;periods?:Choice[];principal?:string;effectiveOn?:string;count?:number;firstPeriod?:string;reason?:string;original?:string;installment?:string;correctionCase?:string;correctionChoices?:Choice[];correctedAdvance?:string};
export function AdvanceForm(props:Props){
 const {offline,blockOfflineSubmission}=useOfflineSubmission(),offlineHintId=useId();
 const {key,record,corrupt,unresolved}=useJournal(props.actor,props.tenant,props.employer),[pending,setPending]=useState(false),[message,setMessage]=useState(''),router=useRouter();
 const effectiveAdvance=props.operation==='save'&&props.revision===0&&record?.intent.operation==='save'&&record.intent.employment===props.employment?record.intent.advance:props.advance;
 const showOfflineNotice=offline&&!pending&&!unresolved&&!corrupt;
 const restored=record?.intent.operation===props.operation&&record.intent.advance===effectiveAdvance&&(!props.original||record.intent.data.original===props.original)&&(!props.installment||record.intent.data.installment===props.installment)?record.intent.data:{};
 async function submit(form:HTMLFormElement){if(blockOfflineSubmission())return;if(unresolved||corrupt||pending)return;setMessage('');const data:Record<string,string>={};new FormData(form).forEach((value,k)=>{if(typeof value==='string'&&value.trim())data[k]=value.trim();});
 const journal:AdvanceJournal={version:1,actor:props.actor,tenant:props.tenant,employer:props.employer,attempt:crypto.randomUUID(),intent:{operation:props.operation,advance:effectiveAdvance,employment:props.employment,expected:props.revision,data}};
 try{if(!await write(key,journal)){setMessage('يوجد طلب سابق لنفس الاختيارات. تحقّق من نتيجته قبل إرسال عملية أخرى.');return;}}catch{setMessage('تعذر حفظ محاولة آمنة على هذا الجهاز. لم يُرسل الطلب؛ استخدم متصفحًا يدعم التخزين والأقفال الآمنة ثم أعد المحاولة.');return;}
 setPending(true);try{const result=await advanceAction(journal,false);if(result.resolution==='committed'){await write(key,null,journal.attempt);router.replace(`/tenant/${props.tenant}/payroll/advances?${new URLSearchParams({employer:props.employer,advance:result.result?.id??props.advance})}`);router.refresh();setMessage('حُفظت العملية وأثرها في السجل.');}else setMessage(result.error??'تحقّق من الطلب السابق قبل المتابعة.');}catch{setMessage('انقطعت الاستجابة؛ تحقّق من الطلب السابق قبل المتابعة.');}finally{setPending(false);}}
 return <form key={record?.resolution==='closed_without_commit'?record.attempt:'current'} className={styles.form} onReset={e=>e.preventDefault()} onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}><fieldset className={styles.paymentFields} disabled={pending||unresolved||corrupt}><legend>{labels[props.operation]}</legend>
 {props.operation==='save'?<>{props.correctedAdvance&&<input type="hidden" name="corrected_advance" value={props.correctedAdvance}/>}<label>أصل السلفة بالجنيه<Input name="principal" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" required defaultValue={restored.principal??props.principal}/></label><label>تاريخ سريان السلفة<Input type="date" name="effective_on" required defaultValue={restored.effective_on??props.effectiveOn}/></label><label>الفترة الأولى للخصم<Select name="first_period" required defaultValue={restored.first_period??props.firstPeriod??''}><option value="">اختر فترة محفوظة</option>{props.periods?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></label><label>عدد الأقساط<Input name="count" type="number" min="1" max="120" required defaultValue={restored.count??props.count??1}/></label><p>تقسّم القيمة بالقروش بالتساوي؛ القسط الأخير يحمل الباقي. يجب حفظ الفترات اللازمة قبل اعتماد الجدول.</p></>:<><input type="hidden" name="confirmed" value="yes"/><label>تاريخ العملية<Input name="date" type="date" max={props.today} defaultValue={restored.date??props.today} required/></label><label>المرجع الخارجي أو مرجع المراجعة<Input name="reference" minLength={3} maxLength={160} defaultValue={restored.reference??''} required/></label>{props.operation==='settle'&&<label>المبلغ المسدد بالجنيه<Input name="amount" inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" required defaultValue={restored.amount}/></label>}{props.operation==='defer'&&<label>الفترة اللاحقة للخصم<Select name="target_period" required defaultValue={restored.target_period??''}><option value="">اختر فترة لاحقة غير مقفلة</option>{props.periods?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select></label>}{props.original&&<input type="hidden" name="original" value={props.original}/>}{props.installment&&<input type="hidden" name="installment" value={props.installment}/>}{props.operation==='correct_deduction'&&<label>التصحيح المُراجع ومسؤولية الموظف<Select name="correction_case" required defaultValue={restored.correction_case??props.correctionCase??''}><option value="">اختر المرجع المُراجع</option>{props.correctionChoices?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select></label>}</>}
 <label>سبب العملية<Textarea name="reason" minLength={3} maxLength={500} required defaultValue={restored.reason??props.reason??''}/></label>
 {props.operation==='correct_disbursement'&&<p>تؤكد أن دليل الصرف المسجل خاطئ، وأنه لم يحدث أي سداد أو خصم. تُحفظ حركة عكس مرتبطة بالأصل؛ لا يسجل هذا ردًا بنكيًا أو إعفاءً من دين حقيقي. المبلغ الصحيح يحتاج مسودة واعتمادًا ودليل صرف مستقلًا.</p>}{props.operation==='activate'&&<p>تؤكد أن المبلغ صُرف خارج النظام. هذه العملية تُنشئ مسؤولية السداد؛ لا تنفذ تحويلًا بنكيًا.</p>}{props.operation==='settle'&&<p>تؤكد استلام هذا السداد خارجيًا ومراجعة مرجعه. يوزّع على أقدم الأقساط دون إسقاط بقية الدين.</p>}{(props.operation==='compensate'||props.operation==='correct_deduction')&&<p>تصحيح سجل خاطئ يحفظ الأصل. لا يُعد ردًا بنكيًا أو إلغاءً لمبلغ دُفع فعليًا.</p>}
 <Button variant="solid" className={styles.primary} type="submit" disabled={offline} aria-describedby={showOfflineNotice?offlineHintId:undefined}>{pending?'جارٍ حفظ الطلب…':labels[props.operation]}</Button></fieldset>{showOfflineNotice&&<OfflineSubmissionNotice id={offlineHintId}/>} {message&&<Message tone="bad" role="alert">{message}</Message>}</form>;
}
