import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PageFrame} from '@/components/context-navigation';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import {uuid,displayDate} from '../rules';
import {money} from '../runs/rules';
import {AdvanceForm,AdvanceRecovery} from './AdvanceForm';
import {advanceError,statuses,eventNames,type Choice,type AdvanceWorkspace} from './rules';
import styles from '../payroll.module.css';
export const dynamic='force-dynamic';
type Query=Record<string,string|undefined>;
export default async function AdvancesPage({params,searchParams}:{params:Promise<{tenantId:string}>;searchParams:Promise<Query>}){
 const {tenantId}=await params,q=await searchParams;if(!uuid(tenantId))notFound();
 const path=`/tenant/${tenantId}/payroll/advances`,keep=Object.fromEntries(Object.entries(q).filter((x):x is [string,string]=>typeof x[1]==='string'));
 const href=(delta:Record<string,string>)=>`${path}?${new URLSearchParams({...keep,...delta})}`;
 let actorId:string|null=null;
 const failure=(text:string)=><PageFrame><section dir="rtl" className={styles.card}><h1>سلف الموظفين</h1><p role="alert">{text}</p>{actorId&&q.employer&&uuid(q.employer)&&<AdvanceRecovery actor={actorId} tenant={tenantId} employer={q.employer}/>}<Link href={href({})}>إعادة المحاولة بنفس السياق</Link></section></PageFrame>;
 for(const key of ['employer','advance','employment','period','after','employer_after','employee_after','period_after','history_before','correction_event','correction_case','correction_after','corrected_advance'])if(q[key]&&!uuid(q[key]!))return failure('راجع رابط الجهة والموظف والسلفة.');
 for(const key of ['q','employer_q','employee_q','period_q','correction_q'])if((q[key]?.length??0)>120)return failure('اختصر نص البحث ثم أعد المحاولة.');
 if(q.installment_after&&!/^\d{1,3}$/.test(q.installment_after))return failure('راجع صفحة الأقساط المطلوبة.');
 const client=await createSupabaseServerClient();if(!client)return failure('تعذر الاتصال بسجل السلف.');
 const {data:{user}}=await client.auth.getUser();if(!user)redirect(`/auth/login?next=${encodeURIComponent(href({}))}`);
 actorId=user.id;
 const employerResult=await client.rpc('payroll_advance_choices',{p_tenant:tenantId,p_employer:null,p_kind:'employers',p_query:q.employer_q??'',p_after:q.employer_after||null,p_selected:q.employer||null});
 if(employerResult.error)return failure(advanceError(employerResult.error.code,employerResult.error.message));
 const employers=employerResult.data as {items:Choice[];selected:Choice|null;next:string|null};
 if(!q.employer)return <PageFrame><div dir="rtl" className={styles.workspace}><section className={styles.card}><h1>سلف الموظفين</h1><p>اختر جهة العمل لعرض أصل السلفة والرصيد وجدول الأقساط.</p><form className={styles.filters} action={path}><label>البحث عن جهة<input name="employer_q" defaultValue={q.employer_q??''} maxLength={120}/></label><button>بحث</button></form>{employers.items.map(e=><p key={e.id}><Link href={href({employer:e.id,employer_after:'',advance:'',employment:'',period:''})}>{e.name}</Link></p>)}{employers.items.length===0&&<p>لا توجد جهة مطابقة. راجع البحث أو مسؤول الشركة.</p>}{employers.next&&<Link href={href({employer_after:employers.next})}>جهات إضافية</Link>}</section></div></PageFrame>;
 const response=await client.rpc('payroll_advance_workspace',{p_tenant:tenantId,p_employer:q.employer,p_advance:q.advance||null,p_query:q.q??'',p_after:q.after||null,p_installment_after:Number(q.installment_after??0),p_history_before:q.history_before||null});
 if(response.error||!response.data)return failure(advanceError(response.error?.code,response.error?.message));
 const w=response.data as AdvanceWorkspace,d=w.detail,scope={actor:user.id,tenant:tenantId,employer:q.employer};
 const creation=q.new==='1'&&!d;
 const needPeriods=creation||(d?.status==='draft')||(d?.status==='active');
 const periodResult=needPeriods?await client.rpc('payroll_advance_choices',{p_tenant:tenantId,p_employer:q.employer,p_kind:'periods',p_query:q.period_q??'',p_after:q.period_after||null,p_selected:q.period||d?.version.first_period||null}):null;
 const employeeResult=creation?await client.rpc('payroll_advance_choices',{p_tenant:tenantId,p_employer:q.employer,p_kind:'employments',p_query:q.employee_q??'',p_after:q.employee_after||null,p_selected:q.employment||null}):null;
 if(periodResult?.error||employeeResult?.error)return failure(advanceError(periodResult?.error?.code??employeeResult?.error?.code,periodResult?.error?.message??employeeResult?.error?.message));
 const periodData=periodResult?.data as {items:Choice[];selected:Choice|null;next:string|null}|undefined,employeeData=employeeResult?.data as {items:Choice[];selected:Choice|null;next:string|null}|undefined;
 const periods=[...(periodData?.selected&&!periodData.items.some(p=>p.id===periodData.selected!.id)?[periodData.selected]:[]),...(periodData?.items??[])];
 const correctionResult=d&&q.correction_event&&w.access.can_approve&&w.access.can_correct_payroll?await client.rpc('payroll_advance_correction_choices',{p_tenant:tenantId,p_employer:q.employer,p_advance:d.id,p_event:q.correction_event,p_query:q.correction_q??'',p_after:q.correction_after||null,p_selected:q.correction_case||null}):null;
 if(correctionResult?.error)return failure(advanceError(correctionResult.error.code,correctionResult.error.message));
 const correctionData=correctionResult?.data as {items:Choice[];selected:Choice|null;next:string|null;already_compensated?:boolean;event:{reference:string;amount:string;occurred_on:string}}|undefined;
 const corrections=[...(correctionData?.selected&&!correctionData.items.some(c=>c.id===correctionData.selected!.id)?[correctionData.selected]:[]),...(correctionData?.items??[])];
 const common=d?{...scope,advance:d.id,employment:d.employment_id,revision:d.revision,today:w.today,periods}:null;
 return <PageFrame><div dir="rtl" className={styles.workspace}>
 <header><h1>سلف الموظفين</h1><p>{w.employer.name}{d?` · ${d.name}`:''}</p><Link href={href({employer:'',advance:'',new:'',employment:'',period:''})}>تغيير جهة العمل</Link></header>
 <AdvanceRecovery {...scope}/>
 <nav className={styles.reviewNavigation} aria-label="أقسام السلف">{d&&common?<><a href="#payroll-advance-summary">الرصيد والخطوة التالية</a><a href="#payroll-advance-schedule">الأقساط</a><a href="#payroll-advance-history">الحركات والتصحيح</a></>:<><a href="#payroll-advance-list">السلف المحفوظة</a>{creation&&w.access.can_manage&&w.access.enabled&&<a href="#payroll-advance-create">السلفة الجديدة</a>}</>}</nav>
 {!w.access.enabled&&<section className={styles.card}><p>إنشاء السلف وتفعيل صرف جديد غير متاحين. يمكن للمسؤول المخول متابعة الأرصدة وتسوية الالتزامات القائمة.</p></section>}
 {d&&common?<>
 <section id="payroll-advance-summary" className={styles.card}><h2>{statuses[d.status]}</h2><dl className={styles.figureStrip}><div><dt>أصل السلفة</dt><dd><bdi>{money(d.version.principal)}</bdi></dd></div><div><dt>الرصيد المتبقي</dt><dd><bdi>{money(d.outstanding)}</bdi></dd></div></dl>
 {d.status==='active'&&d.next_installment&&<p>القسط التالي في {displayDate(d.next_installment.starts_on)} · <bdi>{money(d.next_installment.amount)}</bdi></p>}
 {d.status==='draft'&&w.access.can_approve&&w.access.enabled?<AdvanceForm {...common} operation="approve"/>:d.status==='approved'&&w.access.can_approve&&w.access.enabled?<AdvanceForm {...common} operation="activate"/>:d.status==='active'&&w.access.can_approve?<AdvanceForm {...common} operation="settle"/>:<p>{d.status==='settled'?'الرصيد صفري من الحركات المسجلة؛ الأصل والتاريخ محفوظان.':d.status==='record_corrected'?'عُكس دليل الصرف الخاطئ قبل أي سداد؛ لا يُعد تسوية لدين حقيقي.':d.status==='cancelled'?'لم تُفعّل مسؤولية صرف لهذا السجل.':'الخطوة التالية لدى مسؤول اعتماد تمويل الموظفين.'}</p>}
 </section>
 {d.status==='active'&&<section className={styles.card}><h2>مراجعة خصم الرواتب</h2><p>القسط المجدول ليس خصمًا منفذًا. يلزم أساس قانوني مؤهل للأولوية والحد المسموح قبل استهلاكه مع إقفال الرواتب؛ يبقى غير المطبق ضمن الرصيد.</p>{d.termination_on&&<p>انتهى التوظيف في {displayDate(d.termination_on)}. لا يعني ذلك إسقاط الدين؛ راجع أساس التسوية الخارجية مع المسؤول المخول.</p>}</section>}
 {d.status==='active'&&d.termination_on&&<section className={styles.card} aria-label="رصيد السلفة عند انتهاء التوظيف"><h2>مراجعة الرصيد عند انتهاء التوظيف</h2><p>الرصيد المتبقي <bdi>{money(d.outstanding)}</bdi>. توثيق المراجعة يحفظ المرجع ولا يسدد الدين. عند استلام سداد فعلي، استخدم تسجيل التسوية الخارجية أعلاه.</p>{w.access.can_approve?<AdvanceForm {...common} operation="termination"/>:<p>اطلب من مسؤول اعتماد تمويل الموظفين مراجعة الرصيد وتوثيق مسار تسويته.</p>}</section>}
 <details id="payroll-advance-schedule" className={styles.card}><summary>جدول الأقساط ومتابعة الترحيل</summary>{d.schedule.map(i=><article key={i.id}><h3>القسط {i.ordinal} · {displayDate(i.starts_on)} — {displayDate(i.ends_on)}</h3><p>المجدول <bdi>{money(i.amount)}</bdi> · غير المسدد <bdi>{money(i.remaining)}</bdi>{i.deferred?' · رُحّل بمراجعة محفوظة':''}</p>{d.status==='active'&&w.access.can_approve&&!/^0(?:\.0+)?$/.test(i.remaining)&&<details><summary>ترحيل القسط إلى فترة لاحقة</summary><p>يؤجل الاستحقاق دون تغيير أصل الدين أو اعتباره مسددًا.</p><AdvanceForm {...common} operation="defer" installment={i.id}/></details>}</article>)}{d.schedule.length===30&&<Link href={href({installment_after:String(d.schedule[29].ordinal)})}>الأقساط التالية</Link>}{q.installment_after&&<Link href={href({installment_after:''})}>بداية جدول الأقساط</Link>}</details>
 {correctionData&&q.correction_event&&<section className={styles.card}><h2>تعويض سجل خصم بعد تصحيح مُراجع</h2><p>{correctionData.event.reference} · {displayDate(correctionData.event.occurred_on)} · <bdi>{money(correctionData.event.amount)}</bdi></p><form className={styles.filters} action={path}>{Object.entries(keep).filter(([k])=>!['correction_q','correction_after'].includes(k)).map(([k,v])=><input key={k} type="hidden" name={k} value={v}/>)}<label>مرجع المراجعة أو سببها<input name="correction_q" defaultValue={q.correction_q??''} maxLength={120}/></label><button>بحث المراجعات</button></form>{correctionData.already_compensated?<p>لهذا الخصم حركة تصحيح محفوظة. إذا انقطع الرد السابق، تحقّق من المحاولة المحفوظة لاستعادة نتيجتها.</p>:corrections.length?<AdvanceForm {...common} operation="correct_deduction" original={q.correction_event} correctionChoices={corrections} correctionCase={q.correction_case}/>:<p>لا توجد مسؤولية خارجية مُراجعة تطابق الموظف والمخرج والمبلغ. اطلب من مسؤول تصحيح الرواتب استكمالها؛ لا تُستنتج من الأجر الإجمالي أو الصافي.</p>}{correctionData.next&&<Link href={href({correction_after:correctionData.next})}>مراجعات إضافية</Link>}<Link href={href({correction_event:'',correction_after:'',correction_case:'',correction_q:''})}>إغلاق اختيار التصحيح</Link></section>}
 <details id="payroll-advance-history" className={styles.card}><summary>الحركات ومرجع التصحيح</summary>{d.history.map(e=><article key={e.id}><h3>{eventNames[e.kind]??'حركة محفوظة'}</h3><p>{displayDate(e.occurred_on)} · <bdi>{money(e.delta)}</bdi> · {e.reference}</p><p>{e.reason}{e.compensated?' · لها حركة تصحيح محفوظة':''}</p>{e.output_id&&w.access.can_view_final&&<Link href={`/tenant/${tenantId}/payroll/output?${new URLSearchParams({employer:q.employer!,output:e.output_id})}`}>المخرج المرتبط</Link>}{!e.compensated&&e.kind==='disbursement'&&d.status==='active'&&w.access.can_manage&&w.access.can_approve&&<details><summary>تصحيح دليل صرف خاطئ قبل أي سداد</summary><AdvanceForm {...common} operation="correct_disbursement" original={e.id}/></details>}{!e.compensated&&e.kind==='settlement'&&w.access.can_approve&&<details><summary>تصحيح هذا السجل الخاطئ</summary><AdvanceForm {...common} operation="compensate" original={e.id}/></details>}{!e.compensated&&e.kind==='payroll_deduction'&&w.access.can_approve&&w.access.can_correct_payroll&&<details><summary>تعويض السجل بعد تصحيح رواتب مُراجع</summary><p>يحفظ الخصم الأصلي ويربط الحركة بقرار تصحيح ومسؤولية الموظف. لا يرد تحويلًا بنكيًا.</p><Link href={href({correction_event:e.id,correction_after:'',correction_case:''})}>اختيار التصحيح المُراجع لهذا السجل</Link></details>}</article>)}{d.history.length===20&&<Link href={href({history_before:d.history[19].id})}>حركات أقدم</Link>}{q.history_before&&<Link href={href({history_before:''})}>أحدث الحركات</Link>}</details>
 <details className={styles.card}><summary>خيارات أخرى</summary>{d.status==='record_corrected'&&w.access.can_manage&&w.access.enabled&&<Link href={href({advance:'',new:'1',employment:d.employment_id,corrected_advance:d.id})}>إعداد مبلغ صحيح مرتبط بالسجل الأصلي</Link>}{d.status==='draft'&&w.access.can_manage&&w.access.enabled&&<AdvanceForm {...common} operation="save" principal={d.version.principal} effectiveOn={d.version.effective_on} count={d.version.installment_count} firstPeriod={q.period??d.version.first_period} reason={d.version.reason}/>}{['draft','approved'].includes(d.status)&&w.access.can_manage&&<AdvanceForm {...common} operation="cancel"/>}</details>
 <Link href={href({advance:'',new:'',after:'',history_before:'',installment_after:''})}>العودة إلى قائمة السلف</Link>
 </>:<>
 <section id="payroll-advance-list" className={styles.card}><h2>السلف وأرصدة الموظفين</h2><form className={styles.filters} action={path}><input type="hidden" name="employer" value={q.employer}/><label>اسم الموظف أو رمزه<input name="q" defaultValue={q.q??''} maxLength={120}/></label><button>بحث</button></form><div className={styles.cardGrid}>{w.items.map(a=><article className={styles.card} key={a.id}><h3><Link href={href({advance:a.id,new:'',history_before:'',installment_after:''})}>{a.name} · <bdi>{a.code}</bdi></Link></h3><p>{statuses[a.status]} · أصل <bdi>{money(a.principal)}</bdi> · متبقٍ <bdi>{money(a.outstanding)}</bdi></p>{a.next_installment&&<p>القسط التالي {displayDate(a.next_installment.starts_on)} · <bdi>{money(a.next_installment.amount)}</bdi></p>}</article>)}</div>{w.items.length===0&&<p>لا توجد سلف مطابقة لهذا البحث.</p>}{w.next&&<Link href={href({after:w.next})}>سلف إضافية</Link>}{w.access.can_manage&&w.access.enabled&&!creation&&<Link href={href({new:'1',employment:'',period:''})}>إعداد سلفة جديدة</Link>}</section>
 {creation&&w.access.can_manage&&w.access.enabled&&<section id="payroll-advance-create" className={styles.card}><h2>إعداد سلفة جديدة</h2><form className={styles.filters} action={path}><input type="hidden" name="employer" value={q.employer}/><input type="hidden" name="new" value="1"/>{q.corrected_advance&&<input type="hidden" name="corrected_advance" value={q.corrected_advance}/> }{q.period&&<input type="hidden" name="period" value={q.period}/>}<label>البحث عن الموظف<input name="employee_q" defaultValue={q.employee_q??''} maxLength={120}/></label><button>بحث</button></form>{employeeData?.selected&&<p>الموظف المختار: {employeeData.selected.name} · <bdi>{employeeData.selected.code}</bdi></p>}{employeeData?.items.map(e=><p key={e.id}><Link href={href({employment:e.id})}>{e.name} · <bdi>{e.code}</bdi></Link></p>)}{employeeData?.next&&<Link href={href({employee_after:employeeData.next})}>موظفون إضافيون</Link>}{employeeData?.selected&&<AdvanceForm {...scope} operation="save" advance={crypto.randomUUID()} employment={employeeData.selected.id} revision={0} today={w.today} correctedAdvance={q.corrected_advance} periods={periods} firstPeriod={q.period}/>}</section>}
 </>}
 {needPeriods&&<details className={styles.card}><summary>البحث عن فترة خارج الاختيارات الحالية</summary><form className={styles.filters} action={path}>{Object.entries(keep).filter(([k])=>!['period_q','period_after'].includes(k)).map(([k,v])=><input key={k} type="hidden" name={k} value={v}/>)}<label>اسم الفترة أو تاريخ بدايتها<input name="period_q" defaultValue={q.period_q??''} maxLength={120}/></label><button>بحث الفترات</button></form>{periodData?.items.map(p=><p key={p.id}><Link href={href({period:p.id})}>{p.name} · {displayDate(p.starts_on??'')}</Link></p>)}{periodData?.next&&<Link href={href({period_after:periodData.next})}>فترات إضافية</Link>}<p>إذا كانت الفترات المستقبلية ناقصة، اطلب من مدير إعداد الرواتب توليدها أولًا.</p></details>}
 {w.access.can_review_payroll?<Link href={`/tenant/${tenantId}/payroll?${new URLSearchParams({employer:q.employer,period:q.period??''})}`}>الرواتب</Link>:<p>استكمال أساس خصم القسط لدى مسؤول الرواتب والامتثال. يمكنك متابعة الرصيد والتسوية من هذه الصفحة.</p>}
 </div></PageFrame>;
}
