'use client';
import { Button, Input, Message, Panel, Select, Textarea, Checkbox } from '@/components/ui';
import {useEffect,useId,useState} from 'react';
import {OfflineSubmissionNotice,useOfflineSubmission} from '@/components/offline-submission';
import {useRouter} from 'next/navigation';
import {usePaymentRecovery} from './usePaymentRecovery';
import {money} from '../runs/rules';
import type {PaymentEmployee} from './rules';
import styles from '../payroll.module.css';
type Props={actor:string;recoveryOnly?:boolean;tenant:string;employer:string;output:string;revision:number;today:string;employees:PaymentEmployee[];remaining:string;remainingCount:number;original?:string;originalAmount?:string;recoveryAttempt?:string};
export function PaymentForm(p:Props){
 const {offline,blockOfflineSubmission}=useOfflineSubmission(),offlineHintId=useId();
 const router=useRouter();
 const {state,action,pending,unresolved}=usePaymentRecovery(p);
 const [mode,setMode]=useState('allocations'),[date,setDate]=useState(p.today),[reference,setReference]=useState(''),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[selected,setSelected]=useState<string[]>([]),[amounts,setAmounts]=useState<Record<string,string>>({}),[another,setAnother]=useState(false);
 useEffect(()=>{if(state.saved||state.cancelled)router.refresh();},[state.saved,state.cancelled,router]);
 const [selectedRows,setSelectedRows]=useState<Record<string,PaymentEmployee>>({});
 const choices=[...p.employees,...selected.filter(id=>!p.employees.some(e=>e.employment_id===id)).map(id=>selectedRows[id]).filter(Boolean)];
 const correction=!!p.original;
 const showOfflineNotice=offline&&!pending&&(correction||mode!=='allocations'||selected.length>0);
 if(p.recoveryOnly)return unresolved?<Panel className={styles.card}><h2>استعادة نتيجة تسجيل الدفعة</h2><p>تحقّق من الطلب السابق قبل تسجيل دفعة أخرى. سيستخدم النظام نفس القيم وهوية الطلب، حتى لو ظهر الدفع في السجل.</p><form action={action} onSubmit={event=>{blockOfflineSubmission(event);}} className={styles.actions}><Button variant="solid" type="submit" className={` ${styles.primary}`} name="__recover" value="yes" disabled={pending||offline} aria-describedby={offline&&!pending?offlineHintId:undefined}>{pending?'جارٍ التحقق…':'استعادة نتيجة الدفعة الأصلية'}</Button><Button variant="ghost" type="submit" name="__cancel" value="yes"  disabled={pending||offline} aria-describedby={offline&&!pending?offlineHintId:undefined}>إلغاء الطلب إذا لم يُسجّل</Button>{offline&&!pending&&<OfflineSubmissionNotice id={offlineHintId} purpose="recovery"/>}</form>{state.error&&<Message tone="bad" role="alert">{state.error}</Message>}</Panel>:state.cancelled?<Message tone="info" role="status">أُلغي الطلب غير المسجل. يمكنك تسجيل طلب جديد.</Message>:state.saved?<Message tone="info" role="status">تأكد تسجيل الطلب الأصلي. المبلغ {money(state.amount)} · المتبقي {money(state.remaining)}</Message>:state.error?<Message tone="bad" role="alert">{state.error}</Message>:null;
 if(unresolved)return null;
 if(state.saved&&!another&&!pending)return <Message tone="info" as="div" role="status"><p>{correction?'حُفظ تصحيح القيد الخاطئ دون حذف الدفعة الأصلية.':'حُفظ تسجيل الدفعة الخارجية.'} المبلغ {money(state.amount)} · المتبقي {money(state.remaining)}</p>{!correction&&<Button variant="ghost" type="button"  onClick={()=>{setAnother(true);setReference('');setReason('');setConfirmed(false);setSelected([]);setAmounts({});}}>تسجيل دفعة أخرى</Button>}</Message>;
 return <form action={action} onSubmit={event=>{if(blockOfflineSubmission(event))return;setAnother(false);}} onReset={e=>e.preventDefault()} className={styles.form}>
 <input type="hidden" name="tenant" value={p.tenant}/><input type="hidden" name="employer" value={p.employer}/><input type="hidden" name="output" value={p.output}/><input type="hidden" name="original" value={p.original??''}/><input type="hidden" name="revision" value={Math.max(p.revision,state.revision)}/>
 <fieldset disabled={pending} className={styles.paymentFields}><legend>{correction?'تصحيح قيد خاطئ فقط':'تسجيل دفعة تم صرفها خارج النظام'}</legend>
 {correction?<><input type="hidden" name="operation" value="compensate"/><p>سيُعكس كامل هذا القيد ({money(p.originalAmount)}) مع الاحتفاظ به في السجل. هذا الإجراء لا يسترد مالًا من الموظف أو البنك.</p></>:<><label>نطاق الدفعة<Select name="operation" value={mode} onChange={e=>setMode(e.target.value)}><option value="allocations">مبالغ محددة لموظفين</option><option value="remaining">كامل المتبقي لهذا المسير</option></Select></label>{mode==='remaining'?<p>تُسجّل {money(p.remaining)} لكامل المتبقي لدى {p.remainingCount} موظفًا. راجع أن هذا المبلغ صُرف بالفعل.</p>:<><p>اختر من الموظفين المعروضين وحدد مبلغ كل موظف. لا يُوزّع مبلغ إجمالي تلقائيًا.</p>{choices.filter(e=>selected.includes(e.employment_id)||!/^0(?:\.0*)?$/.test(e.remaining)).map(e=><div className={styles.paymentChoice} key={e.employment_id}><label><Checkbox  name="employee" value={e.employment_id} checked={selected.includes(e.employment_id)} onChange={event=>{setSelectedRows(rows=>({...rows,[e.employment_id]:e}));setSelected(list=>event.target.checked?[...list,e.employment_id]:list.filter(id=>id!==e.employment_id));}}/>{e.employee_snapshot.name} · المتبقي {money(e.remaining)}</label>{selected.includes(e.employment_id)&&<label>المبلغ<Input name={`amount:${e.employment_id}`} inputMode="decimal" pattern="[0-9]{1,16}(\.[0-9]{1,2})?" required value={amounts[e.employment_id]??''} onChange={event=>setAmounts(values=>({...values,[e.employment_id]:event.target.value}))}/></label>}</div>)}</>}</>}
 <div className={styles.recordFields}><h3>المرجع والتاريخ</h3><label>{correction?'تاريخ تصحيح القيد':'تاريخ الصرف الفعلي'}<Input name="date" type="date" required max={p.today} value={date} onChange={e=>setDate(e.target.value)}/></label>
 <label>مرجع القيد<Input name="reference" minLength={3} maxLength={160} required value={reference} onChange={e=>setReference(e.target.value)}/></label>
 <label>{correction?'سبب خطأ القيد':'بيان الدفعة'}<Textarea name="reason" required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 </div><label className={styles.confirmation}><Checkbox name="confirmed"  value="yes" required checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>{correction?'أؤكد أن هذا تصحيح لقيد خاطئ فقط، وليس استردادًا لمال صُرف.':'أؤكد أن هذه المبالغ صُرفت خارج النظام وأن المرجع يخص هذه الدفعة.'}</label>
 <Button variant={correction ? "ghost" : "solid"} type="submit"  disabled={pending||offline||(!correction&&mode==='allocations'&&!selected.length)} aria-describedby={showOfflineNotice?offlineHintId:undefined}>{pending?'جارٍ التحقق والحفظ…':state.recoverPending?'التحقق من نتيجة نفس الطلب':correction?'حفظ تصحيح القيد':'تسجيل الدفعة الخارجية'}</Button></fieldset>{showOfflineNotice&&<OfflineSubmissionNotice id={offlineHintId} purpose={state.recoverPending?'recovery':'submission'}/>} {state.error&&<Message tone="bad" as="div" role="alert"><p>{state.error}</p>{state.needsRefresh&&<Button variant="ghost" type="button" disabled={pending}  onClick={()=>router.refresh()}>تحديث المطابقة مع الاحتفاظ بالحقول</Button>}</Message>}
 </form>;
}
