'use client';

import { useState } from 'react';
import { ThemePreferenceControl } from '@/components/theme-preference';
import { Panel, RecordCard, Message, DataTable, Checkbox, Radio, FileInput, Avatar, Badge, Banner, Button, Card, DateInput, Disclosure, EmptyState, FactList, Field, IconButton, Input, KeyValueStrip, PageHeader, SegmentedControl, Select, Sheet, Skeleton, StatusBadge, Textarea, TimeInput, Toast, type Tone } from '@/components/ui';

const tones: Tone[] = ['neutral', 'ok', 'warn', 'bad', 'info', 'brand'];
export function Gallery() {
  const [segment, setSegment] = useState('all');
  const [toast, setToast] = useState(false);
  return <main className="ui-gallery"><PageHeader title="مكتبة الواجهة" description="معرض تطوير للمكونات وحالاتها؛ لا يحتوي بيانات تشغيل." action={<ThemePreferenceControl />} /><div className="ui-gallery-grid">
    <Card><h2>الإجراءات</h2><div className="ui-gallery-stack"><div className="ui-gallery-row"><Button icon="plus">إجراء أساسي</Button><Button variant="ghost">إجراء ثانوي</Button><Button variant="danger">حذف</Button></div><div className="ui-gallery-row"><Button size="lg">إجراء كبير</Button><Button disabled>غير متاح</Button><Button pending pendingLabel="جارٍ الحفظ…">حفظ</Button><IconButton icon="search" aria-label="بحث" /></div></div></Card>
    <Card><h2>الحقول</h2><div className="ui-gallery-stack"><Field id="gallery-name" label="الاسم" hint="اكتب الاسم كما سيظهر في القائمة."><Input id="gallery-name" aria-describedby="gallery-name-hint" placeholder="اسم العرض" /></Field><Field id="gallery-error" label="رمز" error="أدخل رمزًا صحيحًا."><Input id="gallery-error" error aria-describedby="gallery-error-error" defaultValue="?" /></Field><Field id="gallery-disabled" label="حقل قراءة"><Input id="gallery-disabled" disabled defaultValue="قراءة فقط" /></Field><Field id="gallery-select" label="الخيار"><Select id="gallery-select"><option>اختر</option><option>الخيار الأول</option></Select></Field><Field id="gallery-note" label="ملاحظة"><Textarea id="gallery-note" /></Field><Field id="gallery-date" label="التاريخ"><DateInput id="gallery-date" /></Field><Field id="gallery-time" label="الوقت"><TimeInput id="gallery-time" /></Field></div></Card>
    <Card><h2>الحالات والهوية</h2><div className="ui-gallery-stack"><div className="ui-gallery-row">{tones.map(tone => <Badge key={tone} tone={tone}>{tone}</Badge>)}</div><StatusBadge label="بانتظار المراجعة" tone="warn" /><div className="ui-gallery-row">{tones.map(tone => <Avatar key={tone} name="مستخدم تجريبي" size={48} status={tone} />)}</div><SegmentedControl label="فلتر المعرض" value={segment} onChange={setSegment} options={[{value:'all',label:'الكل'},{value:'pending',label:'المعلق',count:3},{value:'done',label:'المكتمل'},{value:'disabled',label:'معطل',disabled:true}]} /></div></Card>
    <Card><h2>التنبيهات</h2><div className="ui-gallery-stack">{tones.filter(t => t !== 'neutral' && t !== 'brand').map(tone => <Banner key={tone} tone={tone} title="عنوان تنبيه">رسالة قصيرة توضح الحالة والخطوة التالية.</Banner>)}<Button variant="ghost" onClick={() => setToast(true)}>عرض إشعار</Button></div></Card>
    <Card><h2>التفاصيل</h2><div className="ui-gallery-stack"><KeyValueStrip items={[{label:'عدد العناصر',value:'12'},{label:'المبلغ',value:'1,250',money:true}]} /><FactList items={[{text:'معلومة واضحة قبل إكمال الإجراء',tone:'ok'},{text:'تحقق من التفاصيل قبل التأكيد',tone:'warn'}]} /><Disclosure summary="تفاصيل إضافية">يظهر الشرح الإضافي عند الحاجة دون ازدحام الصفحة.</Disclosure><Sheet title="تفاصيل الإجراء" description="ورقة جانبية على الحاسوب وسفلية على الهاتف." trigger={<Button variant="ghost">فتح التفاصيل</Button>}><div className="ui-gallery-stack"><Banner>محتوى توضيحي للمعرض.</Banner><Button>متابعة</Button></div></Sheet></div></Card>
    <Panel><h2>مكونات صفحات العمل</h2><div className="ui-gallery-stack"><Message tone="info">حالة العملية وخطوتها التالية.</Message><ul className="record-list"><RecordCard>عنصر سجل تجريبي للمعرض</RecordCard></ul><label className="ui-check"><Checkbox />اختيار عنصر</label><label className="ui-check"><Radio name="gallery-choice" />خيار واحد</label><Field id="gallery-file" label="ملف"><FileInput /></Field><DataTable><caption>جدول المعرض</caption><thead><tr><th scope="col">العنصر</th><th scope="col">الحالة</th></tr></thead><tbody><tr><td>معاينة</td><td>متاح</td></tr></tbody></DataTable></div></Panel><Card><h2>فارغ وتحميل</h2><EmptyState title="لا توجد عناصر" description="ابدأ بإضافة أول عنصر عندما تكون مستعدًا." action={<Button icon="plus">إضافة عنصر</Button>} /><div className="ui-gallery-stack"><Skeleton /><Skeleton /><Skeleton style={{width:'45%'}} /></div></Card>
  </div>{toast && <Toast message="تم حفظ التغيير" onDismiss={() => setToast(false)} />}</main>;
}

