'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {PagedChoice,type ChoiceScope} from './PagedChoice';
import {useCorrectionRecovery} from './useCorrectionRecovery';
import {type CorrectionKind} from './rules';
import {inputOptions,inputFields,openingCoverageFields,type InputKind} from '../inputs/rules';
import {displayDate} from '../rules';
import styles from '../payroll.module.css';
type Choice={id:string;name:string;employer_id?:string};
type ObservationChoice={id:string;name:string;expected_hash:string;fresh?:boolean;affects_paid_output?:boolean};
type ResponsibilityRow={employment:string;output:string;basis:string;amount:string;component:string;reference:string;source:string;target:string};
type Props={initialProposal?:{fields:Record<string,unknown>;unchangedChanges?:Record<string,unknown>[];split:boolean;reason:string;reference:string;target:string;rows:ResponsibilityRow[]};initialObservationProposal?:{observations:ObservationChoice[];reason:string;reference:string;target:string;rows:ResponsibilityRow[]};actor:string;tenant:string;employer:string;output:string;employee?:string;caseId?:string;revision:number;kind:CorrectionKind;source?:{id:string;expected_hash:string;kind?:InputKind;name?:string;fresh?:boolean;affects_paid_output?:boolean;fields?:Record<string,unknown>};observations?:ObservationChoice[];employees:Choice[];sites:Choice[];references:Record<string,(Choice&{version?:number})[]>;outputs:{id:string;employer?:string;starts_on:string;ends_on:string}[];periods:{id:string;employer_id?:string;starts_on:string;ends_on:string}[];components:(Choice&{classification:string})[];everPaid:boolean};
const labels:Record<string,string>={tax_net_income:'الدخل الخاضع بعد الخصومات القانونية (إن كان معلومًا)',coverage_start:'بداية الفترة السابقة',coverage_end:'نهاية الفترة السابقة',tax_duration_days:'مدة الاحتساب الضريبي السابقة بالأيام وفق المرجع',tax_treatment_code:'رمز المعاملة الضريبية من المرجع',insurance_status:'حالة التأمينات',insurance_category:'الفئة التأمينية من المرجع',insured_wage:'الأجر المؤمن عليه بالجنيه',insurance_from:'تاريخ بدء الاشتراك',insurance_until:'تاريخ انتهاء الاشتراك (اختياري)',amount:'الأجر',valid_from:'يسري من',valid_until:'ينتهي قبل',start_date:'تاريخ بدء التوظيف',end_date:'آخر يوم توظيف',pay_basis:'أساس الأجر',payroll_eligible:'يدخل في الرواتب',site_id:'الموقع',department_id:'القسم',job_id:'الوظيفة',manager_employee_id:'المدير',work_policy_template_id:'سياسة العمل',work_policy_version:'نسخة السياسة',employee_id:'الموظف المسجل',employee_code:'رمز الموظف الجديد',full_name:'اسم الموظف الجديد',effective_from:'يسري من',effective_until:'ينتهي قبل',cancelled:'إلغاء المدخل',value:'القيمة',reason:'السبب',reference:'المرجع',component_id:'المكوّن',name:'اسم المكوّن',classification:'نوع المكوّن',calculation:'طريقة القيمة',base:'أساس النسبة',behavior:'الاستخدام',taxable:'معالجة الضريبة',social:'معالجة التأمينات',visible:'يظهر للموظف',active:'نشط',proration:'احتساب جزء الفترة',order:'ترتيب العرض',key:'رمز المكوّن',mode:'طريقة احتساب جزء الفترة',units:'الوحدات',year:'السنة',taxable_earnings:'الأجر الخاضع التراكمي',tax_withheld:'الضريبة المحجوزة',tax_due:'الضريبة المستحقة سابقًا (إن كانت معلومة)',social_base:'الوعاء التأميني',employee_social:'حصة الموظف',employer_social:'حصة صاحب العمل'};
const enums:Record<string,string[]>={pay_basis:['monthly','daily'],payroll_eligible:['true','false'],cancelled:['false','true'],classification:['earning','deduction','employer_cost'],calculation:['fixed','percentage'],base:inputOptions.base.map(x=>x[0]),behavior:['recurring','period_input'],taxable:['true','false'],social:['true','false'],visible:['true','false'],active:['true','false'],proration:['salary_proration','paid_full_period'],mode:inputOptions.mode.map(x=>x[0])};
const values:Record<string,string>={monthly:'شهري',daily:'يومي',true:'نعم',false:'لا',earning:'استحقاق',deduction:'خصم',employer_cost:'تكلفة صاحب العمل',fixed:'مبلغ ثابت',percentage:'نسبة من الأجر المكتسب',base_pay:'الأجر الأساسي', '':'لا ينطبق للقيمة الثابتة',recurring:'متكرر',period_input:'مدخل للفترة',salary_proration:'مثل سياسة الأجر الشهري',paid_full_period:'كامل القيمة للفترة',calendar_days:'أيام الفترة الفعلية',fixed_30_day:'أساس 30 يومًا'};
export function ProposalForm(p:Props){
 const router=useRouter();
 const saved=p.initialProposal??p.initialObservationProposal;
 const defaults={...(p.kind==='new_employment'?{employee_code:'',full_name:'',start_date:'',end_date:'',pay_basis:'monthly',payroll_eligible:'true',amount:'',site_id:''}:p.source?.fields??{}),...p.initialProposal?.fields};
 const [fields,setFields]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(defaults).filter(([k])=>k!=='data').map(([k,v])=>[k,v==null?'':String(v)])));
 const [data,setData]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(defaults.data as Record<string,unknown>??{}).map(([k,v])=>[k,v==null?'':String(v)])));
 const [observations,setObservations]=useState<ObservationChoice[]>(()=>p.initialObservationProposal?.observations??(p.kind==='source_change'&&p.source?[{id:p.source.id,name:p.source.name??'التغيير المسجل',expected_hash:p.source.expected_hash,fresh:p.source.fresh,affects_paid_output:p.source.affects_paid_output}]:[]));
 const selectedObservations=observations.map(item=>{const current=item.id===p.source?.id?p.source:p.observations?.find(x=>x.id===item.id);return {...item,fresh:current?.fresh??item.fresh,affects_paid_output:current?.affects_paid_output??item.affects_paid_output};});
 const needsSettlement=p.everPaid||selectedObservations.some(x=>x.affects_paid_output);
 const staleObservation=p.kind==='source_change'&&selectedObservations.some(x=>x.fresh===false);
 const [split,setSplit]=useState(p.initialProposal?.split??false),[existing,setExisting]=useState(Boolean(p.initialProposal?.fields.employee_id));
 const [reason,setReason]=useState(saved?.reason??''),[reference,setReference]=useState(saved?.reference??''),[target,setTarget]=useState(saved?.target??'');
 const [unchangedChanges,setUnchangedChanges]=useState(p.initialProposal?.unchangedChanges??[]);
 const [rows,setRows]=useState<ResponsibilityRow[]>(saved?.rows??[]);
 const recovery=useCorrectionRecovery(p,'proposal',saved=>{const list=(key:string)=>saved.getAll(key).map(String);const get=(key:string)=>String(saved.get(key)??'');setFields(Object.fromEntries(JSON.parse(get('field_keys')).map((key:string)=>[key,get('field:'+key)])));setData(Object.fromEntries(JSON.parse(get('data_keys')).map((key:string)=>[key,get('data:'+key)])));if(get('kind')==='source_change'&&get('source_changes'))setObservations(JSON.parse(get('source_changes')));setSplit(get('kind').endsWith('_split'));setExisting(Boolean(get('field:employee_id')));setUnchangedChanges(JSON.parse(get('unchanged_changes')||'[]'));setReason(get('reason'));setReference(get('reference'));setTarget(get('target'));setRows(list('row_employment').map((employment,i)=>({employment,output:list('row_output')[i]??'',basis:list('row_basis')[i]??'',amount:list('row_amount')[i]??'',component:list('row_component')[i]??'',reference:list('row_reference')[i]??'',source:list('row_source')[i]??'',target:list('row_target')[i]??''})));});
 const {state,action,pending}=recovery;
 const keys=p.kind==='source_change'?[]:Object.keys(fields).filter(k=>p.kind!=='new_employment'||(existing?!['employee_code','full_name'].includes(k):k!=='employee_id')).filter(k=>!split||!['valid_from','valid_until'].includes(k));
 if(split&&!keys.includes('effective_from'))keys.push('effective_from');if(existing&&!keys.includes('employee_id'))keys.push('employee_id');
 const dataKeys=p.source?.kind?inputFields[p.source.kind].filter(key=>p.source?.kind!=='statutory_context'||data.insurance_status==='insured'||!['insurance_category','insured_wage','insurance_from','insurance_until'].includes(key)):[];
 const choiceScope:ChoiceScope={tenant:p.tenant,employer:p.employer,output:p.output,kind:p.kind,employee:p.employee};
 const field=(key:string,current:string,name:string,onChange:(value:string)=>void)=>{
  const options=key==='site_id'?p.sites:key==='component_id'?p.components:(key==='employee_id'?p.references.employee_id:p.references[key])??null;
  if(options)return <PagedChoice scope={choiceScope} choice={key==='component_id'?'components':key} name={name} value={current} onChange={value=>{onChange(value);if(key==='work_policy_template_id'&&!value)setFields(f=>({...f,work_policy_version:''}));}} initial={options} required={key==='site_id'||key==='component_id'} placeholder={labels[key]} version={key==='work_policy_template_id'?Number(fields.work_policy_version||0):undefined} onItem={key==='work_policy_template_id'?item=>setFields(f=>({...f,work_policy_template_id:item.id,work_policy_version:String(item.version??'')})):undefined}/>;
  if(key==='work_policy_version')return <><input type="hidden" name={name} value={current}/><span>نسخة {current||'غير محددة'}</span></>;
  if(inputOptions[key])return <select name={name} value={current} onChange={e=>onChange(e.target.value)}>{inputOptions[key].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>;
  if(enums[key])return <select name={name} value={current} onChange={e=>onChange(e.target.value)}>{enums[key].map(x=><option key={x} value={x}>{values[x]??x}</option>)}</select>;
  return <input name={name} value={current} type={/date|_from|_until|coverage_start|coverage_end/.test(key)?'date':'text'} inputMode={['amount','value','units','tax_duration_days','taxable_earnings','tax_withheld','tax_due','tax_net_income','insured_wage','social_base','employee_social','employer_social'].includes(key)?'decimal':undefined} onChange={e=>onChange(e.target.value)} required={openingCoverageFields.includes(key)?openingCoverageFields.some(k=>Boolean(data[k])):!['end_date','valid_until','effective_until','tax_due','tax_net_income','insurance_until'].includes(key)} maxLength={500}/>;
 };
 if(state.saved)return <div role="status"><p>حُفظ المقترح دون تغيير المصدر أو الراتب الأصلي.</p><Link href={`/tenant/${p.tenant}/payroll/corrections?${new URLSearchParams({employer:p.employer,output:p.output,case:state.caseId??'',kind:p.kind})}`}>مراجعة المقترح المحفوظ</Link></div>;
 return <form action={action} onChange={recovery.invalidatePreview} onReset={e=>e.preventDefault()} className={styles.form}>
 <input type="hidden" name="tenant" value={p.tenant}/><input type="hidden" name="employer" value={p.employer}/><input type="hidden" name="output" value={p.output}/><input type="hidden" name="case" value={p.caseId??''}/><input type="hidden" name="revision" value={p.revision}/><input type="hidden" name="kind" value={split?`${p.kind}_split`:p.kind}/><input type="hidden" name="source" value={p.source?.id??''}/><input type="hidden" name="source_hash" value={p.source?.expected_hash??''}/><input type="hidden" name="source_changes" value={JSON.stringify(selectedObservations)}/><input type="hidden" name="unchanged_changes" value={JSON.stringify(unchangedChanges)}/><input type="hidden" name="field_keys" value={JSON.stringify(keys)}/><input type="hidden" name="data_keys" value={JSON.stringify(dataKeys)}/>
 <fieldset disabled={pending||recovery.unresolved} className={styles.paymentFields}><legend>التغيير المقترح</legend>
 {p.kind==='source_change'&&<><p>اختر التغييرات المسجلة التي تريد مراجعة أثرها معًا.</p><ul>{observations.map(item=><li key={item.id}>{item.name} <button type="button" className="secondary-button" onClick={()=>{setObservations(list=>list.filter(x=>x.id!==item.id));recovery.invalidatePreview();}}>إزالة هذا التغيير</button></li>)}</ul><label>إضافة تغيير مسجل<PagedChoice scope={choiceScope} choice="sources" value="" onChange={()=>{}} onItem={item=>{if(typeof item.expected_hash!=='string'||observations.length>=32)return;setObservations(list=>list.some(x=>x.id===item.id)?list:[...list,{id:item.id,name:item.name,expected_hash:item.expected_hash as string,fresh:item.fresh as boolean|undefined,affects_paid_output:item.affects_paid_output as boolean|undefined}]);recovery.invalidatePreview();}} initial={p.observations} placeholder="اختر تغييرًا آخر للمراجعة"/></label>{observations.length===0&&<p>اختر تغييرًا واحدًا على الأقل قبل المعاينة.</p>}</>}
 {['compensation','assignment'].includes(p.kind)&&<label>نطاق التصحيح<select value={split?'dated':'whole'} onChange={e=>setSplit(e.target.value==='dated')}><option value="whole">تصحيح النسخة كاملة</option><option value="dated">تغيير يبدأ داخل النسخة مع حفظ ما قبله</option></select></label>}{p.kind==='new_employment'&&<label>هوية الموظف<select value={existing?'existing':'new'} onChange={e=>setExisting(e.target.value==='existing')}><option value="new">موظف جديد غير مسجل</option><option value="existing">موظف مسجل وتوظيفه غير مسجل</option></select></label>}
 {keys.map(key=><label key={key}>{labels[key]??key}{field(key,fields[key]??'',`field:${key}`,v=>setFields(f=>({...f,[key]:v})))}</label>)}
 {dataKeys.map(key=><label key={key}>{labels[key]??key}{field(key,data[key]??'',`data:${key}`,v=>setData(f=>({...f,[key]:v})))}</label>)}
 <label>مرجع التصحيح<input name="reference" required minLength={3} maxLength={160} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>سبب التصحيح<textarea name="reason" required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label>
 {needsSettlement&&<><h3>مسؤولية التسوية المقترحة</h3><p>أدخل أساسًا يدويًا واضحًا للمراجعة، لا فرق صافي مستنتجًا من الأجر. الموجب مستحق إضافي للموظف والسالب مسؤولية استرداد. الخصم اللاحق يحتاج التأهيل القانوني ولا يُعد مسددًا عند إنشاء المدخل.</p><label>فترة المدخل اللاحق<PagedChoice scope={choiceScope} choice="periods" name="target" value={target} onChange={setTarget} initial={p.periods.map(x=>({...x,name:displayDate(x.starts_on)+' — '+displayDate(x.ends_on)}))} placeholder="فترة المدخل اللاحق (اختياري)"/></label>
 {rows.map((r,index)=><fieldset key={index}><legend>المسؤولية {index+1}</legend><label>الموظف<PagedChoice scope={choiceScope} choice="employees" name="row_employment" value={r.employment} required onChange={value=>setRows(list=>list.map((x,i)=>i===index?{...x,employment:value}:x))} initial={[...p.employees,...(p.kind==='new_employment'?[{id:'new:0',name:'الموظف في التوظيف المقترح'}]:[])]} placeholder="الموظف المسؤول"/></label><label>المسير المتأثر<PagedChoice scope={choiceScope} choice="outputs" name="row_output" value={r.output} onChange={value=>setRows(list=>list.map((x,i)=>i===index?{...x,output:value}:x))} initial={p.outputs.map(x=>({...x,name:(x.employer??'')+' · '+displayDate(x.starts_on)+' — '+displayDate(x.ends_on)}))} placeholder="المسير المتأثر"/></label>
 <label>مسار التسوية<select name="row_basis" value={r.basis} onChange={e=>setRows(list=>list.map((x,i)=>i===index?{...x,basis:e.target.value}:x))}><option value="external_reviewed">تسوية خارجية مستقلة معتمدة</option><option value="period_component">مكوّن لفترة لاحقة</option></select></label>
 {['amount','reference','source'].map(key=><label key={key}>{key==='amount'?'مبلغ المسؤولية مع الإشارة':key==='source'?'أساس المبلغ ومصدره':'مرجع المسؤولية'}<input name={`row_${key}`} value={r[key as 'amount'|'reference'|'source']} required minLength={key==='amount'?1:3} maxLength={500} onChange={e=>setRows(list=>list.map((x,i)=>i===index?{...x,[key]:e.target.value}:x))}/></label>)}
 {r.basis==='period_component'&&<label>الفترة المستهدفة لهذا الموظف<PagedChoice scope={choiceScope} choice="periods" name="row_target" value={r.target} onChange={value=>setRows(list=>list.map((x,i)=>i===index?{...x,target:value}:x))} initial={p.periods.map(x=>({...x,name:displayDate(x.starts_on)+' — '+displayDate(x.ends_on)}))} placeholder="الفترة المستهدفة لهذا الموظف"/></label>}{r.basis!=='period_component'&&<input type="hidden" name="row_target" value=""/>}
 {r.basis==='period_component'?<label>مكوّن الفترة<PagedChoice scope={choiceScope} choice="components" name="row_component" value={r.component} required onChange={value=>setRows(list=>list.map((x,i)=>i===index?{...x,component:value}:x))} initial={p.components} placeholder="مكوّن الفترة"/></label>:<input type="hidden" name="row_component" value=""/>}<button type="button" className="secondary-button" onClick={()=>setRows(list=>list.filter((_,i)=>i!==index))}>إزالة هذه المسؤولية من المقترح</button></fieldset>)}
 <button type="button" className="secondary-button" disabled={rows.length>=100} onClick={()=>setRows(list=>[...list,{employment:'',output:p.output,basis:'external_reviewed',amount:'',component:'',reference:'',source:'',target:''}])}>إضافة مسؤولية لموظف</button></>}
 <button name="operation" value="preview" disabled={staleObservation||(p.kind==='source_change'&&observations.length===0)}>{pending?'جارٍ التحقق…':'معاينة نطاق التصحيح'}</button>{state.previewHash&&recovery.previewValid&&!pending&&!recovery.unresolved&&<><p>تؤثر المعاينة في {state.affected?.length??0} مسير. راجع القيم؛ تغييرها يحتاج معاينة جديدة.</p><button name="operation" value="save" disabled={staleObservation}>حفظ المقترح للمراجعة</button></>}
 </fieldset><RecoveryNotice recovery={recovery}/>{staleObservation&&<p role="alert">تغيّرت البيانات مرة أخرى. <button type="button" className="secondary-button" onClick={()=>router.refresh()}>تحديث التغييرات مع الاحتفاظ بالحقول</button></p>}{state.error&&<div role="alert"><p>{state.error}</p><button type="button" className="secondary-button" disabled={pending||state.recoverPending} onClick={()=>router.refresh()}>تحديث المصدر مع الاحتفاظ بالحقول</button></div>}
 </form>;
}
export function CorrectionCommand(p:{actor:string;tenant:string;employer:string;output:string;kind?:CorrectionKind;caseId:string;revision:number;operation:string;label:string;period?:string;run?:string;candidate?:string;appearance?:'primary'|'secondary'}){
 const [reason,setReason]=useState('');const router=useRouter();const recovery=useCorrectionRecovery(p,`command:${p.caseId}:${p.run??''}`,saved=>setReason(String(saved.get('reason')??'')));const {state,action,pending}=recovery;
 return <form action={action} onReset={e=>e.preventDefault()} className={styles.form}>{Object.entries({tenant:p.tenant,employer:p.employer,output:p.output,case:p.caseId,revision:p.revision,operation:p.operation,kind:p.kind??'compensation',period:p.period??'',run:p.run??'',candidate:p.candidate??''}).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<fieldset disabled={pending||state.saved||recovery.unresolved} className={styles.paymentFields}><legend>{p.label}</legend>{p.operation==='finalize'?<label><input type="checkbox" name="confirm" required/>راجعت البدائل المعتمدة وأريد تثبيتها معًا مع حفظ الأصول واستهلاك المدخلات مرة واحدة.</label>:<label>بيان الإجراء<textarea name="reason" value={reason} onChange={e=>setReason(e.target.value)} required minLength={3} maxLength={500}/></label>}<button className={p.appearance?`${p.appearance}-button ${styles.primary}`:undefined}>{pending?'جارٍ التنفيذ.':p.label}</button></fieldset><RecoveryNotice recovery={recovery}/>{state.saved&&<p role="status">تم حفظ الإجراء. <button type="button" className="secondary-button" onClick={()=>router.refresh()}>عرض النتيجة الحالية</button></p>}{state.error&&<p role="alert">{state.error}</p>}</form>;
}
export function SettlementForm(p:{canRecord:boolean;actor:string;tenant:string;employer:string;output:string;caseId:string;revision:number;today:string;employees:Choice[]}){
 const [fields,setFields]=useState({employment:'',direction:'employee_extra_payment',amount:'',date:p.today,reference:'',reason:''});const router=useRouter();const recovery=useCorrectionRecovery(p,`settlement:${p.caseId}`,saved=>setFields(f=>Object.fromEntries(Object.keys(f).map(k=>[k,String(saved.get(k)??'')])) as typeof f));const {state,action,pending}=recovery;
 return <form action={action} onReset={e=>e.preventDefault()} className={styles.form}>{Object.entries({tenant:p.tenant,employer:p.employer,output:p.output,case:p.caseId,revision:p.revision,operation:'settlement'}).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<fieldset disabled={pending||state.saved||recovery.unresolved||!p.canRecord} className={styles.paymentFields}><legend>دليل تنفيذ تسوية خارجية معتمدة</legend><p>يُسجّل هذا الدليل مقابل مسؤولية التسوية المستقلة. لا يعدل دفعة الراتب الأصلي أو صافيها، ولا يُنشئ تأهيلًا قانونيًا للحساب.</p><label>الموظف<PagedChoice scope={{tenant:p.tenant,employer:p.employer,output:p.output,kind:'input_revision'}} choice="employees" name="employment" value={fields.employment} required onChange={value=>setFields(f=>({...f,employment:value}))} initial={p.employees} placeholder="موظف التسوية"/></label><label>اتجاه التسوية<select name="direction" value={fields.direction} onChange={e=>setFields(f=>({...f,direction:e.target.value}))}><option value="employee_extra_payment">مبلغ إضافي صُرف للموظف</option><option value="employee_recovery">مبلغ استُرد بالفعل من الموظف</option></select></label>{(['amount','date','reference','reason'] as const).map(key=><label key={key}>{key==='amount'?'المبلغ الفعلي':key==='date'?'تاريخ التنفيذ':key==='reference'?'مرجع الدليل':'بيان التنفيذ'}<input name={key} type={key==='date'?'date':'text'} max={key==='date'?p.today:undefined} value={fields[key]} required maxLength={500} onChange={e=>setFields(f=>({...f,[key]:e.target.value}))}/></label>)}<button>{pending?'جارٍ التحقق…':'تسجيل دليل التسوية'}</button></fieldset><RecoveryNotice recovery={recovery}/>{!p.canRecord&&<p>يلزم التفويض الحالي لتسجيل دليل التسوية. الطلب السابق محفوظ للتحقق بعد استعادة التفويض.</p>}{state.error&&<p role="alert">{state.error}</p>}{state.saved&&<p role="status">حُفظ الدليل. <button type="button" onClick={()=>router.refresh()}>عرض المسؤولية المحدثة</button></p>}</form>;
}

function RecoveryNotice({recovery:r}:{recovery:ReturnType<typeof useCorrectionRecovery>}){return r.unresolved?<div role="alert"><p>يوجد طلب سابق لم تتأكد نتيجته. القيم الأصلية محفوظة؛ استعد نتيجته قبل تنفيذ إجراء آخر.</p><p>استعد نتيجة الطلب من الإجراء المحفوظ أعلى الصفحة. لا تُدخل طلبًا جديدًا قبل حسمها.</p></div>:null;}

export function CorrectionRecoveryPanel(p:{actor:string;tenant:string;employer:string;output:string}){const r=useCorrectionRecovery(p,'receipt-recovery',()=>{});const router=useRouter();if(!r.unresolved&&r.closedUncommitted)return <p role="status">تأكدنا أن الطلب السابق لم يُنفّذ، وأغلقناه لمنع تنفيذه لاحقًا. القيم محفوظة؛ حدّث المصدر ثم راجعها وأعد المعاينة قبل الحفظ. <Link href={r.originalHref}>العودة إلى القيم المحفوظة</Link> <button type="button" onClick={()=>router.refresh()}>تحديث المصدر مع الاحتفاظ بالحقول</button></p>;if(!r.unresolved)return r.state.saved?<p role="status">استُعيدت نتيجة الطلب الأصلي. <button type="button" onClick={()=>router.refresh()}>عرض الحالة المحدثة</button>{r.state.caseId&&<Link href={`/tenant/${p.tenant}/payroll/corrections?${new URLSearchParams({employer:p.employer,output:p.output,case:r.state.caseId,kind:r.state.kind??''})}`}>مراجعة نتيجة الطلب</Link>}</p>:null;return <section className={styles.card}><h2>استعادة نتيجة الطلب السابق</h2><p>لم تتأكد نتيجة هذا الطلب. احتفظنا بقيمه ونسخته الأصلية؛ تحقّق منه قبل أي إجراء جديد.</p><dl>{r.summary.map(([key,value])=><div key={key}><dt>{key==='amount'?'المبلغ':key==='date'?'التاريخ':key==='reference'?'المرجع':'البيان'}</dt><dd><bdi>{value}</bdi></dd></div>)}</dl><form action={r.action} onReset={e=>e.preventDefault()}><button disabled={r.pending} formNoValidate>{r.pending?'جارٍ استعادة النتيجة…':'استعادة نتيجة الطلب الأصلي'}</button></form>{r.state.error&&<p role="alert">{r.state.error}</p>}</section>;}
