import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PageFrame} from '@/components/context-navigation';
import {createSupabaseServerClient} from '@/lib/supabase/server';
import {uuid,displayDate} from '../rules';
import {correctionKinds,correctionStatuses,type CorrectionKind} from './rules';
import {ProposalForm,CorrectionCommand,SettlementForm,CorrectionRecoveryPanel} from './CorrectionForms';
import {type InputKind} from '../inputs/rules';
import {SourcePicker} from './SourcePicker';
import {money,issueNames,type Issue} from '../runs/rules';
import styles from '../payroll.module.css';
import {leaveCorrectionHref,type LeaveCorrectionContext} from '@/lib/payroll/leave-correction-context';
export const dynamic='force-dynamic';
type Source={id:string;expected_hash:string;kind?:InputKind;name?:string;fresh?:boolean;affects_paid_output?:boolean;fields?:Record<string,unknown>};
type Workspace={employer:{display_name:string};period:{id:string;starts_on:string;ends_on:string};today:string;ever_paid:boolean;superseded:boolean;employees:{id:string;name:string;code:string}[];sources:Source[];sites:{id:string;name:string}[];references:Record<string,{id:string;name:string;version?:number}[]>;period_choices:{id:string;starts_on:string;ends_on:string}[];replacement_outputs:{original_output:string;replacement_output:string;employer_id:string}[];output_choices:{id:string;employer:string;starts_on:string;ends_on:string}[];component_choices:{id:string;name:string;classification:string}[];access:{can_view_final:boolean;can_view_payments:boolean;can_prepare:boolean;can_approve:boolean;can_record:boolean};case:null|{affected_count:number;affected_outputs:{id:string;ever_paid:boolean;starts_on:string;ends_on:string}[];id:string;revision:number;status:string;proposal_id:string;reason:string;reference:string;changes:{type:string;source_id?:string;expected_hash?:string;fields?:Record<string,unknown>}[];target_period?:string;responsibilities:{employment_id:string;output_id?:string;basis:string;amount:string;source:string;reference:string;component_id?:string;target_period?:string}[]};amendments:{id:string;period_id:string;revision:number;status:string;candidate_id:string;approval:{ready:boolean;blocking_count:number;stale_reasons:string[]}|null;issues:Issue[]|null}[];history:{id:string;status:string;revision:number;created_at:string}[];settlements:{employment_id:string;direction:string;amount:string;occurred_on:string;reference:string;reason:string}[]};
export default async function CorrectionsPage({params,searchParams}:{params:Promise<{tenantId:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {tenantId}=await params;if(!uuid(tenantId))notFound();const q=await searchParams;const path=`/tenant/${tenantId}/payroll/corrections`;
 const keep=Object.fromEntries(Object.entries(q).filter((x):x is [string,string]=>typeof x[1]==='string'));
 const href=(extra:Record<string,string>)=>`${path}?${new URLSearchParams({...keep,...extra})}`;
 const failure=(text:string)=><PageFrame><section dir="rtl" className={styles.card}><h1>تصحيح راتب مقفل</h1><p role="alert">{text}</p><Link href={href({})}>إعادة المحاولة بنفس السياق</Link> · <Link href={`/tenant/${tenantId}/payroll?${new URLSearchParams({employer:q.employer??'',period:q.period??''})}`}>العودة إلى الرواتب</Link></section></PageFrame>;
 if((q.employer&&!uuid(q.employer))||(q.output&&!uuid(q.output))||['case','employee','person','after','source','request'].some(key=>q[key]&&!uuid(q[key]!)))return failure('راجع سياق الجهة والموظف والفترة.');
 const kind=(q.request?'source_change':q.kind??'compensation') as CorrectionKind;if(!Object.hasOwn(correctionKinds,kind))return failure('راجع نوع المصدر المطلوب تصحيحه.');
 const client=await createSupabaseServerClient();if(!client)return failure('تعذر الاتصال ببيانات التصحيح.');const {data:{user}}=await client.auth.getUser();if(!user)redirect(`/auth/login?next=${encodeURIComponent(href({}))}`);
 let requestContext:LeaveCorrectionContext|undefined;
 if(q.request){
  const contextResult=await client.rpc('payroll_leave_correction_context',{p_tenant:tenantId,p_request:q.request});
  if(contextResult.error||!contextResult.data)return failure('تعذر استعادة سياق الطلب أو لا تملك صلاحية تصحيح الرواتب.');
  requestContext=contextResult.data as LeaveCorrectionContext;
  if((q.employer&&q.employer!==requestContext.employer_id)||(q.employee&&q.employee!==requestContext.employment_id))return failure('لا يطابق الرابط جهة العمل أو الموظف المرتبط بالطلب.');
  if(!q.output)return <PageFrame><section className={styles.card} dir="rtl"><h1>مخرجات الرواتب المتأثرة بالطلب</h1>
   {requestContext.outputs.map(output=><p key={output.id}><Link href={leaveCorrectionHref(tenantId,requestContext!,output.id)}>مراجعة التصحيح — {displayDate(output.starts_on)} إلى {displayDate(output.ends_on)}</Link></p>)}
   {requestContext.outputs.length===0&&<p>لا توجد مسؤولية تصحيح مفتوحة لهذا الطلب أو استبدالاته.</p>}</section></PageFrame>;
  if(!requestContext.outputs.some(output=>output.id===q.output))return failure('لا توجد مسؤولية تصحيح مفتوحة لهذا الطلب على المخرج المحدد.');
  q.employer=requestContext.employer_id;q.employee=requestContext.employment_id;q.kind='source_change';
  Object.assign(keep,{employer:q.employer,employee:q.employee,kind:q.kind});
 }
 if(!q.output){
  const discovery=await client.rpc('payroll_correction_outputs',{p_tenant:tenantId,p_employer:q.employer||null,p_person:q.person||null,p_after:q.after||null});
  if(discovery.error)return failure(discovery.error.code==='42501'?'يلزم مسؤول مخول بتصحيح الرواتب. أرسل له الجهة والموظف والتاريخ المطلوب تصحيحه.':'تعذر تحميل المخرجات؛ أعد المحاولة بنفس السياق.');
  const outputs=discovery.data as {id:string;employer_id:string;period_id:string;employer:string;starts_on:string;ends_on:string;ever_paid:boolean}[];
  return <PageFrame><main dir="rtl" className={styles.workspace}><section className={styles.card}><h1>اختر المسير الأصلي للتصحيح</h1><p>تحدد الفترة نطاق أثر المصدر. الأجر النهائي لا يُعرض هنا.</p>{outputs.map(o=><p key={o.id}><Link href={href({employer:o.employer_id,period:o.period_id,output:o.id,after:''})}>{o.employer} · {displayDate(o.starts_on)} — {displayDate(o.ends_on)}</Link> · {o.ever_paid?'سبق دفعه':'لم يُسجّل دفع'}</p>)}{outputs.length===0&&<p>لا يوجد مخرج نهائي مطابق لهذا السياق. راجع الموظف والجهة أو مسؤول الرواتب.</p>}{outputs.length===30&&<Link href={href({after:outputs[29].id})}>مخرجات إضافية</Link>}<Link href={`/tenant/${tenantId}/payroll?${new URLSearchParams({employer:q.employer??''})}`}>العودة إلى الرواتب</Link></section></main></PageFrame>;
 }
 if(!q.employer)return failure('حدد الجهة القانونية للمخرج الأصلي.');
 const result=await client.rpc('payroll_correction_workspace',{p_tenant:tenantId,p_employer:q.employer,p_output:q.output,p_case:q.case||null,p_kind:kind,p_employee:q.employee||null,p_after:q.after||null});
 if(result.error||!result.data)return failure(result.error?.code==='42501'?'يلزم مسؤول مخول بتصحيح الرواتب وإدارة هذا المصدر. لم تتغير البيانات.':'تعذر تحميل المراجعة. أعد المحاولة بنفس الجهة والفترة والمصدر.');
 const w=result.data as Workspace,c=w.case;
 const navigationSources=requestContext?.outputs.find(output=>output.id===q.output)?.source_ids;
 const navigationObservations=navigationSources&&!c?await Promise.all(navigationSources.map(async id=>{
  const choice=await client.rpc('payroll_correction_choices',{p_tenant:tenantId,p_employer:q.employer,p_output:q.output,p_kind:'source_change',p_choice:'sources',p_selected:id,p_employee:q.employee});
  return choice.error?undefined:choice.data?.selected as Source|undefined;
 })):undefined;
 if(navigationObservations?.some(source=>!source||!source.fresh))return failure('تغير مصدر الطلب أثناء فتح التصحيح. أعد تحميل الطلب لاستعادة المصادر الحالية.');
 const navigationObservationProposal=navigationObservations?{observations:navigationObservations.map(source=>({id:source!.id,name:source!.name??'مصدر الإجازة',expected_hash:source!.expected_hash,fresh:source!.fresh,affects_paid_output:source!.affects_paid_output})),reason:'',reference:'',target:'',rows:[]}:undefined;
 const selected=q.source?await client.rpc('payroll_correction_choices',{p_tenant:tenantId,p_employer:q.employer,p_output:q.output,p_kind:kind,p_choice:'sources',p_selected:q.source,p_employee:q.employee||null}):null;
 const savedChange=q.edit==='1'?c?.changes[0]:undefined;
 const savedKind=savedChange?.type.replace(/_split$/,'');
 if(savedKind&&savedKind!==kind&&Object.hasOwn(correctionKinds,savedKind))redirect(href({kind:savedKind,source:'',employee:''}));
 const savedSource=savedChange&&kind!=='source_change'&&kind!=='new_employment'&&savedChange.source_id?await client.rpc('payroll_correction_choices',{p_tenant:tenantId,p_employer:q.employer,p_output:q.output,p_kind:kind,p_choice:'sources',p_selected:savedChange.source_id,p_employee:null}):null;
 if(savedSource&&(savedSource.error||!savedSource.data?.selected))return failure('تعذر استعادة مصدر المقترح المحفوظ. أعد المحاولة دون إنشاء مقترح جديد.');
 const currentSource=(savedSource?.data?.selected as Source|undefined)??(selected?.data?.selected as Source|undefined)??w.sources.find(x=>x.id===q.source)??(w.sources.length===1?w.sources[0]:undefined);
 const source=savedChange&&kind!=='source_change'&&currentSource?{...currentSource,expected_hash:savedChange.expected_hash??currentSource.expected_hash}:currentSource;
 const editingObservations=kind==='source_change'&&q.edit==='1'&&c?await Promise.all(c.changes.filter(change=>change.type==='source_change'&&uuid(change.source_id??'')).map(async change=>{
  const choice=await client.rpc('payroll_correction_choices',{p_tenant:tenantId,p_employer:q.employer,p_output:q.output,p_kind:kind,p_choice:'sources',p_selected:change.source_id,p_employee:null});
  const current=choice.data?.selected as Source|undefined;
  return {id:change.source_id!,name:current?.name??'تغيير محفوظ يحتاج تحديث المصدر',expected_hash:change.expected_hash??'',fresh:!choice.error&&current?.fresh===true&&current.expected_hash===change.expected_hash,affects_paid_output:current?.affects_paid_output};
 })):undefined;
 const savedObservationProposal=editingObservations&&c?{observations:editingObservations,reason:c.reason,reference:c.reference,target:c.target_period??'',rows:c.responsibilities.map(row=>({employment:row.employment_id,output:row.output_id??q.output!,basis:row.basis,amount:String(row.amount),component:row.component_id??'',reference:row.reference,source:row.source,target:row.target_period??c.target_period??''}))}:navigationObservationProposal;
 const shared={actor:user.id,tenant:tenantId,employer:q.employer,output:q.output};
 const savedProposal=q.edit==='1'&&c&&savedChange&&kind!=='source_change'?{fields:savedChange.fields??{},unchangedChanges:c.changes.slice(1),split:savedChange.type.endsWith('_split'),reason:c.reason,reference:c.reference,target:c.target_period??'',rows:c.responsibilities.map(row=>({employment:row.employment_id,output:row.output_id??q.output!,basis:row.basis,amount:String(row.amount),component:row.component_id??'',reference:row.reference,source:row.source,target:row.target_period??c.target_period??''}))}:undefined;
 return <PageFrame><main dir="rtl" className={styles.workspace}>
 <section className={styles.card}><h1>تصحيح راتب مقفل</h1><p>{w.employer.display_name} · {displayDate(w.period.starts_on)} — {displayDate(w.period.ends_on)}</p><p>{c?correctionStatuses[c.status]:w.ever_paid?'سبق دفع هذا المسير: يلزم تصحيح ومسؤولية تسوية مستقلة.':'لم يُسجل دفع: يمكن إعداد تعديل يحفظ الأصل حتى اعتماد البديل وإقفاله.'}</p><div className={styles.actions}>{w.access.can_view_final&&<Link href={`/tenant/${tenantId}/payroll/output?${new URLSearchParams({employer:q.employer,output:q.output})}`}>المخرج الأصلي</Link>}{w.access.can_view_payments&&<Link href={`/tenant/${tenantId}/payroll/payments?${new URLSearchParams({employer:q.employer,output:q.output})}`}>مطابقة الدفعات الأصلية</Link>}<Link href={`/tenant/${tenantId}/payroll?${new URLSearchParams({employer:q.employer,period:w.period.id})}`}>الرواتب</Link></div></section>
 <CorrectionRecoveryPanel {...shared}/>
 {w.superseded?<section className={styles.card}><h2>حُفظ هذا المخرج ضمن تاريخ الاستبدال</h2><p>افتح المخرج البديل لمتابعة العمل الحالي. الأصل ودليل التصحيح محفوظان.</p></section>:c&&q.edit!=='1'?<>
 <section className={styles.card}><h2>المقترح الحالي</h2><p>{c.reason} · المرجع: {c.reference}</p><p>عدد تغييرات المصدر: {c.changes.length} · المخرجات المتأثرة: {c.affected_count}. اعتماد المقترح مستقل عن اعتماد أي مبلغ نهائي مؤهل قانونيًا.</p>
 {c.responsibilities.length>0&&<ul>{c.responsibilities.map((r,i)=><li key={i}>{w.employees.find(e=>e.id===r.employment_id)?.name??'موظف التوظيف المقترح'} · {r.basis==='external_reviewed'?'مسؤولية خارجية مستقلة':'مدخل لاحق يحتاج تأهيلًا قانونيًا'} · <bdi>{money(r.amount)}</bdi> EGP · {r.source} · {r.reference}</li>)}</ul>}
 {c.status==='draft'&&w.ever_paid&&c.affected_outputs.every(o=>o.ever_paid)&&w.access.can_approve&&<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="approve" label="اعتماد المقترح ونطاق مسؤولياته"/>}
 {c.status==='draft'&&(!w.ever_paid||c.affected_outputs.some(o=>!o.ever_paid))&&w.access.can_prepare&&<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="calculate" label="حساب أثر التعديل للمراجعة"/>}
 {c.status==='approved'&&w.ever_paid&&c.affected_outputs.every(o=>o.ever_paid)&&<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="route_paid" label="تطبيق المصدر وربط مسؤولية التصحيح المعتمدة"/>}
 {c.status==='approved'&&c.affected_outputs.some(o=>!o.ever_paid)&&<div><p>الأصل والمصدر لم يتغيرا. يلزم حساب أثر التصحيح على كل المسيرات المتأثرة، ثم مراجعة المبالغ واعتماد البدائل معًا. إذا لم تُحسب الآثار أو تغيرت مصادرها، أعد المقترح إلى المراجعة.</p>{w.access.can_approve?<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="release" label="إعادة المقترح إلى المراجعة"/>:<p>اطلب من مسؤول اعتماد الرواتب إعادة المقترح إلى المراجعة. اختيارات المصدر والمسؤوليات محفوظة.</p>}</div>}
 </section>
 {w.amendments.length>0&&<section className={styles.card}><h2>مراجعة المخرجات المتأثرة</h2>{w.amendments.map(r=><article key={r.id}><h3>{r.status==='approved'?'مرشح معتمد':'مرشح تعديل'}</h3>{r.approval&&<p>موانع الاعتماد: {r.approval.blocking_count} · {r.approval.stale_reasons.length?'تغيرت مصادر المراجعة؛ أعد الحساب':'نسخة الأثر محفوظة'}</p>}{r.issues&&<ul>{r.issues.map((issue,index)=><li key={index}>{issueNames[issue.code]??'يلزم استكمال المصدر أو التأهيل القانوني لهذا الأثر.'}</li>)}</ul>}{c.status==='approved'&&w.access.can_approve&&r.status==='review'&&r.approval?.ready&&<CorrectionCommand {...shared} caseId={c.id} period={r.period_id} run={r.id} candidate={r.candidate_id} revision={r.revision} operation="approve_candidate" label="اعتماد مرشح التعديل المؤهل"/>}{w.access.can_approve&&r.status==='approved'&&<CorrectionCommand {...shared} caseId={c.id} period={r.period_id} run={r.id} candidate={r.candidate_id} revision={r.revision} operation="release_candidate" label="إعادة المرشح إلى المراجعة"/>}</article>)}</section>}
 {c.status==='review'&&w.access.can_approve&&<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="approve" label="اعتماد المقترح بعد مراجعة الأثر"/>}
 {c.status==='routed'&&c.responsibilities.some(r=>r.basis==='external_reviewed')&&<section className={styles.card}><SettlementForm {...shared} canRecord={w.access.can_record} caseId={c.id} revision={c.revision} today={w.today} employees={w.employees}/></section>}
 {c.status==='review'&&w.access.can_prepare&&c.affected_outputs.some(o=>!o.ever_paid)&&<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="calculate" label="إعادة حساب أثر التعديل"/>}
 {(['draft','review'].includes(c.status)||(c.status==='approved'&&c.affected_outputs.every(o=>o.ever_paid)&&w.access.can_approve))&&<details className={styles.card}><summary>إجراءات أخرى للمقترح</summary>{['draft','review'].includes(c.status)&&<Link href={href({edit:'1',source:''})}>تعديل المصدر وإعادة معاينة المقترح</Link>}{c.status==='approved'?<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="release" label="إعادة المقترح إلى المراجعة"/>:<CorrectionCommand {...shared} caseId={c.id} revision={c.revision} operation="cancel" label="إلغاء المقترح مع حفظ التاريخ"/>}</details>}
 </>:<section className={styles.card}><h2>حدد ما يحتاج إلى تصحيح</h2>{!savedChange&&<SourcePicker scope={{tenant:tenantId,employer:q.employer,output:q.output,kind}} href={href({})} employee={q.employee??''} source={q.source??''}/>}{kind==='new_employment'||source||savedObservationProposal?<ProposalForm key={`${kind}:${source?.id??'new'}:${c?.proposal_id??'new'}`} {...shared} caseId={c?.id} revision={c?.revision??0} kind={kind} employee={q.employee} source={source} initialProposal={savedProposal} initialObservationProposal={savedObservationProposal} observations={kind==='source_change'?w.sources.map(x=>({id:x.id,name:x.name??'التغيير المسجل',expected_hash:x.expected_hash,fresh:x.fresh,affects_paid_output:x.affects_paid_output})):undefined} employees={w.employees} sites={w.sites} references={w.references} periods={w.period_choices} components={w.component_choices} outputs={w.output_choices} everPaid={w.ever_paid||Boolean(source?.affects_paid_output)}/>:<p>{kind==='source_change'?'لا توجد تغييرات مسجلة لهذا المسير. إذا احتجت تعديل الحضور أو الإجازة، سجّله من الخدمة المختصة أولًا.':'اختر الموظف ثم افتح النسخة المطلوبة. التوظيف المستحق غير المسجل له مسار مستقل أعلاه.'}</p>}</section>}
 {c&&['routed','completed','cancelled'].includes(c.status)&&!w.superseded&&<Link href={href({case:'',edit:'',source:''})}>إعداد مقترح جديد مع حفظ التصحيح السابق</Link>}
 {w.replacement_outputs.map(x=><p key={x.replacement_output}>{w.access.can_view_final?<Link href={`/tenant/${tenantId}/payroll/output?${new URLSearchParams({employer:x.employer_id,output:x.replacement_output})}`}>المخرج البديل المحفوظ</Link>:'المخرج البديل محفوظ؛ راجع مسؤول عرض الرواتب لفتحه.'}</p>)}
 <details className={styles.card}><summary>تاريخ التصحيح ودليل التسوية</summary>{w.history.map(h=><p key={h.id}><Link href={href({case:h.id})}>{correctionStatuses[h.status]}</Link> · {displayDate(h.created_at.slice(0,10))}</p>)}{w.settlements.map((s,i)=><p key={i}>{s.direction==='employee_recovery'?'استرداد فعلي':'صرف إضافي فعلي'} · <bdi>{money(s.amount)}</bdi> EGP · {displayDate(s.occurred_on)} · {s.reference}</p>)}</details>
 </main></PageFrame>;
}
