import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {createContext,runInContext} from 'node:vm';
const require=createRequire(import.meta.url),ts=require('typescript');
function load(url,dependencies={}){const context=createContext({exports:{},URLSearchParams,require:name=>{assert.ok(name in dependencies,`unexpected internal dependency ${name}`);return dependencies[name];}});runInContext(ts.transpileModule(readFileSync(url,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,context);return context.exports;}
const common=load(new URL('../rules.ts',import.meta.url)),rules=load(new URL('./rules.ts',import.meta.url));
const tenant='c4481000-0000-4000-8000-000000000001',employer='c4483000-0000-4000-8000-000000000001',output='c4489500-0000-4000-8000-000000000001',replacement='c4489500-0000-4000-8000-000000000002',employee='c4485000-0000-4000-8000-000000000001',site='c4483500-0000-4000-8000-000000000001';
function links(tree){if(!tree||typeof tree!=='object')return [];if(Array.isArray(tree))return tree.flatMap(links);return [...(tree.props?.href?[tree.props.href]:[]),...links(tree.props?.children)];}
function harness(mode){const calls=[];const client={auth:{getUser:async()=>({data:{user:{id:'modeled-actor'}}})},rpc:async(name,args)=>{calls.push({name,args});
 if(name==='payroll_report_employers')return {data:{items:[{id:employer,name:'Owned Employer'}]}};
 if(name==='payroll_report_choices')return {data:{items:[{id:output,starts_on:'2030-01-25',ends_on:'2030-02-24',superseded:mode==='replacement'}],selected:[],next:null}};
 if(name==='payroll_report_dimensions')return mode==='invalid-dimension'?{error:{code:'42501'}}:{data:{items:[{id:site,name:'Saved Site'}],selected:null,next:null}};
 if(name==='payroll_report_workspace')return {data:{report:'sheet',output_id:output,employer:{name:'QA',legal_name:'QA NONLEGAL'},period:{starts_on:'2030-01-25',ends_on:'2030-02-24'},previous_period:null,rows:[],next:null,total_count:0,summary:{net:'0.00'},issues:mode==='replacement'?['superseded']:[],source_revision:'a'.repeat(32),superseded:mode==='replacement',replacement_output_id:mode==='replacement'?replacement:null,can_export:true}};
 throw new Error('unexpected RPC');}};
 const jsx=(type,props)=>({type,props});const page=load(new URL('./page.tsx',import.meta.url),{'react/jsx-runtime':{jsx,jsxs:jsx},'next/link':{default:'Link'},'next/navigation':{notFound:()=>{throw Error('notFound');},redirect:href=>{throw Object.assign(Error('redirect'),{href});}},'@/components/context-navigation':{PageFrame:'Frame'},'@/lib/supabase/server':{createSupabaseServerClient:async()=>client},'../rules':common,'./rules':rules,'./PrintPayslipButton':{PrintPayslipButton:'PrintButton'},'./reports.module.css':{default:{}}});
 return {calls,run:query=>page.default({params:Promise.resolve({tenantId:tenant}),searchParams:Promise.resolve(query)})};}
// Actual server page and internal helpers with modeled Auth/RPC/render nodes.
test('Employer entry matches the actual declared RPC arguments and reaches owned choices',async()=>{const h=harness(),tree=await h.run({});assert.ok(links(tree).some(href=>href.includes(employer)));const call=h.calls[0];assert.equal(call.name,'payroll_report_employers');const sql=readFileSync(new URL('../../../../../../supabase/migrations/20261002074500_cube4_payroll_reports.sql',import.meta.url),'utf8');const parameters=/CREATE FUNCTION public.payroll_report_employers\(([^)]+)\)/.exec(sql)[1].split(',').map(value=>value.trim().split(' ')[0]);assert.deepEqual(Object.keys(call.args).sort(),parameters.sort());});
test('explicit output change redirects to new scope and announces dependent filter reset',async()=>{const h=harness();await assert.rejects(h.run({employer,output:replacement,scope_output:output,site,employee,after:employee,revision:'obsolete'}),error=>{const url=new URL(error.href,'http://local.invalid');assert.equal(url.searchParams.get('output'),replacement);assert.equal(url.searchParams.get('scope_changed'),'1');for(const key of ['site','employee','after','revision','scope_output'])assert.equal(url.searchParams.has(key),false);return true;});assert.equal(h.calls.length,0);});
test('invalid dimension selection offers explicit clear-scope recovery rather than a repeating refresh only',async()=>{const h=harness('invalid-dimension'),tree=await h.run({employer,output,site,employee});const recovery=links(tree).map(href=>new URL(href,'http://local.invalid')).find(url=>url.searchParams.get('output')===output&&!url.searchParams.has('site')&&!url.searchParams.has('employee'));assert.ok(recovery);assert.ok(!h.calls.some(call=>call.name==='payroll_report_workspace'));});
test('replacement navigation clears old output-dependent filters and employee scope',async()=>{const h=harness('replacement'),tree=await h.run({employer,output,site,employee});const link=links(tree).map(href=>new URL(href,'http://local.invalid')).find(url=>url.searchParams.get('output')===replacement);assert.ok(link);assert.equal(link.searchParams.has('site'),false);assert.equal(link.searchParams.has('employee'),false);assert.equal(link.searchParams.get('scope_changed'),'1');});
