import Link from 'next/link';
import { PageFrame } from '@/components/context-navigation';
import { channelReasonLabel,channelStateLabel,formatChannelInstant } from '@/lib/attendance-channel';
import { MappingForm,SourceForm } from '../ChannelForms';
import { channelOffset,ChannelPager,channelSession,ChannelUnavailable,type Source,type EventRow,type Mapping,type Options } from '../shared';
export const dynamic='force-dynamic';
export default async function SourcePage({params,searchParams}:{params:Promise<{tenantId:string;sourceId:string}>;searchParams:Promise<{offset?:string;mappingOffset?:string;q?:string;siteQ?:string}>}) {
 const {tenantId,sourceId}=await params,query=await searchParams,offset=channelOffset(query.offset),mappingOffset=channelOffset(query.mappingOffset),session=await channelSession(tenantId);if(!session) return <ChannelUnavailable tenantId={tenantId}/>;
 const [detail,events,mappings,options,siteOptions]=await Promise.all([session.db.rpc('attendance_channel_source_detail',{p_tenant:tenantId,p_source:sourceId}),session.db.rpc('attendance_channel_events',{p_tenant:tenantId,p_source:sourceId,p_limit:20,p_offset:offset}),session.db.rpc('attendance_channel_mappings',{p_tenant:tenantId,p_source:sourceId,p_limit:20,p_offset:mappingOffset}),session.access.can_manage?session.db.rpc('attendance_channel_options',{p_tenant:tenantId,p_search:(query.q??'').slice(0,100),p_limit:20}):Promise.resolve({data:{employees:[],sites:[]},error:null}),session.access.can_manage?session.db.rpc('attendance_channel_options',{p_tenant:tenantId,p_search:(query.siteQ??'').slice(0,100),p_limit:20}):Promise.resolve({data:{employees:[],sites:[]},error:null})]);
 if(detail.error || events.error || mappings.error || options.error || siteOptions.error) return <ChannelUnavailable tenantId={tenantId}/>;
 const source=detail.data as Source,rows=(events.data?.items??[]) as EventRow[],mapRows=(mappings.data?.items??[]) as Mapping[],choices={employees:(options.data as Options).employees,sites:(siteOptions.data as Options).sites};
 const attention=(e:EventRow)=>e.review_required || ['unmapped','retry_failed','received','retrying'].includes(e.state);rows.sort((a,b)=>Number(attention(b))-Number(attention(a)));
 const base=`/tenant/${tenantId}/attendance/sources/${sourceId}`;
 return <PageFrame><div className="channel-page"><Link className="secondary-button" href={`/tenant/${tenantId}/attendance/sources`}>العودة إلى القنوات</Link><header className="workspace-page-heading"><div><h1>{source.name}</h1><p>{source.kind==='mobile'?'حضور الهاتف':'مصدر خارجي'} · {source.site_name??'الموقع يُحدد بالربط'} · {source.enabled?'مفعّلة':'موقوفة'}</p></div></header>
 <section className="workspace-records-panel"><h2>الحركات والمهام المطلوبة</h2><p className="field-hint">تُرتب الحركات المحتاجة للمتابعة أولًا ضمن هذه الصفحة فقط. استخدم التالي لبقية السجل؛ أعداد القناة في القائمة تشمل كامل سجلها.</p>{!rows.length?<p>لا توجد حركات في هذه الصفحة.</p>:<ul className="record-list">{rows.map(e=><li className="record-card" key={e.id}><div className="record-main"><h3>{e.employee_name??'موظف لم يُربط بعد'} <span className="entity-status">{channelStateLabel(e.state)}</span></h3><p>{e.direction==='in'?'حضور':e.direction==='out'?'انصراف':'اتجاه الحركة يحتاج مراجعة'} · {formatChannelInstant(e.happened_at,e.timezone_name??'UTC')}{!e.timezone_name?' (UTC)':''}</p>{e.review_required && <p className="form-message">تحتاج الحركة مراجعة دليل الموقع.</p>}{e.reason && <p>{channelReasonLabel(e.reason)}</p>}</div><Link className="secondary-button" href={`${base}/events/${e.id}`}>فتح الحركة</Link></li>)}</ul>}<ChannelPager href={base} offset={offset} more={events.data?.has_more===true}/></section>
 {source.kind==='external' && <section className="workspace-records-panel"><h2>سجل قرارات ربط الموظفين</h2><p className="field-hint">تُحفظ القرارات السابقة. آخر قرار لنفس الفترة يحكمها؛ تداخل فترتين مفعّلتين يحتاج تصحيح الربط.</p>{mapRows.length?<ul className="record-list">{mapRows.map(m=><li className="record-card" key={m.id}><div className="record-main"><h3>{m.employee_name} · {m.active?'قرار تفعيل':'قرار إلغاء'}</h3><p>معرّف المصدر: <bdi>{m.external_key}</bdi> · {m.site_name}</p><p>{formatChannelInstant(m.valid_from,'UTC')} (UTC) — {m.valid_until?`${formatChannelInstant(m.valid_until,'UTC')} (UTC)`:'بلا نهاية محددة'}</p>{session.access.can_manage && <details className="task-disclosure"><summary>تغيير قرار هذه الفترة</summary><MappingForm tenantId={tenantId} sourceId={sourceId} options={choices} mapping={m}/></details>}</div></li>)}</ul>:<p>لا توجد قرارات ربط.</p>}<nav className="attendance-pagination" aria-label="صفحات الربط">{mappingOffset>0 && <Link className="secondary-button" href={`${base}?mappingOffset=${Math.max(0,mappingOffset-20)}`}>الربط السابق</Link>}{mappings.data?.has_more && <Link className="secondary-button" href={`${base}?mappingOffset=${mappingOffset+20}`}>الربط التالي</Link>}</nav>{session.access.can_manage && <details className="task-disclosure" open={Boolean(query.q || query.siteQ)}><summary>إضافة ربط موظف</summary><form method="get" className="channel-search"><label htmlFor="mapping-search">ابحث عن موظف</label><input id="mapping-search" name="q" defaultValue={query.q??''} maxLength={100}/><label htmlFor="mapping-site-search">ابحث عن موقع</label><input id="mapping-site-search" name="siteQ" defaultValue={query.siteQ??''} maxLength={100}/><button className="secondary-button">البحث</button></form><p className="field-hint">أول ٢٠ نتيجة. يمكنك البحث بالاسم أو كود الموظف.</p><MappingForm tenantId={tenantId} sourceId={sourceId} options={choices}/></details>}</section>}
 <section className="workspace-records-panel"><h2>سجل إعدادات القناة</h2><ul className="record-list">{source.versions?.map(v=><li key={v.version} className="record-card"><div><h3>الإصدار {v.version} · {v.enabled?'مفعّل':'موقوف'}</h3><p>{v.reason}</p><p>{formatChannelInstant(v.created_at,'UTC')} (UTC)</p></div></li>)}</ul>{session.access.can_manage && <><details className="task-disclosure"><summary>تعديل سياسة القناة</summary><SourceForm tenantId={tenantId} source={source} options={choices}/></details>{source.enabled && <details className="danger-disclosure"><summary>إيقاف القناة</summary><SourceForm tenantId={tenantId} source={source} options={choices} disableOnly/></details>}</>}</section></div></PageFrame>;
}
