import { Button, ButtonLink, Disclosure, Input, Message, PageHeader, Panel, RecordCard, Badge, Field } from '@/components/ui';
import styles from '../../attendance-channels.module.css';
import { PageFrame } from '@/components/context-navigation';
import { channelReasonLabel,channelStateLabel,formatChannelInstant } from '@/lib/attendance-channel';
import { MappingForm,SourceForm } from '../ChannelForms';
import { channelOffset,channelHref,ChannelPager,channelSession,ChannelUnavailable,type Source,type EventRow,type Mapping,type Options } from '../shared';
export const dynamic='force-dynamic';
export default async function SourcePage({params,searchParams}:{params:Promise<{tenantId:string;sourceId:string}>;searchParams:Promise<{offset?:string;mappingOffset?:string;q?:string;siteQ?:string}>}) {
 const {tenantId,sourceId}=await params,query=await searchParams,offset=channelOffset(query.offset),mappingOffset=channelOffset(query.mappingOffset),session=await channelSession(tenantId);const base=`/tenant/${tenantId}/attendance/sources/${sourceId}`,context={offset,mappingOffset,q:query.q,siteQ:query.siteQ},retryHref=channelHref(base,context);if(!session) return <ChannelUnavailable tenantId={tenantId} retryHref={retryHref}/>;
 const [detail,events,mappings,options,siteOptions]=await Promise.all([session.db.rpc('attendance_channel_source_detail',{p_tenant:tenantId,p_source:sourceId}),session.db.rpc('attendance_channel_events',{p_tenant:tenantId,p_source:sourceId,p_limit:20,p_offset:offset}),session.db.rpc('attendance_channel_mappings',{p_tenant:tenantId,p_source:sourceId,p_limit:20,p_offset:mappingOffset}),session.access.can_manage?session.db.rpc('attendance_channel_options',{p_tenant:tenantId,p_search:(query.q??'').slice(0,100),p_limit:20}):Promise.resolve({data:{employees:[],sites:[]},error:null}),session.access.can_manage?session.db.rpc('attendance_channel_options',{p_tenant:tenantId,p_search:(query.siteQ??'').slice(0,100),p_limit:20}):Promise.resolve({data:{employees:[],sites:[]},error:null})]);
 if(detail.error || events.error || mappings.error || options.error || siteOptions.error) return <ChannelUnavailable tenantId={tenantId} retryHref={retryHref}/>;
 const source=detail.data as Source,rows=(events.data?.items??[]) as EventRow[],mapRows=(mappings.data?.items??[]) as Mapping[],choices={employees:(options.data as Options).employees,sites:(siteOptions.data as Options).sites};
 const attention=(e:EventRow)=>e.review_required || ['unmapped','retry_failed','received','retrying'].includes(e.state);rows.sort((a,b)=>Number(attention(b))-Number(attention(a)));

 return <PageFrame><div className="channel-page"><ButtonLink variant="ghost"  href={`/tenant/${tenantId}/attendance/sources`}>العودة إلى وسائل تسجيل الحضور</ButtonLink><header className="workspace-page-heading"><div><PageHeader  title={<>{source.name}</>} description={<> {source.kind==='mobile'?'حضور الهاتف':'مصدر خارجي'} · {source.site_name??'الموقع يُحدد بالربط'} · {source.enabled?'مفعّلة':'موقوفة'} </>} /></div></header><nav className={styles.sectionNav} aria-label="أقسام وسيلة تسجيل الحضور"><a href="#channel-events">الحركات والمتابعة</a>{source.kind==='external' && <a href="#channel-mappings">ربط الموظفين</a>}<a href="#channel-settings">الإعدادات والإصدارات</a></nav>
 <Panel ><h2 id="channel-events">الحركات والمهام المطلوبة</h2><p className="field-hint">تُرتب الحركات المحتاجة للمتابعة أولًا ضمن هذه الصفحة فقط. استخدم التالي لبقية السجل؛ الأعداد المعروضة لكل وسيلة حضور في القائمة تشمل كامل سجلها.</p>{!rows.length?<p>لا توجد حركات في هذه الصفحة.</p>:<ul className="record-list">{rows.map(e=><RecordCard  key={e.id}><div className="record-main"><h3>{e.employee_name??'موظف لم يُربط بعد'} <Badge tone="neutral" >{channelStateLabel(e.state)}</Badge></h3><p>{e.direction==='in'?'حضور':e.direction==='out'?'انصراف':'اتجاه الحركة يحتاج مراجعة'} · {formatChannelInstant(e.happened_at,e.timezone_name??'UTC')}{!e.timezone_name?' (UTC)':''}</p>{e.review_required && <Message tone="info" >تحتاج الحركة مراجعة بيانات الموقع.</Message>}{e.reason && <p>{channelReasonLabel(e.reason)}</p>}</div><ButtonLink variant="ghost"  href={`${base}/events/${e.id}`}>فتح الحركة</ButtonLink></RecordCard>)}</ul>}<ChannelPager href={channelHref(base,{mappingOffset,q:query.q,siteQ:query.siteQ})} offset={offset} more={events.data?.has_more===true}/></Panel>
 {source.kind==='external' && <Panel ><h2 id="channel-mappings">سجل قرارات ربط الموظفين</h2><p className="field-hint">تُحفظ القرارات السابقة. آخر قرار لنفس الفترة يحكمها؛ تداخل فترتين مفعّلتين يحتاج تصحيح الربط.</p>{mapRows.length?<ul className="record-list">{mapRows.map(m=><RecordCard  key={m.id}><div className="record-main"><h3>{m.employee_name} · {m.active?'قرار تفعيل':'قرار إلغاء'}</h3><p>معرّف المصدر: <bdi>{m.external_key}</bdi> · {m.site_name}</p><p>{formatChannelInstant(m.valid_from,'UTC')} (UTC) — {m.valid_until?`${formatChannelInstant(m.valid_until,'UTC')} (UTC)`:'بلا نهاية محددة'}</p>{session.access.can_manage && <Disclosure summary={<>تغيير قرار هذه الفترة</>} className="task-disclosure"><MappingForm tenantId={tenantId} sourceId={sourceId} options={choices} mapping={m}/></Disclosure>}</div></RecordCard>)}</ul>:<p>لا توجد قرارات ربط.</p>}<nav className="attendance-pagination" aria-label="صفحات الربط">{mappingOffset>0 && <ButtonLink variant="ghost"  href={channelHref(base,{...context,mappingOffset:Math.max(0,mappingOffset-20)})}>الربط السابق</ButtonLink>}{mappings.data?.has_more && <ButtonLink variant="ghost"  href={channelHref(base,{...context,mappingOffset:mappingOffset+20})}>الربط التالي</ButtonLink>}</nav>{session.access.can_manage && <Disclosure summary={<>إضافة ربط موظف</>} className="task-disclosure" open={Boolean(query.q || query.siteQ)}><form method="get" className="channel-search">{offset>0 && <input type="hidden" name="offset" value={offset}/>} {mappingOffset>0 && <input type="hidden" name="mappingOffset" value={mappingOffset}/>}<Field id="mapping-search" label={<>ابحث عن موظف</>}><Input id="mapping-search" name="q" defaultValue={query.q??''} maxLength={100}/></Field><Field id="mapping-site-search" label={<>ابحث عن موقع</>}><Input id="mapping-site-search" name="siteQ" defaultValue={query.siteQ??''} maxLength={100}/></Field><Button variant="ghost" type="submit" >البحث</Button></form><p className="field-hint">أول 20 نتيجة. يمكنك البحث بالاسم أو كود الموظف.</p><MappingForm tenantId={tenantId} sourceId={sourceId} options={choices}/></Disclosure>}</Panel>}
 <Panel ><h2 id="channel-settings">سجل إعدادات وسيلة تسجيل الحضور</h2><ul className="record-list">{source.versions?.map(v=><RecordCard key={v.version} ><div><h3>الإصدار {v.version} · {v.enabled?'مفعّل':'موقوف'}</h3><p>{v.reason}</p><p>{formatChannelInstant(v.created_at,'UTC')} (UTC)</p></div></RecordCard>)}</ul>{session.access.can_manage && <><Disclosure summary={<>تعديل سياسة وسيلة تسجيل الحضور</>} className="task-disclosure"><SourceForm tenantId={tenantId} source={source} options={choices}/></Disclosure>{source.enabled && <Disclosure summary={<>إيقاف وسيلة تسجيل الحضور</>} className="danger-disclosure"><SourceForm tenantId={tenantId} source={source} options={choices} disableOnly/></Disclosure>}</>}</Panel></div></PageFrame>;
}
