'use client';
import { Disclosure } from '@/components/ui';
import { Message } from '@/components/ui';
import { Button, Input, Select } from '@/components/ui';
import { useId } from 'react';
import { OfflineSubmissionNotice, useOfflineSubmission } from '@/components/offline-submission';
import {startTransition,useActionState,useRef,useState} from 'react';
import {saveComparison} from './actions';
import type {Source} from '../DraftForm';
import {scenarios,outputs} from './labels';
export type ComparisonState={saved:boolean;error:string;uncertain:boolean;stale:boolean;matched?:boolean};
export type ComparisonCase={name:string;scenario:string;origin:string;source_url:string;reference:string;tax:{net:string;duration:string;prior_due:string;from:string;until:string};insurance:{month:string;wage:string;reference:string}[];expected:Record<string,string>};
export function ComparisonForm({head,revision,actor,sources,secondary=false}:{head:string;revision:number;actor:string;sources:Source[];secondary?:boolean}){
 const { offline, blockOfflineSubmission } = useOfflineSubmission();
 const offlineHintId = useId();
 const [opened,setOpened]=useState(false);
 const [fields,setFields]=useState<ComparisonCase>({name:'',scenario:'',origin:'',source_url:sources[0]?.url??'',reference:'',tax:{net:'',duration:'',prior_due:'',from:'',until:''},insurance:[],expected:Object.fromEntries(Object.keys(outputs).map(key=>[key,'']))});const [dirty,setDirty]=useState(false);const request=useRef<{signature:string;attempt:string}|null>(null);
 const inFlight=useRef(false);
 const change=(update:(current:ComparisonCase)=>ComparisonCase)=>{setDirty(true);setFields(update);};
 async function submit(previous:ComparisonState,form:FormData){try{const signature=JSON.stringify(Array.from(form.entries()));if(!request.current||request.current.signature!==signature){if(previous.uncertain)return {...previous,saved:false,error:'استعد نتيجة الحفظ السابق بنفس البيانات أولًا.'};request.current={signature,attempt:crypto.randomUUID()};}form.set('attempt',request.current.attempt);try{const result=await saveComparison(previous,form);if(!result.uncertain)request.current=null;if(result.saved)setDirty(false);return result;}catch{return {...previous,saved:false,uncertain:true,error:'لم تصل نتيجة الحفظ. أعد المحاولة بنفس الحقول لاستعادة النتيجة.'};}}finally{inFlight.current=false;}}
 const [state,action,pending]=useActionState(submit,{saved:false,error:'',uncertain:false,stale:false});const frozen=pending||state.uncertain||state.stale;
 const amount=(id:string,label:string,value:string,onChange:(value:string)=>void,signed=false)=><label htmlFor={id}>{label}<Input id={id} value={value} onChange={event=>onChange(event.target.value)} required inputMode="decimal" dir="ltr" pattern={signed?'-?(0|[1-9][0-9]{0,11})(\\.[0-9]{1,2})?':'(0|[1-9][0-9]{0,11})(\\.[0-9]{1,2})?'} maxLength={16}/></label>;
 const showOfflineNotice = offline && !pending && !state.stale;
 return <Disclosure className={secondary ? "comparison-secondary" : undefined} summary={<>حالة مقارنة جديدة</>} open={opened||dirty||pending||state.uncertain||state.stale||Boolean(state.error)} onToggle={event=>{if((dirty||pending||state.uncertain||state.stale||state.error)&&!event.currentTarget.open){event.currentTarget.open=true;return;}setOpened(event.currentTarget.open);}}><form action={action} onSubmit={event=>{if(blockOfflineSubmission(event))return;event.preventDefault();if(inFlight.current||pending||state.stale)return;const form=new FormData(event.currentTarget);inFlight.current=true;startTransition(()=>action(form));}} className="auth-form" aria-busy={pending}><input type="hidden" name="head" value={head}/><input type="hidden" name="revision" value={revision}/><input type="hidden" name="actor" value={actor}/><input type="hidden" name="case" value={JSON.stringify(fields)}/><fieldset disabled={frozen}><legend>تسجيل حالة مقارنة</legend><label htmlFor="comparison-name">اسم الحالة<Input id="comparison-name" value={fields.name} onChange={event=>change(c=>({...c,name:event.target.value}))} required minLength={3} maxLength={160}/></label><label htmlFor="comparison-scenario">السيناريو<Select id="comparison-scenario" value={fields.scenario} onChange={event=>change(c=>({...c,scenario:event.target.value}))} required><option value="" disabled>اختر السيناريو</option>{Object.entries(scenarios).map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></label><label htmlFor="comparison-origin">مصدر الأرقام المتوقعة<Select id="comparison-origin" value={fields.origin} onChange={event=>change(c=>({...c,origin:event.target.value}))} required><option value="" disabled>اختر المصدر</option><option value="synthetic">حالة اصطناعية للاختبار فقط</option><option value="official">نتيجة من المصدر الرسمي</option></Select></label><label htmlFor="comparison-source">المرجع المحفوظ<Select id="comparison-source" value={fields.source_url} onChange={event=>change(c=>({...c,source_url:event.target.value}))}>{sources.map(source=><option key={source.url} value={source.url}>{source.title}</option>)}</Select></label><label htmlFor="comparison-reference">مرجع النتيجة أو رقمها<Input id="comparison-reference" value={fields.reference} onChange={event=>change(c=>({...c,reference:event.target.value}))} required minLength={3} maxLength={160}/></label><p className="field-hint">استخدم حالة مجهولة الهوية، دون أسماء موظفين أو بيانات شخصية. المطابقة الحسابية وحدها لا تعتمد القواعد.</p>
 <h3>مدخلات ضريبة الأجور</h3><div className="limit-fields">{amount('comparison-net','صافي الدخل التراكمي قبل الإعفاء الشخصي (ج.م.)',fields.tax.net,value=>change(c=>({...c,tax:{...c.tax,net:value}})))}{amount('comparison-duration','مدة الحساب التراكمية بالأيام',fields.tax.duration,value=>change(c=>({...c,tax:{...c.tax,duration:value}})))}{amount('comparison-prior','الضريبة المستحقة سابقًا (ج.م.)',fields.tax.prior_due,value=>change(c=>({...c,tax:{...c.tax,prior_due:value}})))}</div><p className="field-hint">صافي الدخل هنا بعد الاشتراكات القابلة للخصم وقبل الإعفاء الشخصي. أدخل المدة القانونية من حالة المقارنة؛ لا تُستنتج من دورة الراتب.</p><div className="limit-fields">{(['from','until'] as const).map(key=><label key={key} htmlFor={`comparison-${key}`}>{key==='from'?'بداية فترة الدخل':'نهاية فترة الدخل'}<Input id={`comparison-${key}`} type="date" required value={fields.tax[key]} onChange={event=>change(c=>({...c,tax:{...c.tax,[key]:event.target.value}}))}/></label>)}</div>
 <h3>أشهر الاشتراك التأميني في الحالة</h3>{fields.insurance.length===0&&<p>لا توجد أشهر اشتراك مدخلة. ستكون نتيجة التأمينات لهذه الحالة صفرًا.</p>}{fields.insurance.map((month,index)=><fieldset key={index}><legend>شهر الاشتراك {index+1}</legend><label htmlFor={`comparison-month-${index}`}>الشهر<Input id={`comparison-month-${index}`} type="month" required value={month.month.slice(0,7)} onChange={event=>change(c=>({...c,insurance:c.insurance.map((m,i)=>i===index?{...m,month:event.target.value?event.target.value+'-01':''}:m)}))}/></label>{amount(`comparison-wage-${index}`,'أجر الاشتراك (ج.م.)',month.wage,value=>change(c=>({...c,insurance:c.insurance.map((m,i)=>i===index?{...m,wage:value}:m)})))}<label htmlFor={`comparison-wage-reference-${index}`}>مرجع أجر الاشتراك<Input id={`comparison-wage-reference-${index}`} required minLength={3} maxLength={160} value={month.reference} onChange={event=>change(c=>({...c,insurance:c.insurance.map((m,i)=>i===index?{...m,reference:event.target.value}:m)}))}/></label><Button variant="ghost" type="button"  onClick={()=>change(c=>({...c,insurance:c.insurance.filter((_,i)=>i!==index)}))}>حذف شهر الاشتراك {index+1}</Button></fieldset>)}{fields.insurance.length<12&&<Button variant="ghost" type="button"  onClick={()=>change(c=>({...c,insurance:[...c.insurance,{month:'',wage:'',reference:''}]}))}>إضافة شهر اشتراك</Button>}
 <h3>الأرقام المتوقعة من مصدر المقارنة</h3>{Object.entries(outputs).map(([key,label])=><div key={key}>{amount(`comparison-expected-${key}`,label+' (ج.م.)',fields.expected[key],value=>change(c=>({...c,expected:{...c.expected,[key]:value}})),key==='tax_delta')}</div>)}</fieldset><p className="field-hint">الحفظ يحسب المقارنة ويسجّل نتيجتها لهذه النسخة فقط؛ لا يصدر حزمة ولا يجعلها صالحة للصرف.</p>{state.error&&<Message tone="bad" role="alert" >{state.error}</Message>}{state.saved&&!dirty&&!pending&&<Message tone="info" role="status" >{state.matched?'حُفظت المقارنة والأرقام متطابقة. القواعد ما زالت غير مؤهلة.':'حُفظت المقارنة مع اختلاف في الأرقام. راجع النتيجة قبل متابعة التأهيل.'}</Message>}{state.stale?<a className="primary-button" target="_blank" rel="noopener noreferrer" href={'/operator/statutory/comparisons?head='+encodeURIComponent(head)}>فتح نسخة المقارنة الحالية في نافذة جديدة</a>:<Button variant="solid" type="submit"  disabled={offline || (pending)} aria-describedby={showOfflineNotice ? offlineHintId : undefined}>{pending?'جارٍ حساب المقارنة…':state.uncertain?'استعادة نتيجة حفظ المقارنة':'حساب المقارنة وحفظ نتيجتها'}</Button>}{showOfflineNotice && <OfflineSubmissionNotice id={offlineHintId} purpose={state.uncertain ? "recovery" : "continuation"} />}</form></Disclosure>;
}
