// Presentation only. Full source-authoritative guidance remains in issueNames.
export const issueTitles: Record<string, string> = {
  payroll_deduction_source_allocation_required: 'مصادر الخصم تحتاج توزيعًا مراجعًا',
  payroll_carry_source_unfinalized: 'الفترة الأصلية للمتبقي لم تُثبّت',
  payroll_deduction_disposition_stale: 'مصدر الالتزام تغيّر',
  source_monthly_units_invalid: 'مصادر الأيام غير المدفوعة غير متوافقة',
  monthly_fixed30_unpaid_basis_required: 'أساس الأيام غير المدفوعة يحتاج حسمًا',
  payroll_deduction_capacity_disposition_required: 'الخصومات تتجاوز الحد المسموح',
  payroll_deduction_source_invalid: 'بيانات الخصم أو مرجعه ناقصة',
  payroll_deduction_approval_required: 'مصدر الخصم يحتاج اعتمادًا',
  payroll_deduction_refund_basis_required: 'تسوية ضريبية مستردة تؤثر على الحد المسموح للخصم',
  issued_labour_evidence_required: 'أدلة حدود الاستقطاع غير مؤهلة',
  insurance_month_scope_required: 'نطاق شهر التأمين يحتاج مراجعة',
  insurance_month_already_consumed: 'شهر التأمين محسوب في مسير نهائي',
  insurance_pack_missing_or_ambiguous: 'القاعدة التأمينية مفقودة أو متعارضة',
  advance_capacity_disposition_required: 'قسط السلفة يتجاوز حد الخصم أو صافي الأجر',
  advance_finance_disabled: 'السلف غير مفعّلة والالتزام قائم',
  advance_source_invalid: 'مصدر قسط السلفة غير صالح',
  financial_profile_composition_required: 'ربط المصادر المالية غير مكتمل',
  statutory_composition_scope_required: 'نطاق السنة وبيانات الحساب القانونية يحتاجان مراجعة',
  statutory_prior_balance_required: 'رصيد الضريبة السابق يحتاج استكمالًا',
  statutory_legal_duration_required: 'مدة الفترة الضريبية غير مكتملة',
  statutory_composition_context_mismatch: 'بيانات مدة الحساب لا تطابق الفترة',
  insurance_obligation_attribution_required: 'فترات الرواتب المسؤولة عن أشهر التأمين غير محددة',
  statutory_duration_outside_adapter: 'المدة خارج نطاق طريقة الحساب الحالية',
  statutory_composition_pack_missing_or_ambiguous: 'نسخة قواعد الضريبة مفقودة أو متعارضة',
  opening_tax_net_income_unknown: 'الدخل الخاضع السابق غير معلوم',
  prior_ytd_coverage_gap: 'تغطية الأرصدة السابقة ناقصة',
  prior_ytd_chain_inconsistent: 'الأرصدة السنوية السابقة لا تتطابق',
  opening_ytd_after_final_requires_review: 'الأرصدة الافتتاحية تتداخل مع حسابات مثبّتة',
  prior_statutory_context_unqualified: 'بيانات حساب سابق غير مؤهلة ضريبيًا',
  employee_statutory_context_missing: 'بيانات الضريبة والتأمينات ناقصة',
  employee_statutory_context_ambiguous: 'بيانات الضريبة والتأمينات متعارضة',
  opening_ytd_ambiguous: 'الأرصدة السابقة للسنة متعارضة',
  opening_tax_due_unknown: 'الضريبة المستحقة سابقًا غير معلومة',
  opening_tax_coverage_unknown: 'فترة تغطية الأرصدة السابقة غير معلومة',
  statutory_earning_attribution_required: 'توزيع الاستحقاق بين سنتين يحتاج مراجعة شروط الحساب',
  negative_statutory_balance: 'الحساب ينتج صافيًا سالبًا',
  source_capture_missing: 'نسخة مصادر الفترة غير مثبتة',
  source_scope_invalid: 'مصدر خارج نطاق الفترة أو التوظيف',
  source_duplicate_time: 'أكثر من سجل حضور لليوم نفسه',
  source_duplicate_leave: 'نسخة إجازة مكررة لليوم نفسه',
  source_quantity_unknown: 'كمية المصدر غير محددة',
  source_leave_overlap: 'إجازات متداخلة في اليوم نفسه',
  source_classification_stale: 'تصنيف الحضور يحتاج مصالحة',
  source_leave_binding_mismatch: 'الحضور لا يطابق الإجازة المعتمدة',
  source_mapping_uncertain: 'توزيع نصف يوم الإجازة غير متوافق',
  source_leave_treatment_unknown: 'المعالجة المالية للإجازة غير متاحة',
  source_choice_required: 'مصدر الأجر اليومي يحتاج اختيارًا معتمدًا',
  source_choice_pending: 'اختيار مصدر الأجر اليومي ينتظر الاعتماد',
  source_time_disabled: 'مصدر الحضور المحفوظ غير متاح',
  source_time_coverage_unqualified: 'الاحتساب المالي للحضور والإجازات غير مؤهل',
  recurring_interpretation_changed: 'طريقة حساب البند المتكرر تغيّرت',
  policy_coverage_gap: 'سياسة الرواتب لا تغطي كل الفترة',
  calendar_history_unverified: 'سجل الدورة لا يكفي لتحديد الاستحقاق',
  calendar_historical_correction_required: 'الفترة المحفوظة تحتاج مسار تصحيح',
  advance_caps_unqualified: 'حد خصم السلفة غير مؤهل قانونيًا',
  advance_allowance_stale: 'رصيد السلفة أو أساس الخصم تغيّر',
  advance_carry_forward_required: 'متبقي السلفة يحتاج معالجة معتمدة',
  advance_employment_unavailable: 'قسط مستحق لتوظيف خارج حساب الفترة',
  policy_missing: 'سياسة الجزء من الفترة غير محددة',
  statutory_pack_unqualified: 'الحساب المالي للفترة غير مؤهل',
  statutory_adapter_unqualified: 'طريقة الحساب لم تجتز التحقق من الشروط القانونية',
  time_integration_pending: 'دمج الحضور غير مؤهل بعد',
  leave_integration_pending: 'دمج الإجازات غير مؤهل بعد',
  correction_open: 'طلب تصحيح مفتوح للفترة',
  no_eligible_employees: 'لا توجد علاقات توظيف مؤهلة',
  compensation_gap: 'الأجر لا يغطي كل أيام الفترة',
  assignment_gap: 'بيانات العمل لا تغطي كل الفترة',
  manual_units_ambiguous: 'مدخلات الوحدات اليومية متعارضة',
  approved_units_missing: 'وحدات الأجر اليومي غير معتمدة',
  daily_units_allocation_needed: 'الوحدات تحتاج توزيعًا على تواريخ الأجر',
  units_exceed_eligibility: 'الوحدات تتجاوز أيام التوظيف المؤهلة',
  recurring_overlap: 'بنود الموظف المتكررة متداخلة',
  daily_percentage_allocation_needed: 'الوحدات تحتاج توزيعًا وفق تغيّر البند',
  component_full_period_change: 'قيمة البند أو تجزئته تغيّرت داخل الفترة',
  component_behavior_changed: 'نوع البند أو طريقة حسابه تغيّرت',
  adjustment_component_changed: 'بند المدخل المالي غير صالح للفترة',
  negative_operational_balance: 'الخصومات تتجاوز الاستحقاقات المعروفة',
  opening_ytd_unknown: 'الأرصدة الافتتاحية لم تُراجع',
};
