-- Cube 3 Slice 2: effective Leave calendars, explicit periods, types and audited balances.
CREATE SCHEMA leave;
REVOKE ALL ON SCHEMA leave FROM PUBLIC,anon,authenticated,service_role;
CREATE EXTENSION IF NOT EXISTS btree_gist WITH SCHEMA extensions;

CREATE TABLE leave.calendars(tenant_id uuid NOT NULL REFERENCES platform_core.tenants(id) ON DELETE RESTRICT,id uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid(),employer_entity_id uuid NOT NULL,code text NOT NULL,name text NOT NULL,is_active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,id,employer_entity_id),UNIQUE(tenant_id,employer_entity_id,code),FOREIGN KEY(tenant_id,employer_entity_id) REFERENCES platform_core.tenant_legal_entities(tenant_id,id) ON DELETE RESTRICT);
CREATE TABLE leave.calendar_versions(tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid(),calendar_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),effective_from date NOT NULL,effective_until date,timezone text NOT NULL DEFAULT 'Africa/Cairo',source text NOT NULL,reason text NOT NULL,created_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,calendar_id,version),FOREIGN KEY(tenant_id,calendar_id) REFERENCES leave.calendars(tenant_id,id) ON DELETE RESTRICT,CHECK(effective_until IS NULL OR effective_until>effective_from),EXCLUDE USING gist(tenant_id WITH =,calendar_id WITH =,daterange(effective_from,effective_until,'[)') WITH &&));
CREATE TABLE leave.calendar_rest_days(tenant_id uuid NOT NULL,calendar_version_id uuid NOT NULL,weekday smallint NOT NULL CHECK(weekday BETWEEN 0 AND 6),PRIMARY KEY(tenant_id,calendar_version_id,weekday),FOREIGN KEY(tenant_id,calendar_version_id) REFERENCES leave.calendar_versions(tenant_id,id) ON DELETE RESTRICT);
CREATE TABLE leave.calendar_holidays(tenant_id uuid NOT NULL,calendar_version_id uuid NOT NULL,holiday_date date NOT NULL,name text NOT NULL,source text NOT NULL,PRIMARY KEY(tenant_id,calendar_version_id,holiday_date),FOREIGN KEY(tenant_id,calendar_version_id) REFERENCES leave.calendar_versions(tenant_id,id) ON DELETE RESTRICT);
CREATE TABLE leave.year_periods(tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid(),employer_entity_id uuid NOT NULL,calendar_id uuid NOT NULL,starts_on date NOT NULL,ends_on date NOT NULL,label text NOT NULL,created_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,id,employer_entity_id),UNIQUE(tenant_id,employer_entity_id,starts_on,ends_on),FOREIGN KEY(tenant_id,employer_entity_id) REFERENCES platform_core.tenant_legal_entities(tenant_id,id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,calendar_id,employer_entity_id) REFERENCES leave.calendars(tenant_id,id,employer_entity_id) ON DELETE RESTRICT,CHECK(ends_on>=starts_on),EXCLUDE USING gist(tenant_id WITH =,employer_entity_id WITH =,daterange(starts_on,ends_on+1,'[)') WITH &&));
CREATE TABLE leave.types(tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid(),employer_entity_id uuid NOT NULL,code text NOT NULL,name text NOT NULL,PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,id,employer_entity_id),UNIQUE(tenant_id,employer_entity_id,code),FOREIGN KEY(tenant_id,employer_entity_id) REFERENCES platform_core.tenant_legal_entities(tenant_id,id) ON DELETE RESTRICT);
CREATE TABLE leave.type_versions(tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid(),leave_type_id uuid NOT NULL,version integer NOT NULL CHECK(version>0),effective_from date NOT NULL,effective_until date,pay_effect text NOT NULL CHECK(pay_effect IN('paid','unpaid')),balance_mode text NOT NULL CHECK(balance_mode IN('tracked','untracked')),day_count_basis text NOT NULL DEFAULT 'working_days' CHECK(day_count_basis IN('working_days','calendar_days')),half_day_allowed boolean NOT NULL DEFAULT false,source text NOT NULL,reason text NOT NULL,created_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,leave_type_id,version),UNIQUE(tenant_id,id,leave_type_id),FOREIGN KEY(tenant_id,leave_type_id) REFERENCES leave.types(tenant_id,id) ON DELETE RESTRICT,CHECK(effective_until IS NULL OR effective_until>effective_from),EXCLUDE USING gist(tenant_id WITH =,leave_type_id WITH =,daterange(effective_from,effective_until,'[)') WITH &&));
CREATE TABLE leave.accounts(tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid(),employer_entity_id uuid NOT NULL,employee_id uuid NOT NULL,leave_type_id uuid NOT NULL,year_period_id uuid NOT NULL,created_by uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,id),UNIQUE(tenant_id,employer_entity_id,employee_id,leave_type_id,year_period_id),UNIQUE(tenant_id,id,leave_type_id),FOREIGN KEY(tenant_id,employer_entity_id) REFERENCES platform_core.tenant_legal_entities(tenant_id,id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,employee_id) REFERENCES people.employees(tenant_id,id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,leave_type_id,employer_entity_id) REFERENCES leave.types(tenant_id,id,employer_entity_id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,year_period_id,employer_entity_id) REFERENCES leave.year_periods(tenant_id,id,employer_entity_id) ON DELETE RESTRICT);
CREATE INDEX leave_accounts_employee_page ON leave.accounts(tenant_id,employee_id,year_period_id,leave_type_id,id);
CREATE INDEX leave_accounts_tenant_page ON leave.accounts(tenant_id,year_period_id,employee_id,leave_type_id,id);
CREATE TABLE leave.ledger_entries(tenant_id uuid NOT NULL,id uuid NOT NULL DEFAULT pg_catalog.gen_random_uuid(),account_id uuid NOT NULL,leave_type_id uuid NOT NULL,entry_kind text NOT NULL CHECK(entry_kind IN('opening','annual_grant','adjustment')),delta_days numeric(8,2) NOT NULL CHECK(delta_days<>0 AND (entry_kind='adjustment' OR delta_days>0)),source_version_id uuid,source_reference text NOT NULL,idempotency_key text NOT NULL,reason text NOT NULL,actor_user_id uuid NOT NULL REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(tenant_id,id),FOREIGN KEY(tenant_id,account_id,leave_type_id) REFERENCES leave.accounts(tenant_id,id,leave_type_id) ON DELETE RESTRICT,FOREIGN KEY(tenant_id,source_version_id,leave_type_id) REFERENCES leave.type_versions(tenant_id,id,leave_type_id) ON DELETE RESTRICT,UNIQUE(tenant_id,account_id,idempotency_key));
CREATE UNIQUE INDEX leave_ledger_one_opening ON leave.ledger_entries(tenant_id,account_id) WHERE entry_kind='opening';
CREATE UNIQUE INDEX leave_ledger_one_annual_grant ON leave.ledger_entries(tenant_id,account_id) WHERE entry_kind='annual_grant';
CREATE INDEX leave_ledger_account_created ON leave.ledger_entries(tenant_id,account_id,created_at,id);
CREATE TABLE leave.config_audit_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,tenant_id uuid NOT NULL REFERENCES platform_core.tenants(id) ON DELETE RESTRICT,employer_entity_id uuid NOT NULL,object_kind text NOT NULL CHECK(object_kind IN('calendar_version','year_period','leave_type_version')),object_id uuid NOT NULL,action text NOT NULL CHECK(action IN('created','superseded')),actor_user_id uuid NOT NULL REFERENCES auth.users(id),reason text NOT NULL,details jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(tenant_id,employer_entity_id) REFERENCES platform_core.tenant_legal_entities(tenant_id,id) ON DELETE RESTRICT);
ALTER TABLE leave.config_audit_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON leave.config_audit_events FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON SEQUENCE leave.config_audit_events_id_seq FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION leave.reject_ledger_mutation() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $f$ BEGIN RAISE EXCEPTION 'leave_ledger_append_only' USING ERRCODE='55000'; END $f$;
CREATE TRIGGER leave_ledger_append_only BEFORE UPDATE OR DELETE ON leave.ledger_entries FOR EACH ROW EXECUTE FUNCTION leave.reject_ledger_mutation();
CREATE FUNCTION leave.reject_snapshot_mutation() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $f$ BEGIN RAISE EXCEPTION 'leave_snapshot_immutable' USING ERRCODE='55000'; END $f$;
CREATE TRIGGER leave_config_audit_append_only BEFORE UPDATE OR DELETE ON leave.config_audit_events FOR EACH ROW EXECUTE FUNCTION leave.reject_snapshot_mutation();
CREATE FUNCTION leave.guard_effective_revision() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $f$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'leave_snapshot_immutable' USING ERRCODE='55000'; END IF;
 IF (to_jsonb(NEW)-'effective_until') IS DISTINCT FROM (to_jsonb(OLD)-'effective_until') OR OLD.effective_until IS NOT NULL OR NEW.effective_until IS NULL OR NEW.effective_until<=((now() AT TIME ZONE 'Africa/Cairo')::date) THEN RAISE EXCEPTION 'leave_snapshot_immutable' USING ERRCODE='55000'; END IF;
 RETURN NEW; END $f$;
CREATE TRIGGER leave_calendar_version_immutable BEFORE DELETE ON leave.calendar_versions FOR EACH ROW EXECUTE FUNCTION leave.reject_snapshot_mutation();
CREATE TRIGGER leave_calendar_version_revision_guard BEFORE UPDATE ON leave.calendar_versions FOR EACH ROW EXECUTE FUNCTION leave.guard_effective_revision();
CREATE TRIGGER leave_calendar_rest_immutable BEFORE UPDATE OR DELETE ON leave.calendar_rest_days FOR EACH ROW EXECUTE FUNCTION leave.reject_snapshot_mutation();
CREATE TRIGGER leave_calendar_holiday_immutable BEFORE UPDATE OR DELETE ON leave.calendar_holidays FOR EACH ROW EXECUTE FUNCTION leave.reject_snapshot_mutation();
CREATE TRIGGER leave_year_period_immutable BEFORE UPDATE OR DELETE ON leave.year_periods FOR EACH ROW EXECUTE FUNCTION leave.reject_snapshot_mutation();
CREATE TRIGGER leave_type_version_immutable BEFORE DELETE ON leave.type_versions FOR EACH ROW EXECUTE FUNCTION leave.reject_snapshot_mutation();
CREATE TRIGGER leave_type_version_revision_guard BEFORE UPDATE ON leave.type_versions FOR EACH ROW EXECUTE FUNCTION leave.guard_effective_revision();
CREATE TRIGGER leave_account_immutable BEFORE UPDATE OR DELETE ON leave.accounts FOR EACH ROW EXECUTE FUNCTION leave.reject_snapshot_mutation();

DO $f$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['calendars','calendar_versions','calendar_rest_days','calendar_holidays','year_periods','types','type_versions','accounts','ledger_entries'] LOOP EXECUTE format('ALTER TABLE leave.%I ENABLE ROW LEVEL SECURITY',t); EXECUTE format('REVOKE ALL ON leave.%I FROM PUBLIC,anon,authenticated,service_role',t); END LOOP; END $f$;
REVOKE ALL ON FUNCTION leave.reject_ledger_mutation() FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION leave.reject_snapshot_mutation() FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION leave.guard_effective_revision() FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION leave.authorized(p_tenant uuid,p_permission text,p_new_work boolean DEFAULT true) RETURNS uuid LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=auth.uid(); BEGIN
 IF a IS NULL OR NOT platform_private.has_tenant_permission(p_tenant,a,p_permission)
 OR NOT EXISTS(SELECT 1 FROM platform_core.tenants t JOIN platform_core.tenant_memberships m ON m.tenant_id=t.id JOIN auth.users u ON u.id=m.user_id WHERE t.id=p_tenant AND t.lifecycle_state='active' AND m.user_id=a AND m.access_state='active' AND u.deleted_at IS NULL AND u.email_confirmed_at IS NOT NULL AND (u.banned_until IS NULL OR u.banned_until<=now())) THEN RAISE EXCEPTION 'leave_forbidden' USING ERRCODE='42501'; END IF;
 IF p_new_work AND (NOT platform_private.tenant_capability_is_enabled(p_tenant,'hr.people',now()) OR NOT platform_private.tenant_capability_is_enabled(p_tenant,'hr.leave',now())) THEN RAISE EXCEPTION 'leave_new_work_disabled' USING ERRCODE='55000'; END IF; RETURN a; END $f$;
REVOKE ALL ON FUNCTION leave.authorized(uuid,text,boolean) FROM PUBLIC,anon,authenticated,service_role;

CREATE FUNCTION public.leave_create_calendar(p_tenant uuid,p_employer uuid,p_code text,p_name text,p_effective_from date,p_effective_until date,p_rest_days smallint[],p_holidays jsonb,p_source text,p_reason text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=leave.authorized(p_tenant,'leave.manage',true); c uuid; v uuid; entity_active boolean; BEGIN
 IF nullif(btrim(p_code),'') IS NULL OR length(btrim(p_code))>60 OR nullif(btrim(p_name),'') IS NULL OR length(btrim(p_name))>160 OR nullif(btrim(p_source),'') IS NULL OR length(btrim(p_source))>300 OR nullif(btrim(p_reason),'') IS NULL OR length(btrim(p_reason))>500 OR p_effective_from IS NULL OR (p_effective_until IS NOT NULL AND p_effective_until<=p_effective_from) OR p_rest_days IS NULL OR cardinality(p_rest_days)>7 OR array_position(p_rest_days,NULL) IS NOT NULL OR EXISTS(SELECT 1 FROM unnest(p_rest_days) d WHERE d<0 OR d>6) OR p_holidays IS NULL OR jsonb_typeof(p_holidays)<>'array' OR jsonb_array_length(p_holidays)>400 OR EXISTS(SELECT 1 FROM jsonb_array_elements(p_holidays) h WHERE jsonb_typeof(h)<>'object' OR nullif(btrim(h->>'date'),'') IS NULL OR nullif(btrim(h->>'name'),'') IS NULL OR (h->>'date')::date<p_effective_from OR (p_effective_until IS NOT NULL AND (h->>'date')::date>=p_effective_until)) THEN RAISE EXCEPTION 'leave_calendar_input_invalid' USING ERRCODE='22023'; END IF;
 IF NOT EXISTS(SELECT 1 FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=p_employer AND is_active) THEN RAISE EXCEPTION 'leave_employer_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text||p_employer::text||p_code,90427)); PERFORM leave.authorized(p_tenant,'leave.manage',true);
 SELECT is_active INTO entity_active FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=p_employer FOR UPDATE;
 IF NOT coalesce(entity_active,false) THEN RAISE EXCEPTION 'leave_employer_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM leave.authorized(p_tenant,'leave.manage',true);
 INSERT INTO leave.calendars(tenant_id,employer_entity_id,code,name) VALUES(p_tenant,p_employer,btrim(p_code),btrim(p_name)) RETURNING id INTO c;
 INSERT INTO leave.calendar_versions(tenant_id,calendar_id,version,effective_from,effective_until,source,reason,created_by) VALUES(p_tenant,c,1,p_effective_from,p_effective_until,btrim(p_source),btrim(p_reason),a) RETURNING id INTO v;
 INSERT INTO leave.calendar_rest_days SELECT p_tenant,v,x FROM unnest(coalesce(p_rest_days,'{}'::smallint[])) x ON CONFLICT DO NOTHING;
 INSERT INTO leave.calendar_holidays(tenant_id,calendar_version_id,holiday_date,name,source) SELECT p_tenant,v,(x->>'date')::date,x->>'name',btrim(p_source) FROM jsonb_array_elements(p_holidays) x;
 INSERT INTO leave.config_audit_events(tenant_id,employer_entity_id,object_kind,object_id,action,actor_user_id,reason,details) VALUES(p_tenant,p_employer,'calendar_version',v,'created',a,btrim(p_reason),jsonb_build_object('calendar_id',c,'version',1,'effective_from',p_effective_from,'effective_until',p_effective_until));
 RETURN c; END $f$;
REVOKE ALL ON FUNCTION public.leave_create_calendar(uuid,uuid,text,text,date,date,smallint[],jsonb,text,text) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_create_calendar(uuid,uuid,text,text,date,date,smallint[],jsonb,text,text) TO authenticated;

CREATE FUNCTION public.leave_revise_calendar(p_tenant uuid,p_calendar uuid,p_effective_from date,p_effective_until date,p_rest_days smallint[],p_holidays jsonb,p_source text,p_reason text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=leave.authorized(p_tenant,'leave.manage',true); old leave.calendar_versions%ROWTYPE; v uuid; employer uuid; entity_active boolean; BEGIN
 IF p_effective_from IS NULL OR p_effective_from<=((now() AT TIME ZONE 'Africa/Cairo')::date) OR (p_effective_until IS NOT NULL AND p_effective_until<=p_effective_from) OR p_rest_days IS NULL OR cardinality(p_rest_days)>7 OR array_position(p_rest_days,NULL) IS NOT NULL OR EXISTS(SELECT 1 FROM unnest(p_rest_days) d WHERE d<0 OR d>6) OR p_holidays IS NULL OR jsonb_typeof(p_holidays)<>'array' OR jsonb_array_length(p_holidays)>400 OR EXISTS(SELECT 1 FROM jsonb_array_elements(p_holidays) h WHERE jsonb_typeof(h)<>'object' OR nullif(btrim(h->>'date'),'') IS NULL OR nullif(btrim(h->>'name'),'') IS NULL OR (h->>'date')::date<p_effective_from OR (p_effective_until IS NOT NULL AND (h->>'date')::date>=p_effective_until)) OR nullif(btrim(p_source),'') IS NULL OR length(btrim(p_source))>300 OR nullif(btrim(p_reason),'') IS NULL OR length(btrim(p_reason))>500 THEN RAISE EXCEPTION 'leave_calendar_input_invalid' USING ERRCODE='22023'; END IF;
 SELECT c.employer_entity_id INTO employer FROM leave.calendars c WHERE c.tenant_id=p_tenant AND c.id=p_calendar FOR UPDATE;
 IF employer IS NULL THEN RAISE EXCEPTION 'leave_calendar_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text||p_calendar::text,90427)); PERFORM leave.authorized(p_tenant,'leave.manage',true);
 SELECT is_active INTO entity_active FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=employer FOR UPDATE;
 IF NOT coalesce(entity_active,false) THEN RAISE EXCEPTION 'leave_employer_unavailable' USING ERRCODE='23503'; END IF;
 SELECT * INTO old FROM leave.calendar_versions WHERE tenant_id=p_tenant AND calendar_id=p_calendar AND effective_until IS NULL ORDER BY version DESC LIMIT 1 FOR UPDATE;
 IF NOT FOUND OR p_effective_from<=old.effective_from THEN RAISE EXCEPTION 'leave_calendar_revision_invalid' USING ERRCODE='23P01'; END IF;
 PERFORM leave.authorized(p_tenant,'leave.manage',true);
 UPDATE leave.calendar_versions SET effective_until=p_effective_from WHERE tenant_id=p_tenant AND id=old.id;
 INSERT INTO leave.calendar_versions(tenant_id,calendar_id,version,effective_from,effective_until,timezone,source,reason,created_by) VALUES(p_tenant,p_calendar,old.version+1,p_effective_from,p_effective_until,old.timezone,btrim(p_source),btrim(p_reason),a) RETURNING id INTO v;
 INSERT INTO leave.calendar_rest_days SELECT p_tenant,v,x FROM unnest(p_rest_days) x;
 INSERT INTO leave.calendar_holidays(tenant_id,calendar_version_id,holiday_date,name,source) SELECT p_tenant,v,(x->>'date')::date,x->>'name',btrim(p_source) FROM jsonb_array_elements(p_holidays) x;
 INSERT INTO leave.config_audit_events(tenant_id,employer_entity_id,object_kind,object_id,action,actor_user_id,reason,details) VALUES(p_tenant,employer,'calendar_version',old.id,'superseded',a,btrim(p_reason),jsonb_build_object('superseded_by',v,'effective_from',p_effective_from));
 INSERT INTO leave.config_audit_events(tenant_id,employer_entity_id,object_kind,object_id,action,actor_user_id,reason,details) VALUES(p_tenant,employer,'calendar_version',v,'created',a,btrim(p_reason),jsonb_build_object('calendar_id',p_calendar,'version',old.version+1,'effective_from',p_effective_from,'effective_until',p_effective_until)); RETURN v; END $f$;
REVOKE ALL ON FUNCTION public.leave_revise_calendar(uuid,uuid,date,date,smallint[],jsonb,text,text) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_revise_calendar(uuid,uuid,date,date,smallint[],jsonb,text,text) TO authenticated;

CREATE FUNCTION public.leave_create_year_period(p_tenant uuid,p_employer uuid,p_calendar uuid,p_starts date,p_ends date,p_label text,p_reason text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=leave.authorized(p_tenant,'leave.manage',true); out_id uuid; entity_active boolean; calendar_active boolean; BEGIN
 IF p_starts IS NULL OR p_ends<p_starts OR nullif(btrim(p_label),'') IS NULL OR length(btrim(p_label))>120 OR nullif(btrim(p_reason),'') IS NULL OR length(btrim(p_reason))>500 OR NOT EXISTS(SELECT 1 FROM leave.calendars c WHERE c.tenant_id=p_tenant AND c.id=p_calendar AND c.employer_entity_id=p_employer) OR NOT coalesce((SELECT range_agg(daterange(v.effective_from,v.effective_until,'[)')) @> daterange(p_starts,p_ends+1,'[)') FROM leave.calendar_versions v WHERE v.tenant_id=p_tenant AND v.calendar_id=p_calendar),false) THEN RAISE EXCEPTION 'leave_year_period_invalid' USING ERRCODE='22023'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text||p_employer::text,90428)); PERFORM leave.authorized(p_tenant,'leave.manage',true);
 SELECT is_active INTO entity_active FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=p_employer FOR UPDATE;
 SELECT is_active INTO calendar_active FROM leave.calendars WHERE tenant_id=p_tenant AND id=p_calendar FOR UPDATE;
 IF NOT coalesce(entity_active,false) OR NOT coalesce(calendar_active,false) THEN RAISE EXCEPTION 'leave_employer_or_calendar_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM leave.authorized(p_tenant,'leave.manage',true);
 INSERT INTO leave.year_periods(tenant_id,employer_entity_id,calendar_id,starts_on,ends_on,label,created_by) VALUES(p_tenant,p_employer,p_calendar,p_starts,p_ends,btrim(p_label),a) RETURNING id INTO out_id;
 INSERT INTO leave.config_audit_events(tenant_id,employer_entity_id,object_kind,object_id,action,actor_user_id,reason,details) VALUES(p_tenant,p_employer,'year_period',out_id,'created',a,btrim(p_reason),jsonb_build_object('calendar_id',p_calendar,'starts_on',p_starts,'ends_on',p_ends,'label',btrim(p_label))); RETURN out_id; END $f$;
REVOKE ALL ON FUNCTION public.leave_create_year_period(uuid,uuid,uuid,date,date,text,text) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_create_year_period(uuid,uuid,uuid,date,date,text,text) TO authenticated;

CREATE FUNCTION leave.calendar_day_snapshot(p_tenant uuid,p_calendar uuid,p_day date) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS $f$
 SELECT CASE WHEN v.id IS NULL THEN NULL ELSE jsonb_build_object('calendar_version_id',v.id,'is_weekly_rest',EXISTS(SELECT 1 FROM leave.calendar_rest_days r WHERE r.tenant_id=v.tenant_id AND r.calendar_version_id=v.id AND r.weekday=extract(dow FROM p_day)::smallint),'holiday',h.name,'holiday_source',h.source,'effective_from',v.effective_from,'effective_until',v.effective_until) END
 FROM (SELECT 1) x LEFT JOIN LATERAL (SELECT cv.* FROM leave.calendar_versions cv WHERE cv.tenant_id=p_tenant AND cv.calendar_id=p_calendar AND cv.effective_from<=p_day AND (cv.effective_until IS NULL OR cv.effective_until>p_day) ORDER BY cv.effective_from DESC LIMIT 1) v ON true
 LEFT JOIN leave.calendar_holidays h ON h.tenant_id=v.tenant_id AND h.calendar_version_id=v.id AND h.holiday_date=p_day
$f$;
REVOKE ALL ON FUNCTION leave.calendar_day_snapshot(uuid,uuid,date) FROM PUBLIC,anon,authenticated,service_role;
CREATE FUNCTION public.leave_calendar_day(p_tenant uuid,p_calendar uuid,p_day date) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $f$
BEGIN PERFORM leave.authorized(p_tenant,'leave.view',false); IF p_day IS NULL OR NOT EXISTS(SELECT 1 FROM leave.calendars WHERE tenant_id=p_tenant AND id=p_calendar) THEN RAISE EXCEPTION 'leave_calendar_day_unavailable' USING ERRCODE='P0002'; END IF; RETURN leave.calendar_day_snapshot(p_tenant,p_calendar,p_day); END $f$;
REVOKE ALL ON FUNCTION public.leave_calendar_day(uuid,uuid,date) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_calendar_day(uuid,uuid,date) TO authenticated;

CREATE FUNCTION public.leave_create_type(p_tenant uuid,p_employer uuid,p_code text,p_name text,p_effective_from date,p_pay_effect text,p_balance_mode text,p_half boolean,p_source text,p_reason text,p_day_count_basis text DEFAULT 'working_days') RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=leave.authorized(p_tenant,'leave.manage',true); x uuid; BEGIN
 IF nullif(btrim(p_code),'') IS NULL OR length(btrim(p_code))>60 OR nullif(btrim(p_name),'') IS NULL OR length(btrim(p_name))>160 OR p_pay_effect IS NULL OR p_pay_effect NOT IN('paid','unpaid') OR p_balance_mode IS NULL OR p_balance_mode NOT IN('tracked','untracked') OR p_day_count_basis IS NULL OR p_day_count_basis NOT IN('working_days','calendar_days') OR p_half IS NULL OR p_effective_from IS NULL OR nullif(btrim(p_source),'') IS NULL OR length(btrim(p_source))>300 OR nullif(btrim(p_reason),'') IS NULL OR length(btrim(p_reason))>500 THEN RAISE EXCEPTION 'leave_type_input_invalid' USING ERRCODE='22023'; END IF;
 IF NOT EXISTS(SELECT 1 FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=p_employer AND is_active) THEN RAISE EXCEPTION 'leave_employer_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text||p_employer::text||btrim(p_code),90431)); PERFORM leave.authorized(p_tenant,'leave.manage',true);
 PERFORM 1 FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=p_employer AND is_active FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'leave_employer_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM leave.authorized(p_tenant,'leave.manage',true);
 INSERT INTO leave.types(tenant_id,employer_entity_id,code,name) VALUES(p_tenant,p_employer,btrim(p_code),btrim(p_name)) RETURNING id INTO x;
 INSERT INTO leave.type_versions(tenant_id,leave_type_id,version,effective_from,pay_effect,balance_mode,day_count_basis,half_day_allowed,source,reason,created_by) VALUES(p_tenant,x,1,p_effective_from,p_pay_effect,p_balance_mode,p_day_count_basis,p_half,btrim(p_source),btrim(p_reason),a);
 INSERT INTO leave.config_audit_events(tenant_id,employer_entity_id,object_kind,object_id,action,actor_user_id,reason,details) SELECT p_tenant,p_employer,'leave_type_version',id,'created',a,btrim(p_reason),jsonb_build_object('leave_type_id',x,'version',1,'effective_from',p_effective_from,'pay_effect',p_pay_effect,'balance_mode',p_balance_mode,'day_count_basis',p_day_count_basis) FROM leave.type_versions WHERE tenant_id=p_tenant AND leave_type_id=x AND version=1; RETURN x; END $f$;
REVOKE ALL ON FUNCTION public.leave_create_type(uuid,uuid,text,text,date,text,text,boolean,text,text,text) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_create_type(uuid,uuid,text,text,date,text,text,boolean,text,text,text) TO authenticated;

CREATE FUNCTION public.leave_revise_type(p_tenant uuid,p_type uuid,p_effective_from date,p_pay_effect text,p_balance_mode text,p_day_count_basis text,p_half boolean,p_source text,p_reason text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=leave.authorized(p_tenant,'leave.manage',true); old leave.type_versions%ROWTYPE; employer uuid; v uuid; entity_active boolean; BEGIN
 IF p_effective_from IS NULL OR p_effective_from<=((now() AT TIME ZONE 'Africa/Cairo')::date) OR p_pay_effect IS NULL OR p_pay_effect NOT IN('paid','unpaid') OR p_balance_mode IS NULL OR p_balance_mode NOT IN('tracked','untracked') OR p_day_count_basis IS NULL OR p_day_count_basis NOT IN('working_days','calendar_days') OR p_half IS NULL OR nullif(btrim(p_source),'') IS NULL OR length(btrim(p_source))>300 OR nullif(btrim(p_reason),'') IS NULL OR length(btrim(p_reason))>500 THEN RAISE EXCEPTION 'leave_type_input_invalid' USING ERRCODE='22023'; END IF;
 SELECT t.employer_entity_id INTO employer FROM leave.types t WHERE t.tenant_id=p_tenant AND t.id=p_type FOR UPDATE;
 IF employer IS NULL THEN RAISE EXCEPTION 'leave_type_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text||p_type::text,90430)); PERFORM leave.authorized(p_tenant,'leave.manage',true);
 SELECT is_active INTO entity_active FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=employer FOR UPDATE;
 IF NOT coalesce(entity_active,false) THEN RAISE EXCEPTION 'leave_employer_unavailable' USING ERRCODE='23503'; END IF;
 SELECT * INTO old FROM leave.type_versions WHERE tenant_id=p_tenant AND leave_type_id=p_type AND effective_until IS NULL ORDER BY version DESC LIMIT 1 FOR UPDATE;
 IF NOT FOUND OR p_effective_from<=old.effective_from THEN RAISE EXCEPTION 'leave_type_revision_invalid' USING ERRCODE='23P01'; END IF;
 PERFORM leave.authorized(p_tenant,'leave.manage',true);
 UPDATE leave.type_versions SET effective_until=p_effective_from WHERE tenant_id=p_tenant AND id=old.id;
 INSERT INTO leave.type_versions(tenant_id,leave_type_id,version,effective_from,pay_effect,balance_mode,day_count_basis,half_day_allowed,source,reason,created_by) VALUES(p_tenant,p_type,old.version+1,p_effective_from,p_pay_effect,p_balance_mode,p_day_count_basis,p_half,btrim(p_source),btrim(p_reason),a) RETURNING id INTO v;
 INSERT INTO leave.config_audit_events(tenant_id,employer_entity_id,object_kind,object_id,action,actor_user_id,reason,details) VALUES(p_tenant,employer,'leave_type_version',old.id,'superseded',a,btrim(p_reason),jsonb_build_object('superseded_by',v,'effective_from',p_effective_from));
 INSERT INTO leave.config_audit_events(tenant_id,employer_entity_id,object_kind,object_id,action,actor_user_id,reason,details) VALUES(p_tenant,employer,'leave_type_version',v,'created',a,btrim(p_reason),jsonb_build_object('leave_type_id',p_type,'version',old.version+1,'effective_from',p_effective_from,'pay_effect',p_pay_effect,'balance_mode',p_balance_mode,'day_count_basis',p_day_count_basis)); RETURN v; END $f$;
REVOKE ALL ON FUNCTION public.leave_revise_type(uuid,uuid,date,text,text,text,boolean,text,text) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_revise_type(uuid,uuid,date,text,text,text,boolean,text,text) TO authenticated;

CREATE FUNCTION public.leave_configuration_snapshot(p_tenant uuid,p_employer uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $f$
DECLARE out_cal jsonb; out_types jsonb; out_periods jsonb; BEGIN
 PERFORM leave.authorized(p_tenant,'leave.view',false);
 SELECT coalesce(jsonb_agg(jsonb_build_object('calendar_id',c.id,'code',c.code,'name',c.name,'versions',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',v.id,'version',v.version,'effective_from',v.effective_from,'effective_until',v.effective_until,'timezone',v.timezone,'source',v.source,'rest_weekdays',(SELECT coalesce(jsonb_agg(r.weekday ORDER BY r.weekday),'[]'::jsonb) FROM leave.calendar_rest_days r WHERE r.tenant_id=v.tenant_id AND r.calendar_version_id=v.id),'holidays',(SELECT coalesce(jsonb_agg(jsonb_build_object('date',h.holiday_date,'name',h.name,'source',h.source) ORDER BY h.holiday_date),'[]'::jsonb) FROM leave.calendar_holidays h WHERE h.tenant_id=v.tenant_id AND h.calendar_version_id=v.id)) ORDER BY v.version DESC),'[]'::jsonb) FROM leave.calendar_versions v WHERE v.tenant_id=c.tenant_id AND v.calendar_id=c.id)) ORDER BY c.code),'[]'::jsonb) INTO out_cal FROM leave.calendars c WHERE c.tenant_id=p_tenant AND c.employer_entity_id=p_employer;
 SELECT coalesce(jsonb_agg(jsonb_build_object('id',t.id,'code',t.code,'name',t.name,'versions',(SELECT coalesce(jsonb_agg(jsonb_build_object('id',v.id,'version',v.version,'effective_from',v.effective_from,'effective_until',v.effective_until,'pay_effect',v.pay_effect,'balance_mode',v.balance_mode,'day_count_basis',v.day_count_basis,'half_day_allowed',v.half_day_allowed,'source',v.source) ORDER BY v.version DESC),'[]'::jsonb) FROM leave.type_versions v WHERE v.tenant_id=t.tenant_id AND v.leave_type_id=t.id)) ORDER BY t.code),'[]'::jsonb) INTO out_types FROM leave.types t WHERE t.tenant_id=p_tenant AND t.employer_entity_id=p_employer;
 SELECT coalesce(jsonb_agg(jsonb_build_object('id',id,'calendar_id',calendar_id,'starts_on',starts_on,'ends_on',ends_on,'label',label) ORDER BY starts_on,id),'[]'::jsonb) INTO out_periods FROM leave.year_periods WHERE tenant_id=p_tenant AND employer_entity_id=p_employer;
 RETURN jsonb_build_object('calendars',out_cal,'types',out_types,'year_periods',out_periods); END $f$;
REVOKE ALL ON FUNCTION public.leave_configuration_snapshot(uuid,uuid) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_configuration_snapshot(uuid,uuid) TO authenticated;

CREATE FUNCTION public.leave_access_snapshot(p_tenant uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=auth.uid(); can_view boolean; can_manage boolean; can_approve boolean; can_adjust boolean; self_access boolean; enabled boolean; employers jsonb; employer_more boolean; BEGIN
 IF a IS NULL OR NOT EXISTS(SELECT 1 FROM platform_core.tenants t JOIN platform_core.tenant_memberships m ON m.tenant_id=t.id JOIN auth.users u ON u.id=m.user_id WHERE t.id=p_tenant AND t.lifecycle_state='active' AND m.user_id=a AND m.access_state='active' AND u.deleted_at IS NULL AND u.email_confirmed_at IS NOT NULL AND (u.banned_until IS NULL OR u.banned_until<=now())) THEN RAISE EXCEPTION 'leave_forbidden' USING ERRCODE='42501'; END IF;
 can_view:=platform_private.has_tenant_permission(p_tenant,a,'leave.view') OR platform_private.has_tenant_permission(p_tenant,a,'leave.manage') OR platform_private.has_tenant_permission(p_tenant,a,'leave.approve'); can_manage:=platform_private.has_tenant_permission(p_tenant,a,'leave.manage'); can_approve:=platform_private.has_tenant_permission(p_tenant,a,'leave.approve'); can_adjust:=platform_private.has_tenant_permission(p_tenant,a,'leave_balance.adjust'); self_access:=platform_private.has_leave_self_permission(p_tenant,a,'leave.self.view');
 IF NOT (can_view OR can_manage OR can_approve OR can_adjust OR self_access) THEN RAISE EXCEPTION 'leave_forbidden' USING ERRCODE='42501'; END IF;
 enabled:=platform_private.tenant_capability_is_enabled(p_tenant,'hr.people',now()) AND platform_private.tenant_capability_is_enabled(p_tenant,'hr.leave',now());
 SELECT coalesce(jsonb_agg(x.item ORDER BY x.display_name,x.id),'[]'::jsonb) INTO employers FROM (SELECT e.id,e.display_name,jsonb_build_object('id',e.id,'display_name',e.display_name,'is_active',e.is_active) item FROM platform_core.tenant_legal_entities e WHERE e.tenant_id=p_tenant AND e.is_active AND (can_view OR can_manage OR can_approve OR can_adjust) ORDER BY e.display_name,e.id LIMIT 100) x;
 SELECT EXISTS(SELECT 1 FROM platform_core.tenant_legal_entities e WHERE e.tenant_id=p_tenant AND e.is_active AND (can_view OR can_manage OR can_approve OR can_adjust) ORDER BY e.display_name,e.id OFFSET 100 LIMIT 1) INTO employer_more;
 RETURN jsonb_build_object('can_view',can_view,'can_manage',can_manage,'can_approve',can_approve,'can_adjust',can_adjust,'self_access',self_access,'new_work_enabled',enabled,'employers',employers,'employers_has_more',employer_more);
END $f$;
REVOKE ALL ON FUNCTION public.leave_access_snapshot(uuid) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_access_snapshot(uuid) TO authenticated;

CREATE FUNCTION public.leave_post_balance(p_tenant uuid,p_employee uuid,p_employer uuid,p_type uuid,p_period uuid,p_kind text,p_delta numeric,p_type_version uuid,p_key text,p_source text,p_reason text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=leave.authorized(p_tenant,'leave_balance.adjust',true); account uuid; old leave.ledger_entries%ROWTYPE; active_version leave.type_versions%ROWTYPE; employment uuid; balance_now numeric; period_start date; policy_date date; entity_active boolean; ky text:=btrim(coalesce(p_key,'')); src text:=btrim(coalesce(p_source,'')); why text:=btrim(coalesce(p_reason,'')); cairo_today date:=((now() AT TIME ZONE 'Africa/Cairo')::date); BEGIN
 IF p_type IS NULL OR p_period IS NULL OR p_kind IS NULL OR p_kind NOT IN('opening','annual_grant','adjustment') OR p_delta IS NULL OR p_delta=0 OR p_delta<>round(p_delta,2) OR p_type_version IS NULL OR ky='' OR length(ky)>120 OR src='' OR length(src)>300 OR why='' OR length(why)>500 OR (p_kind IN('opening','annual_grant') AND p_delta<=0) THEN RAISE EXCEPTION 'leave_balance_input_invalid' USING ERRCODE='22023'; END IF;
 PERFORM 1 FROM people.employees WHERE tenant_id=p_tenant AND id=p_employee FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'leave_employee_unavailable' USING ERRCODE='23503'; END IF;
 PERFORM leave.authorized(p_tenant,'leave_balance.adjust',true);
 SELECT id INTO employment FROM people.employments WHERE tenant_id=p_tenant AND employee_id=p_employee AND employer_entity_id=p_employer AND employment_status='active' AND start_date<=cairo_today AND (end_date IS NULL OR end_date>=cairo_today) FOR UPDATE;
 IF employment IS NULL THEN RAISE EXCEPTION 'leave_active_employment_required' USING ERRCODE='23514'; END IF;
 SELECT is_active INTO entity_active FROM platform_core.tenant_legal_entities WHERE tenant_id=p_tenant AND id=p_employer FOR UPDATE;
 IF NOT coalesce(entity_active,false) THEN RAISE EXCEPTION 'leave_employer_unavailable' USING ERRCODE='23503'; END IF;
 SELECT starts_on INTO period_start FROM leave.year_periods WHERE tenant_id=p_tenant AND id=p_period AND employer_entity_id=p_employer;
 IF period_start IS NULL THEN RAISE EXCEPTION 'leave_account_scope_invalid' USING ERRCODE='23503'; END IF;
 IF NOT EXISTS(SELECT 1 FROM leave.types WHERE tenant_id=p_tenant AND id=p_type AND employer_entity_id=p_employer) THEN RAISE EXCEPTION 'leave_account_scope_invalid' USING ERRCODE='23503'; END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text||p_employee::text,90429)); PERFORM leave.authorized(p_tenant,'leave_balance.adjust',true);
 INSERT INTO leave.accounts(tenant_id,employer_entity_id,employee_id,leave_type_id,year_period_id,created_by) VALUES(p_tenant,p_employer,p_employee,p_type,p_period,a) ON CONFLICT(tenant_id,employer_entity_id,employee_id,leave_type_id,year_period_id) DO NOTHING;
 SELECT id INTO account FROM leave.accounts WHERE tenant_id=p_tenant AND employer_entity_id=p_employer AND employee_id=p_employee AND leave_type_id=p_type AND year_period_id=p_period FOR UPDATE;
 PERFORM leave.authorized(p_tenant,'leave_balance.adjust',true);
 SELECT * INTO old FROM leave.ledger_entries WHERE tenant_id=p_tenant AND account_id=account AND idempotency_key=ky;
 IF FOUND THEN IF old.entry_kind=p_kind AND old.delta_days=p_delta AND old.source_version_id=p_type_version AND old.source_reference=src AND old.reason=why THEN RETURN jsonb_build_object('state','replay','account_id',account,'entry_id',old.id); ELSE RAISE EXCEPTION 'leave_idempotency_conflict' USING ERRCODE='23505'; END IF; END IF;
 IF p_kind='annual_grant' AND EXISTS(SELECT 1 FROM leave.ledger_entries WHERE tenant_id=p_tenant AND account_id=account AND entry_kind='annual_grant') THEN RAISE EXCEPTION 'leave_annual_grant_exists' USING ERRCODE='23505'; END IF;
 policy_date:=CASE WHEN p_kind='opening' THEN period_start ELSE cairo_today END;
 SELECT * INTO active_version FROM leave.type_versions WHERE tenant_id=p_tenant AND leave_type_id=p_type AND id=p_type_version AND effective_from<=policy_date AND (effective_until IS NULL OR effective_until>policy_date);
 IF NOT FOUND THEN RAISE EXCEPTION 'leave_type_version_unavailable' USING ERRCODE='23503'; END IF;
 IF active_version.balance_mode<>'tracked' THEN RAISE EXCEPTION 'leave_untracked_has_no_balance' USING ERRCODE='23514'; END IF;
 IF p_delta>0 AND (NOT platform_private.tenant_capability_is_enabled(p_tenant,'hr.people',now()) OR NOT platform_private.tenant_capability_is_enabled(p_tenant,'hr.leave',now())) THEN RAISE EXCEPTION 'leave_positive_growth_disabled' USING ERRCODE='55000'; END IF;
 SELECT coalesce(sum(delta_days),0) INTO balance_now FROM leave.ledger_entries WHERE tenant_id=p_tenant AND account_id=account;
 IF p_kind='adjustment' AND balance_now+p_delta<0 THEN RAISE EXCEPTION 'leave_balance_insufficient' USING ERRCODE='23514'; END IF;
 INSERT INTO leave.ledger_entries(tenant_id,account_id,leave_type_id,entry_kind,delta_days,source_version_id,source_reference,idempotency_key,reason,actor_user_id) VALUES(p_tenant,account,p_type,p_kind,p_delta,p_type_version,src,ky,why,a) RETURNING id INTO employment;
 RETURN jsonb_build_object('state','created','account_id',account,'entry_id',employment); END $f$;
REVOKE ALL ON FUNCTION public.leave_post_balance(uuid,uuid,uuid,uuid,uuid,text,numeric,uuid,text,text,text) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_post_balance(uuid,uuid,uuid,uuid,uuid,text,numeric,uuid,text,text,text) TO authenticated;

CREATE FUNCTION public.leave_my_balances(p_tenant uuid,p_limit integer DEFAULT 50,p_offset integer DEFAULT 0) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $f$
DECLARE a uuid:=auth.uid(); emp uuid; out_rows jsonb; lim integer:=least(100,greatest(1,coalesce(p_limit,50))); off integer:=coalesce(p_offset,0); more boolean; BEGIN
 IF a IS NULL OR NOT platform_private.has_leave_self_permission(p_tenant,a,'leave.self.view') THEN RAISE EXCEPTION 'leave_self_forbidden' USING ERRCODE='42501'; END IF;
 IF off<0 THEN RAISE EXCEPTION 'leave_page_invalid' USING ERRCODE='22023'; END IF;
 SELECT employee_id INTO emp FROM people.employee_user_links WHERE tenant_id=p_tenant AND user_id=a AND unlinked_at IS NULL;
 IF emp IS NULL THEN RAISE EXCEPTION 'leave_self_link_required' USING ERRCODE='42501'; END IF;
 WITH page_ids AS MATERIALIZED (SELECT ac.tenant_id,ac.id,ac.leave_type_id,ac.year_period_id,yp.starts_on,yp.label,t.name AS type_name FROM leave.accounts ac JOIN leave.types t ON t.tenant_id=ac.tenant_id AND t.id=ac.leave_type_id JOIN leave.year_periods yp ON yp.tenant_id=ac.tenant_id AND yp.id=ac.year_period_id WHERE ac.tenant_id=p_tenant AND ac.employee_id=emp ORDER BY yp.starts_on,ac.leave_type_id,ac.year_period_id,ac.id OFFSET off LIMIT lim+1), page AS MATERIALIZED (SELECT page_ids.*,row_number() OVER(ORDER BY starts_on,leave_type_id,year_period_id,id) rn FROM page_ids)
 SELECT coalesce((SELECT jsonb_agg(jsonb_build_object('leave_type_id',p.leave_type_id,'type_name',p.type_name,'period_id',p.year_period_id,'period_label',p.label,'starts_on',p.starts_on,'balance_days',coalesce((SELECT sum(le.delta_days) FROM leave.ledger_entries le WHERE le.tenant_id=p.tenant_id AND le.account_id=p.id),0)) ORDER BY p.rn) FROM page p WHERE p.rn<=lim),'[]'::jsonb),EXISTS(SELECT 1 FROM page WHERE rn>lim) INTO out_rows,more;
 RETURN jsonb_build_object('items',out_rows,'limit',lim,'offset',off,'has_more',more); END $f$;
REVOKE ALL ON FUNCTION public.leave_my_balances(uuid,integer,integer) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_my_balances(uuid,integer,integer) TO authenticated;

CREATE FUNCTION public.leave_hr_balances(p_tenant uuid,p_employee uuid,p_limit integer DEFAULT 50,p_offset integer DEFAULT 0) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path='' AS $f$
DECLARE out_rows jsonb; lim integer:=least(100,greatest(1,coalesce(p_limit,50))); off integer:=coalesce(p_offset,0); more boolean; BEGIN PERFORM leave.authorized(p_tenant,'leave.view',false); IF off<0 THEN RAISE EXCEPTION 'leave_page_invalid' USING ERRCODE='22023'; END IF;
 WITH page_ids AS MATERIALIZED (SELECT ac.tenant_id,ac.id,ac.employee_id,ac.leave_type_id,ac.year_period_id,yp.starts_on,yp.label,t.name AS type_name FROM leave.accounts ac JOIN leave.types t ON t.tenant_id=ac.tenant_id AND t.id=ac.leave_type_id JOIN leave.year_periods yp ON yp.tenant_id=ac.tenant_id AND yp.id=ac.year_period_id WHERE ac.tenant_id=p_tenant AND (p_employee IS NULL OR ac.employee_id=p_employee) ORDER BY yp.starts_on,ac.employee_id,ac.leave_type_id,ac.year_period_id,ac.id OFFSET off LIMIT lim+1), page AS MATERIALIZED (SELECT page_ids.*,row_number() OVER(ORDER BY starts_on,employee_id,leave_type_id,year_period_id,id) rn FROM page_ids)
 SELECT coalesce((SELECT jsonb_agg(jsonb_build_object('employee_id',p.employee_id,'leave_type_id',p.leave_type_id,'type_name',p.type_name,'period_id',p.year_period_id,'period_label',p.label,'starts_on',p.starts_on,'balance_days',coalesce((SELECT sum(le.delta_days) FROM leave.ledger_entries le WHERE le.tenant_id=p.tenant_id AND le.account_id=p.id),0)) ORDER BY p.rn) FROM page p WHERE p.rn<=lim),'[]'::jsonb),EXISTS(SELECT 1 FROM page WHERE rn>lim) INTO out_rows,more;
 RETURN jsonb_build_object('items',out_rows,'limit',lim,'offset',off,'has_more',more); END $f$;
REVOKE ALL ON FUNCTION public.leave_hr_balances(uuid,uuid,integer,integer) FROM PUBLIC,anon,service_role; GRANT EXECUTE ON FUNCTION public.leave_hr_balances(uuid,uuid,integer,integer) TO authenticated;
