'use client';
import {useState} from 'react';
export type NumericRules={tax:{treatment:string;exemption:string;column_basis:'annual_raw'|'annual_floor10';columns:{through:string;bands:{upper:string;rate:string}[]}[]};insurance:{category:string;minimum:string;maximum:string;branches:{branch:string;employee:string;employer:string;deductible:boolean}[]};base_taxable:boolean;earning_partition_rounding?:'chronological_prefix_half_up_cent';labour_deduction_adapter?:'eg-wage-deductions113114-v1'};
const branchNames:Record<string,string>={pension:'المعاشات',reward:'المكافأة',injury:'إصابة العمل',sickness:'المرض',unemployment:'البطالة',universal_health:'التأمين الصحي الشامل'};
const empty=():NumericRules=>({tax:{treatment:'',exemption:'',column_basis:'annual_raw',columns:[{through:'',bands:[{upper:'',rate:''}]}]},insurance:{category:'',minimum:'',maximum:'',branches:[{branch:'pension',employee:'',employer:'',deductible:false}]},base_taxable:false});
export function NumericRulesEditor({initial,frozen,onEdit}:{initial:NumericRules|null;frozen:boolean;onEdit:()=>void}){
 const [baseChoice,setBaseChoice]=useState(initial?(initial.base_taxable?'taxable':'nontaxable'):'');const [basisChoice,setBasisChoice]=useState(initial?.tax.column_basis??'');const [enabled,setEnabled]=useState(Boolean(initial));const [rules,updateRules]=useState<NumericRules>(()=>initial??empty());
 const setRules=(change:(current:NumericRules)=>NumericRules)=>{onEdit();updateRules(change);};
 const input=(id:string,label:string,value:string,change:(value:string)=>void,percent=false)=><label htmlFor={id}>{label}<input id={id} type="text" inputMode="decimal" dir="ltr" value={value} onChange={event=>change(event.target.value)} required pattern={percent?'(0|[1-9][0-9]{0,2})(\\.[0-9]{1,6})?':'(0|[1-9][0-9]{0,9})(\\.[0-9]{1,2})?'} maxLength={percent?10:13}/></label>;
 const tax=(patch:Partial<NumericRules['tax']>)=>setRules(current=>({...current,tax:{...current.tax,...patch}}));
 const insurance=(patch:Partial<NumericRules['insurance']>)=>setRules(current=>({...current,insurance:{...current.insurance,...patch}}));
 const column=(index:number,patch:Partial<NumericRules['tax']['columns'][number]>)=>tax({columns:rules.tax.columns.map((item,i)=>i===index?{...item,...patch}:item)});
 const band=(ci:number,bi:number,patch:Partial<{upper:string;rate:string}>)=>column(ci,{bands:rules.tax.columns[ci].bands.map((item,i)=>i===bi?{...item,...patch}:item)});
 const branch=(index:number,patch:Partial<NumericRules['insurance']['branches'][number]>)=>insurance({branches:rules.insurance.branches.map((item,i)=>i===index?{...item,...patch}:item)});
 return <><input type="hidden" name="numericRules" value={JSON.stringify(enabled?rules:null)}/><details open={enabled}><summary>القواعد الرقمية للمراجعة</summary><fieldset disabled={frozen}><label><input type="checkbox" checked={enabled} onChange={event=>{onEdit();setEnabled(event.target.checked);}}/> تضمين قواعد رقمية في هذه النسخة</label><p className="field-hint">انقل القيم من المراجع الرسمية. الحفظ لا يفعّلها لحساب الرواتب. إلغاء الاختيار يحفظ نسخة بلا قواعد رقمية مع إبقاء التاريخ السابق.</p>
 {enabled&&<><h3>ضريبة الأجور</h3><div className="limit-fields"><label htmlFor="tax-treatment">رمز المعاملة الضريبية<input id="tax-treatment" value={rules.tax.treatment} onChange={event=>tax({treatment:event.target.value})} required pattern="[0-9]{2}" maxLength={2} dir="ltr"/></label>{input('tax-exemption','الإعفاء الشخصي السنوي (ج.م.)',rules.tax.exemption,value=>tax({exemption:value}))}</div><label htmlFor="tax-column-basis">الدخل المستخدم لاختيار جدول الشرائح<select id="tax-column-basis" required value={basisChoice} onChange={event=>{setBasisChoice(event.target.value);tax({column_basis:event.target.value as NumericRules['tax']['column_basis']});}}><option value="" disabled>اختر وفق المرجع</option><option value="annual_raw">الدخل السنوي قبل تقريب أساس الضريبة</option><option value="annual_floor10">أساس الضريبة بعد التقريب لأقل عشرة جنيهات</option></select></label><p className="field-hint">الأساس يُقرب لأقل عشرة جنيهات، والضريبة التراكمية لأقرب قرش. النسب تُدخل كنسبة مئوية، مثل 10 تعني 10٪.</p>
 {rules.tax.columns.map((item,ci)=><fieldset key={ci}><legend>جدول الشرائح {ci+1}</legend>{ci===rules.tax.columns.length-1?<p>جدول الدخل الأعلى: بلا حد نهائي.</p>:input(`tax-through-${ci}`,'يُستخدم حتى دخل سنوي (ج.م.)',item.through,value=>column(ci,{through:value}))}
 {item.bands.map((part,bi)=><div className="limit-fields" key={bi}>{bi===item.bands.length-1?<p>الشريحة الأخيرة: ما يزيد على الشرائح السابقة.</p>:input(`tax-upper-${ci}-${bi}`,'نهاية الشريحة (ج.م.)',part.upper,value=>band(ci,bi,{upper:value}))}{input(`tax-rate-${ci}-${bi}`,'نسبة الضريبة (%)',part.rate,value=>band(ci,bi,{rate:value}),true)}{item.bands.length>1&&<button type="button" className="secondary-button" onClick={()=>column(ci,{bands:item.bands.filter((_,i)=>i!==bi).map((b,i,array)=>i===array.length-1?{...b,upper:''}:b)})}>حذف الشريحة {bi+1}</button>}</div>)}
 {item.bands.length<32&&<button type="button" className="secondary-button" onClick={()=>column(ci,{bands:[...item.bands,{upper:'',rate:''}]})}>إضافة شريحة لهذا الجدول</button>}{rules.tax.columns.length>1&&<button type="button" className="secondary-button" onClick={()=>tax({columns:rules.tax.columns.filter((_,i)=>i!==ci).map((c,i,array)=>i===array.length-1?{...c,through:''}:c)})}>حذف الجدول {ci+1}</button>}</fieldset>)}
 {rules.tax.columns.length<16&&<button type="button" className="secondary-button" onClick={()=>tax({columns:[...rules.tax.columns,{through:'',bands:[{upper:'',rate:''}]}]})}>إضافة جدول لدخل أعلى</button>}
 <label htmlFor="base-taxable">معاملة الأجر الأساسي<select id="base-taxable" required value={baseChoice} onChange={event=>{setBaseChoice(event.target.value);setRules(current=>({...current,base_taxable:event.target.value==='taxable'}));}}><option value="" disabled>اختر وفق المرجع</option><option value="nontaxable">غير خاضع وفق المرجع</option><option value="taxable">خاضع وفق المرجع</option></select></label><p className="field-hint">تصنيف المكونات الأخرى يعتمد على بياناتها المؤرخة. عند اختلاف التصنيف، يُقرب الجزء الخاضع لأقرب قرش ويُحفظ الباقي في الجزء غير الخاضع.</p>
 <label htmlFor="earning-partition-rounding">توزيع أجزاء الكسب بين السياقات القانونية<select id="earning-partition-rounding" value={rules.earning_partition_rounding??''} onChange={event=>setRules(current=>{const next={...current};if(event.target.value)next.earning_partition_rounding='chronological_prefix_half_up_cent';else delete next.earning_partition_rounding;return next;})}><option value="">لم يراجع هذا النطاق</option><option value="chronological_prefix_half_up_cent">فروق الإجمالي المقرّب حسب ترتيب التواريخ</option></select></label><p className="field-hint">انقل طريقة التوزيع من المرجع المراجع. يحفظ الحساب مجموع المكوّن الأصلي وكسور القرش، ولا يستنتج تاريخ كسب للمبلغ اليدوي. الاختيار لا يؤهل الإصدار أو يعتمد راتبًا.</p>
 <label htmlFor="labour-deduction-adapter">حدود وأولوية الاستقطاع وفق نطاق الإصدار<select id="labour-deduction-adapter" value={rules.labour_deduction_adapter??''} onChange={event=>setRules(current=>{const next={...current};if(event.target.value)next.labour_deduction_adapter='eg-wage-deductions113114-v1';else delete next.labour_deduction_adapter;return next;})}><option value="">لم يراجع نطاق الاستقطاع</option><option value="eg-wage-deductions113114-v1">النطاق القياسي للمادتين ١١٣ و١١٤</option></select></label><p className="field-hint">يلزم المرجع الرسمي ومقارنات مستقلة للحدود والأولوية وأساس الأجر. مراجعة الضريبة والتأمينات وحدها لا تؤهل الاستقطاع.</p>
 <h3>التأمينات الاجتماعية</h3><label htmlFor="insurance-category">الفئة التأمينية<input id="insurance-category" value={rules.insurance.category} onChange={event=>insurance({category:event.target.value})} required minLength={1} maxLength={160}/></label><div className="limit-fields">{input('insurance-minimum','الحد الأدنى لأجر الاشتراك (ج.م.)',rules.insurance.minimum,value=>insurance({minimum:value}))}{input('insurance-maximum','الحد الأقصى لأجر الاشتراك (ج.م.)',rules.insurance.maximum,value=>insurance({maximum:value}))}</div><p className="field-hint">تُقرب حصة كل فرع لكل شهر لأقرب قرش. هذه القواعد لا تحدد وحدها أشهر الاشتراك المستحقة.</p>
 {rules.insurance.branches.map((item,bi)=><fieldset key={bi}><legend>فرع التأمين {bi+1}</legend><label htmlFor={`insurance-branch-${bi}`}>الفرع<select id={`insurance-branch-${bi}`} value={item.branch} onChange={event=>branch(bi,{branch:event.target.value})}>{!branchNames[item.branch]&&<option value={item.branch}>فرع محفوظ يحتاج مراجعة مرجعه</option>}{Object.entries(branchNames).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className="limit-fields">{input(`insurance-employee-${bi}`,'حصة الموظف (%)',item.employee,value=>branch(bi,{employee:value}),true)}{input(`insurance-employer-${bi}`,'حصة جهة العمل (%)',item.employer,value=>branch(bi,{employer:value}),true)}</div><label><input type="checkbox" checked={item.deductible} onChange={event=>branch(bi,{deductible:event.target.checked})}/> حصة الموظف تخفض أساس ضريبة الأجور وفق المرجع</label>{rules.insurance.branches.length>1&&<button type="button" className="secondary-button" onClick={()=>insurance({branches:rules.insurance.branches.filter((_,i)=>i!==bi)})}>حذف فرع التأمين {bi+1}</button>}</fieldset>)}{rules.insurance.branches.length<6&&<button type="button" className="secondary-button" onClick={()=>insurance({branches:[...rules.insurance.branches,{branch:'pension',employee:'',employer:'',deductible:false}]})}>إضافة فرع تأمين</button>}</>}
 </fieldset></details></>;
}
export function NumericRulesSummary({rules}:{rules:NumericRules|null|undefined}){
 if(!rules)return <p>لا توجد قواعد رقمية في هذه النسخة.</p>;
 return <details><summary>القواعد الرقمية المحفوظة</summary><p>توزيع أجزاء الكسب: {rules.earning_partition_rounding?'طريقة التوزيع محفوظة وتحتاج أدلة الإصدار':'لم يراجع هذا النطاق'}. الاستقطاع: {rules.labour_deduction_adapter?'النطاق القياسي محفوظ ويحتاج أدلته المستقلة':'لم يراجع هذا النطاق'}.</p><p>رمز المعاملة: {rules.tax.treatment} · الإعفاء الشخصي: {rules.tax.exemption} ج.م. · الأجر الأساسي: {rules.base_taxable?'خاضع':'غير خاضع'}</p><p>اختيار الجدول: {rules.tax.column_basis==='annual_raw'?'الدخل السنوي قبل التقريب':'الأساس بعد التقريب لأقل عشرة جنيهات'}</p>{rules.tax.columns.map((item,i)=><div key={i}><h4>جدول {i+1} · {item.through?`حتى ${item.through} ج.م.`:'بلا حد نهائي'}</h4><ul>{item.bands.map((part,j)=><li key={j}>{part.upper?`حتى ${part.upper} ج.م.`:'ما يزيد على السابق'} · {part.rate}٪</li>)}</ul></div>)}<p>الفئة التأمينية: {rules.insurance.category} · أجر الاشتراك: {rules.insurance.minimum} إلى {rules.insurance.maximum} ج.م.</p><ul>{rules.insurance.branches.map(item=><li key={item.branch}>{branchNames[item.branch]??'فرع محفوظ يحتاج مراجعة مرجعه'} · الموظف {item.employee}٪ · جهة العمل {item.employer}٪ · {item.deductible?'تخفض حصة الموظف أساس الضريبة':'لا تخفض حصة الموظف أساس الضريبة'}</li>)}</ul><p>تقريب الضريبة التراكمية وحصة كل فرع تأمين لكل شهر لأقرب قرش. المسودة غير مؤهلة لحساب الرواتب.</p></details>;
}
