import { Button, ButtonLink, Disclosure, Input, Message, PageHeader, Panel, RecordCard, Field } from '@/components/ui';
import { ARABIC_DISPLAY_LOCALE } from '@/lib/display-locale';
import {EmployerSelector} from '../EmployerSelector';
import {normalizeEmployerScope} from '../employer-context';
import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { PageFrame } from '@/components/context-navigation';
import { getWorkspaceClient as createSupabaseServerClient, getWorkspaceUser } from '@/lib/workspace-access';
import { CalendarForm, DateSummary, GenerateForm } from '../CalendarForm';
import { type CalendarPreview, displayDate, uuid } from '../rules';
import styles from '../payroll.module.css';
export const dynamic = 'force-dynamic';
type Employer = { id: string; name: string };
type Version = {revision:number;effective_from:string;effective_until:string|null;cutoff_day:number|null;payment_day:number;payment_month:string;timezone:string};
type Workspace = { employer_name:string; revision:number; next_start:string|null; access:{can_view:boolean;can_manage:boolean;enabled:boolean}; versions:Version[]; periods:(CalendarPreview & {is_transition:boolean})[]; next_preview?:CalendarPreview; calendar_change_review?:{open_run_period_id:string|null;locked_history:boolean;attendance_enabled:boolean;pending_attendance_date:string|null;can_review_attendance:boolean} };
export default async function PayrollSetupPage({params,searchParams}: {params:Promise<{tenantId:string}>;searchParams:Promise<{employer?:string;period?:string;review_q?:string;q?:string;after_name?:string;after_id?:string;before?:string;stage?:string;employer_scope?:string}>}) {
 const {tenantId} = await params; if(!uuid(tenantId)) notFound(); const query = await searchParams;
 const path = `/tenant/${tenantId}/payroll/setup`; const employerDestination=normalizeEmployerScope(path,'setup',query);if(employerDestination)redirect(employerDestination); const retry = `${path}?${new URLSearchParams(query).toString()}`;
 const failure = (text:string) => <PageFrame><Panel className={styles.card}><PageHeader  title={<>الرواتب</>} /><Message tone="bad" role="alert">{text}</Message><ButtonLink variant="ghost"  href={retry}>إعادة المحاولة</ButtonLink></Panel></PageFrame>;
 const client = await createSupabaseServerClient(); if(!client) return failure('تعذر الاتصال. أعد المحاولة لاستعادة بيانات الرواتب.');
 const {data:{user}} = await getWorkspaceUser(client); if(!user) redirect(`/auth/login?next=${encodeURIComponent(retry)}`);
 const {data:access,error:accessError} = await client.rpc('payroll_access_snapshot',{p_tenant:tenantId});
 if(accessError || !access) return failure(accessError?.code==='42501'?'هذا الحساب غير مخوّل للوصول إلى الرواتب. راجع مسؤول الشركة.':'تعذر تحميل صلاحيات الرواتب.');
 if((query.review_q?.length ?? 0)>120 || (query.period && !uuid(query.period)) || (query.q?.length ?? 0)>120 || (query.employer && !uuid(query.employer)) || (query.after_id && !uuid(query.after_id)) || (query.before && !/^\d{4}-\d{2}-\d{2}$/.test(query.before))) return failure('راجع رابط البحث والفترة ثم أعد المحاولة.');
 const {data:employers,error:employerError} = await client.rpc('payroll_employers',{p_tenant:tenantId,p_query:query.q??'',p_after_name:query.after_name??null,p_after_id:query.after_id??null,p_limit:30});
 if(employerError || !employers || !Array.isArray(employers.items)) return failure('تعذر تحميل الجهات. الاختيار السابق محفوظ في رابط الصفحة.');
 const items = employers.items as Employer[]; const employer = query.employer ?? employers.unique_employer ?? '';
 let workspace:Workspace|null=null;
 if(employer) { const result = await client.rpc('payroll_workspace',{p_tenant:tenantId,p_employer:employer,p_before:query.before??null,p_limit:12}); if(result.error || !result.data) return failure('تعذر تحميل دورة هذه الجهة وفتراتها. أعد المحاولة بنفس الجهة والفترة.'); workspace=result.data as Workspace; }
 const link = (extra:Record<string,string>) => `${path}?${new URLSearchParams({...(query.q?{q:query.q}:{}),...(query.period?{period:query.period}:{}),...(query.review_q?{review_q:query.review_q}:{}),...(employer?{employer}:{}),...(extra.employer&&extra.employer!==employer?{period:'',review_q:''}:{}),...extra}).toString()}`;
 const today = new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo'}).format(new Date());
 return <PageFrame><div className={styles.workspace} dir="rtl"><div><p className="eyebrow">مساحة الشركة · إعداد الرواتب</p><PageHeader  title={<>دورة الرواتب والفترات</>} description={<> اضبط الدورة لكل جهة، وراجع تواريخ الفترات وجاهزيتها. </>} /><Link href={`/tenant/${tenantId}/payroll?${new URLSearchParams({...(query.employer?{employer:query.employer}:{}),...(query.period?{period:query.period}:{}),...(query.review_q?{review_q:query.review_q}:{})})}`}>العودة إلى مساحة الرواتب</Link></div>
 <form method="get" className={styles.filters}>{employer&&<input type="hidden" name="employer" value={employer}/>} {query.period&&<input type="hidden" name="period" value={query.period}/>} {query.review_q&&<input type="hidden" name="review_q" value={query.review_q}/>}<Field  id="payroll-employer-search" label={<>البحث عن جهة</>}><Input id="payroll-employer-search" name="q" defaultValue={query.q??''} maxLength={120}/></Field><Button variant="ghost" type="submit" >بحث</Button></form>
 {!employer && <section><h2>اختر جهة العمل</h2>{items.length===0?<p>لا توجد جهات مطابقة. عدّل البحث أو راجع إعداد الجهات مع مسؤول الشركة.</p>:<ul>{items.map(e=><li key={e.id}><Link href={link({employer:e.id})}>{e.name}</Link></li>)}</ul>}</section>}
 {items.length===30 && <Link href={link({after_name:items[29].name,after_id:items[29].id})}>جهات إضافية</Link>}
 {workspace && <><Panel className={styles.card}><h2>{workspace.employer_name}</h2><EmployerSelector path={path} page="setup" employer={employer} name={workspace.employer_name} choices={items} context={query} singleEmployer={employers.unique_employer===employer}/><Link href={path}>اختيار جهة أخرى</Link>{!workspace.access.enabled && <Message tone="info" role="status">خدمة الرواتب غير مفعلة لهذه الشركة. يمكنك مراجعة التاريخ؛ راجع مسؤول الشركة قبل إعداد فترات جديدة.</Message>}</Panel>
 <p><Link href={`/tenant/${tenantId}/payroll/inputs?${new URLSearchParams({employer,period:query.period??'',q:query.review_q??''})}`}>تحضير مدخلات الجهة ومراجعتها</Link> · <Link href={`/tenant/${tenantId}/payroll/runs?${new URLSearchParams({employer,period:query.period??'',q:query.review_q??''})}`}>العودة إلى حساب ومراجعة الرواتب</Link></p>
 <nav className={styles.reviewNavigation} aria-label="أقسام إعداد الرواتب"><a href="#payroll-setup-periods">الفترات المحفوظة</a><a href="#payroll-setup-readiness">جاهزية الفترة</a><a href="#payroll-setup-history">تاريخ إعداد الدورة</a></nav>
 <section id="payroll-setup-periods"><h2>الفترات المحفوظة</h2>{workspace.periods.length===0?<p>لا توجد فترات محفوظة لهذه الجهة.</p>:<ul className={styles.cardGrid}>{workspace.periods.map(p=><RecordCard key={p.starts_on} className={styles.card}><h3>رواتب {new Intl.DateTimeFormat(ARABIC_DISPLAY_LOCALE,{year:'numeric',month:'long',timeZone:'UTC'}).format(new Date(`${p.ends_on}T12:00:00Z`))}</h3>{p.is_transition && <p>فترة انتقالية تمت مراجعة تواريخها</p>}<DateSummary preview={p}/><p>التواريخ محفوظة؛ راجع الحساب والتأهيل المالي والقانوني لهذه الفترة من مراجعة الرواتب.</p></RecordCard>)}</ul>}{workspace.periods.length===12 && <Link href={link({before:workspace.periods[11].starts_on})}>فترات أقدم</Link>}{query.before && <Link href={link({})}>العودة إلى أحدث الفترات</Link>}</section>
 <Panel id="payroll-setup-readiness" className={styles.card}><h2>جاهزية الفترة</h2><ul><li>{workspace.versions.length?'الدورة: التواريخ محددة ومحفوظة.':'الدورة: يلزم إعدادها أولًا.'}</li><li>بيانات الموظفين والتعويضات: لم تُفحص في هذه المرحلة.</li><li>الحضور والإجازات وتمويل الموظفين: لم تُفحص بعد. غياب خدمة اختيارية ليس خطأ.</li><li>هذه الصفحة لا تفحص تأهيل حساب الفترة أو اعتمادها. راجع حالة المسير الحالية؛ التثبيت يتطلب التأهيل والاعتماد وصلاحية المسؤول المخول.</li></ul></Panel>
 {workspace.access.can_manage && workspace.access.enabled && (query.stage==='setup'||workspace.versions.length===0?<>
  <Panel className={styles.card} aria-label="قبل تغيير الدورة"><h2>قبل تغيير الدورة</h2>
   {workspace.calendar_change_review?.open_run_period_id && <Message tone="info" role="status">يوجد مسير مفتوح لهذه الجهة. أكمل مساره أو ألغِه من مراجعة الرواتب قبل تغيير الدورة. إذا كان معتمدًا، يلزم تحرير الاعتماد أولًا بإذن المسؤول. <Link href={`/tenant/${tenantId}/payroll/runs?${new URLSearchParams({employer,period:workspace.calendar_change_review.open_run_period_id})}`}>مراجعة المسير المفتوح</Link></Message>}
   {workspace.calendar_change_review?.pending_attendance_date && <Message tone="info" role="status">توجد بيانات حضور تحتاج إلى مراجعة ضمن الفترات المحفوظة، بدءًا من {displayDate(workspace.calendar_change_review.pending_attendance_date)}. تغيير الدورة لا يحل هذه المراجعة ولا ينقل البيانات إلى فترة أخرى. {workspace.calendar_change_review.can_review_attendance?<Link href={`/tenant/${tenantId}/attendance/review?date=${workspace.calendar_change_review.pending_attendance_date}`}>مراجعة الحضور</Link>:'اطلب من مسؤول الحضور مراجعتها.'}</Message>}
   {workspace.calendar_change_review?.locked_history && <p>توجد رواتب مقفلة لهذه الجهة. تواريخها ومخرجاتها ستظل محفوظة؛ التغيير للفترات القادمة فقط.</p>}
   <p className="muted">هذه التنبيهات لا تثبت اكتمال مدخلات الرواتب. تُراجع الجاهزية عند حساب الفترة، ولا يُعتبر اليوم بلا سجل غيابًا.</p>
  </Panel>
  {!workspace.calendar_change_review?.open_run_period_id && <CalendarForm key={`${tenantId}:${employer}:${workspace.revision}`} tenant={tenantId} employer={employer} start={workspace.next_start??today} last={workspace.next_start?new Date(new Date(`${workspace.next_start}T12:00:00Z`).getTime()-86400000).toISOString().slice(0,10):null} defaults={workspace.versions[0]}/>}
 </>:<Panel className={styles.card}>{workspace.next_preview && <GenerateForm key={`${tenantId}:${employer}:${workspace.revision}`} tenant={tenantId} employer={employer} revision={workspace.revision} preview={workspace.next_preview}/>}<p><Link href={link({stage:'setup'})}>تغيير الدورة للفترات القادمة</Link></p></Panel>)}
 <Disclosure summary={<>تاريخ إعداد الدورة</>} id="payroll-setup-history" className={styles.card}>{workspace.versions.length===0?<p>لم تُحفظ دورة بعد.</p>:<ul>{workspace.versions.map(v=><li key={v.revision}>تبدأ {displayDate(v.effective_from)}{v.effective_until?` وتنتهي قبل ${displayDate(v.effective_until)}`:''} · نهاية الفترة: {v.cutoff_day??'آخر يوم من الشهر'} · الصرف يوم {v.payment_day} في {v.payment_month==='following'?'الشهر التالي':'شهر نهاية الفترة'} · <bdi>{v.timezone}</bdi></li>)}</ul>}</Disclosure>
 {query.stage==='setup' && <Link href={link({})}>إلغاء والعودة إلى الفترات</Link>}
 </>}
 </div></PageFrame>;
}
