'use client';
import {useActionState,useState} from 'react';
import Link from 'next/link';
import {inputAction} from './actions';
import {replacementInputHref} from './employee-selection';
import {inputOptions,inputFields,openingCoverageFields,statutoryCalculationFields,kindNames,statusNames,type InputKind,type InputRecord} from './rules';
import styles from '../payroll.module.css';
type Choice={id:string;name:string};
const labels:Record<string,string>={tax_net_income:'الدخل الخاضع بعد الخصومات القانونية (إن كان معلومًا)',coverage_start:'بداية الفترة السابقة',coverage_end:'نهاية الفترة السابقة',tax_duration_days:'مدة الاحتساب الضريبي السابقة بالأيام وفق المرجع',tax_treatment_code:'رمز المعاملة الضريبية من المرجع',insurance_status:'حالة التأمينات',insurance_category:'الفئة التأمينية من المرجع',insured_wage:'الأجر المؤمن عليه بالجنيه',insurance_from:'تاريخ بدء الاشتراك',insurance_until:'تاريخ انتهاء الاشتراك (اختياري)',key:'رمز المكوّن',name:'اسم المكوّن',classification:'نوع المكوّن',calculation:'طريقة القيمة',base:'الأساس المحدد للنسبة',value:'القيمة أو النسبة',taxable:'يدخل في الأجر الخاضع للضريبة',social:'يدخل في أساس التأمينات',visible:'يظهر في بيان الراتب',active:'المكوّن فعال',proration:'استحقاق القيمة الثابتة خلال الفترة',order:'ترتيب العرض',behavior:'طريقة الاستخدام',component_id:'مكوّن الراتب',source:'مصدر الأيام',units:'إجمالي الأيام المستحقة',amount:'المبلغ بالجنيه',reference:'مرجع الإثبات',reason:'سبب الإدخال أو التغيير',year:'السنة',taxable_earnings:'الأجر الخاضع السابق',tax_withheld:'الضريبة المخصومة سابقًا',tax_due:'الضريبة المستحقة سابقًا (إن كانت معلومة)',social_base:'أساس التأمينات السابق',employee_social:'اشتراكات الموظف السابقة',employer_social:'اشتراكات جهة العمل السابقة',mode:'سياسة الجزء من الفترة'};
const insuranceOwnerLabels:Record<string,string>={insurance_obligation_month:'شهر التأمين الذي تتحمله هذه الفترة',insurance_owner_period:'الفترة المالكة لالتزام الشهر من المرجع',insurance_obligation_reference:'مرجع ملكية شهر التأمين'};
const calculationLabels:Record<string,string>={calculation_from:'أول يوم في نطاق الحساب المراجع',calculation_until:'آخر يوم في نطاق الحساب المراجع',tax_duration_days:'المدة الضريبية القانونية المراجعة لهذه الفترة'};
const options=inputOptions;
export function InputForm({tenant,employer,period,kind,record,employees,components,canSave,canApprove,back,timeEnabled=false,newEntry,insurancePeriods=[]}: {tenant:string;employer:string;period:{id:string;starts_on:string;ends_on:string};kind:InputKind;record?:InputRecord;employees:Choice[];components:Choice[];canSave:boolean;canApprove:boolean;back:string;timeEnabled?:boolean;newEntry?:string;insurancePeriods?:Choice[]}) {
 const tomorrow=new Date(`${period.ends_on}T12:00:00Z`);tomorrow.setUTCDate(tomorrow.getUTCDate()+1);
 const periodInput=['manual_units','adjustment'].includes(kind);
 const [values,setValues]=useState<Record<string,string>>(()=>({from:record?.effective_from??period.starts_on,until:record?.effective_until??(periodInput?tomorrow.toISOString().slice(0,10):''),employment:record?.employment_id??employees[0]?.id??'',...(kind==='manual_units'?{source:String(record?.data.source??'manual')}:{}) ,...Object.fromEntries(inputFields[kind].map(k=>[k,String(record?.data[k]??options[k]?.[0]?.[0]??(k==='order'?'10':k==='year'?period.starts_on.slice(0,4):''))]))}));
 const [state,action,pending]=useActionState(inputAction,{error:'',saved:false,head:record?.id??'',revision:record?.revision??0,attempt:'',signature:'',status:record?.status??'draft',manual_data:kind==='manual_units'?record?.data:undefined});
 const frozen=['cancelled','applied'].includes(state.status),approved=state.status==='approved';
 const field=(key:string,choices?:Choice[])=>{const list=choices?choices.map(c=>[c.id,c.name] as [string,string]):options[key];return <label key={key} htmlFor={`input-${key}`}>{(kind==='statutory_context'?(insuranceOwnerLabels[key]??calculationLabels[key]):undefined)??labels[key]??(key==='from'?'تاريخ السريان':'ينتهي قبل تاريخ (اختياري)')}{list?<select id={`input-${key}`} name={key} value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}>{choices&&values[key]&&!list.some(o=>o[0]===values[key])&&<option value={values[key]}>القيمة المحفوظة في هذا السجل</option>}{list.map(([value,label])=><option key={value} value={value} disabled={key==='source'&&value==='time'&&!timeEnabled}>{label}</option>)}</select>:<input id={`input-${key}`} name={key} value={values[key]??''} required={kind==='statutory_context'&&statutoryCalculationFields.includes(key)?statutoryCalculationFields.some(k=>Boolean(values[k])):key==='reference'?['opening_ytd','statutory_context'].includes(kind):openingCoverageFields.includes(key)?openingCoverageFields.some(k=>Boolean(values[k])):!['until','tax_due','tax_net_income','insurance_until'].includes(key)} type={['from','until','insurance_from','insurance_until','coverage_start','coverage_end','calculation_from','calculation_until','insurance_obligation_month'].includes(key)?'date':'text'} inputMode={['value','units','amount','tax_duration_days','insured_wage','taxable_earnings','tax_withheld','tax_due','tax_net_income','social_base','employee_social','employer_social'].includes(key)?'decimal':undefined} maxLength={key==='reason'?500:160} onChange={e=>setValues({...values,[key]:e.target.value})}/>}</label>};
 return <form action={action} onReset={e=>e.preventDefault()} className={styles.form}><h2>{kindNames[kind]}</h2><p>الحالة: {statusNames[state.status]??'مسودة'}</p><input type="hidden" name="tenant" value={tenant}/><input type="hidden" name="employer" value={employer}/><input type="hidden" name="kind" value={kind}/><input type="hidden" name="period" value={periodInput?period.id:''}/>
 {(frozen||approved)&&Object.entries(values).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}
 <fieldset disabled={pending||frozen||approved} className={styles.fields}>{!['component','policy'].includes(kind)?<label htmlFor="input-employment">الموظف<select id="input-employment" name="employment" value={values.employment} onChange={e=>setValues({...values,employment:e.target.value})} disabled={Boolean(state.head)}>{record&&!employees.some(e=>e.id===values.employment)&&<option value={values.employment}>الموظف المحدد في السجل</option>}{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select>{state.head&&<input type="hidden" name="employment" value={values.employment}/>}</label>:<input type="hidden" name="employment" value=""/>}
 {periodInput?<><input type="hidden" name="from" value={values.from}/><input type="hidden" name="until" value={values.until}/></>:<>{field('from')}{field('until')}</>}
 {kind==='manual_units'&&field('source')}{inputFields[kind].filter(k=>kind!=='opening_ytd'||!openingCoverageFields.includes(k)&&k!=='tax_net_income').filter(k=>kind!=='statutory_context'||!statutoryCalculationFields.includes(k)).filter(k=>kind!=='statutory_context'||values.insurance_status==='insured'||!['insurance_category','insured_wage','insurance_from','insurance_until','insurance_obligation_month','insurance_owner_period','insurance_obligation_reference'].includes(k)).map(k=>kind==='manual_units'&&k==='units'&&values.source==='time'?<input key={k} type="hidden" name="units" value="0"/>:field(k,k==='component_id'?components:k==='insurance_owner_period'?insurancePeriods:undefined))}{kind==='opening_ytd'&&<details style={{gridColumn:'1 / -1'}}><summary>تفاصيل احتساب الأرصدة السابقة (إن كانت معلومة)</summary><div className={styles.fields}>{field('tax_net_income')}{openingCoverageFields.map(k=>field(k))}</div><p>انقل الدخل بعد الخصومات القانونية وقبل الإعفاء الشخصي السنوي من المرجع السابق؛ قد يختلف عن الأجر الخاضع السابق. وانقل الفترة ومدتها من المرجع المراجَع. لا تُحسب المدة تلقائيًا من تاريخ الصرف أو عدد أيام دورة الراتب. اترك الحقول الثلاثة فارغة إن لم تكن معلومة.</p></details>}{kind==='statutory_context'&&<details style={{gridColumn:'1 / -1'}}><summary>حقائق مدة الحساب المراجعة</summary><div className={styles.fields}>{statutoryCalculationFields.map(key=>field(key))}</div><p>أدخل نطاق الفترة ومدتها من المرجع المراجع. لا تُستنتج المدة القانونية من أيام التقويم. تُستخدم هذه الحقائق لشرح الحساب، ويظل اعتماد المال مشروطًا بالتأهيل الكامل. للموظف المؤمن عليه، يلزم أيضًا ربط ملكية أشهر التأمين قبل اكتمال الحساب.</p></details>}</fieldset>
 {kind==='manual_units'&&<><p>{values.source==='time'?'يحسب الخادم الأيام من الحضور المعتمد والإجازة المدفوعة المتاحة، دون إضافة الأيام اليدوية. يلزم اكتمال مراجعة المصادر قبل اعتماد الراتب.':'أدخل إجمالي الأيام المستحقة بعد المراجعة، شاملًا الإجازة المدفوعة مرة واحدة. سيُستخدم هذا الإجمالي بدل أيام الحضور لهذه الفترة.'}</p>{!timeEnabled&&<p>الحضور غير مفعّل؛ يمكنك استخدام الإجمالي اليدوي الموثق. الاختيارات السابقة محفوظة للعرض والإلغاء.</p>}{approved&&<p>لتغيير مصدر الأيام، ألغِ المدخل المعتمد ثم أنشئ مدخلًا جديدًا واحفظه واعتمده.</p>}<p>حفظ المدخل واعتماده لا يعني صرف الراتب.</p></>}{kind==='statutory_context'&&values.insurance_status==='insured'&&<p>حدد الشهر والفترة المالكة من المرجع المراجع؛ لا تستنتجهما من أيام الأجر. الربط الحالي يدعم شهرًا تقويميًا كاملًا تغطيه بيانات الاشتراك، ويمنع استهلاك الشهر مرتين. حالات القطع والانضمام أو الانتهاء داخل الشهر تحتاج ربطًا إضافيًا.</p>}{kind==='statutory_context'&&<p>انقل المعاملة والفئة والأجر المؤمن عليه من المرجع المراجَع، مثل مستند التأمينات. قد يختلف الأجر المؤمن عليه عن إجمالي الراتب. هذه بيانات للموظف؛ حفظها لا يعتمد الحساب النظامي أو يصرف راتبًا.</p>}{kind==='opening_ytd'&&<p>أدخل القيم من مرجع مراجَع. الضريبة المستحقة هي نتيجة الحساب السابق، وقد تختلف عن المبلغ المخصوم. اتركها فارغة إن لم تكن معلومة؛ الصفر يعني أن المستحق صفر فعلًا. يلزم استكمال البيانات المطلوبة قبل الاعتماد النهائي.</p>}{kind==='policy'&&<p>تحدد مرة واحدة للشركة. الراتب الشهري الكامل للفترة العادية يُدفع كاملًا؛ تفاصيل الحساب والفترة الانتقالية تظهر عند إتاحة الحساب.</p>}{kind==='component'&&<p>معاملة الضريبة والتأمينات بيانات للمراجعة؛ لا تعني اعتمادًا قانونيًا. لا يدعم النظام معادلات حرة.</p>}
 {state.error&&<p role="alert">{state.error}</p>}{state.saved&&<p role="status">تم حفظ السجل في حالته الظاهرة. لم يُطبّق في راتب أو صرف.</p>}
 <div className={styles.actions}>{canSave&&!frozen&&(!periodInput||!approved)&&<button className="primary-button" name="operation" value="save" disabled={pending}>حفظ المدخل</button>}{canApprove&&state.head&&!frozen&&!approved&&periodInput&&<button className="primary-button" name="operation" value="approve" disabled={pending}>اعتماد المدخل</button>}{canSave&&state.head&&!frozen&&periodInput&&<button className="secondary-button" name="operation" value="cancel" formNoValidate disabled={pending}>إلغاء المدخل</button>}{kind==='manual_units'&&state.status==='cancelled'&&newEntry&&<Link className="primary-button" href={replacementInputHref(newEntry,values.employment)}>اختيار مصدر أيام جديد</Link>}<Link className="secondary-button" href={back}>العودة إلى المدخلات</Link></div></form>;
}
