'use client';
import {useActionState,useState} from 'react';
import Link from 'next/link';
import {inputAction} from './actions';
import {inputOptions,inputFields,kindNames,statusNames,type InputKind,type InputRecord} from './rules';
import styles from '../payroll.module.css';
type Choice={id:string;name:string};
const labels:Record<string,string>={key:'رمز المكوّن',name:'اسم المكوّن',classification:'نوع المكوّن',calculation:'طريقة القيمة',base:'الأساس المحدد للنسبة',value:'القيمة أو النسبة',taxable:'يدخل في الأجر الخاضع للضريبة',social:'يدخل في أساس التأمينات',visible:'يظهر في بيان الراتب',active:'المكوّن فعال',proration:'استحقاق القيمة الثابتة خلال الفترة',order:'ترتيب العرض',behavior:'طريقة الاستخدام',component_id:'مكوّن الراتب',units:'الوحدات المستحقة المعتمدة',amount:'المبلغ بالجنيه',reference:'مرجع الإثبات',reason:'سبب الإدخال أو التغيير',year:'السنة',taxable_earnings:'الأجر الخاضع السابق',tax_withheld:'الضريبة المخصومة سابقًا',social_base:'أساس التأمينات السابق',employee_social:'اشتراكات الموظف السابقة',employer_social:'اشتراكات جهة العمل السابقة',mode:'سياسة الجزء من الفترة'};
const options=inputOptions;
export function InputForm({tenant,employer,period,kind,record,employees,components,canSave,canApprove,back}: {tenant:string;employer:string;period:{id:string;starts_on:string;ends_on:string};kind:InputKind;record?:InputRecord;employees:Choice[];components:Choice[];canSave:boolean;canApprove:boolean;back:string}) {
 const tomorrow=new Date(`${period.ends_on}T12:00:00Z`);tomorrow.setUTCDate(tomorrow.getUTCDate()+1);
 const periodInput=['manual_units','adjustment'].includes(kind);
 const [values,setValues]=useState<Record<string,string>>(()=>({from:record?.effective_from??period.starts_on,until:record?.effective_until??(periodInput?tomorrow.toISOString().slice(0,10):''),employment:record?.employment_id??employees[0]?.id??'',...Object.fromEntries(inputFields[kind].map(k=>[k,String(record?.data[k]??options[k]?.[0]?.[0]??(k==='order'?'10':k==='year'?period.starts_on.slice(0,4):''))]))}));
 const [state,action,pending]=useActionState(inputAction,{error:'',saved:false,head:record?.id??'',revision:record?.revision??0,attempt:'',signature:'',status:record?.status??'draft'});
 const frozen=['cancelled','applied'].includes(state.status),approved=state.status==='approved';
 const field=(key:string,choices?:Choice[])=>{const list=choices?choices.map(c=>[c.id,c.name] as [string,string]):options[key];return <label key={key} htmlFor={`input-${key}`}>{labels[key]??(key==='from'?'تاريخ السريان':'ينتهي قبل تاريخ (اختياري)')}{list?<select id={`input-${key}`} name={key} value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}>{choices&&values[key]&&!list.some(o=>o[0]===values[key])&&<option value={values[key]}>القيمة المحفوظة في هذا السجل</option>}{list.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select>:<input id={`input-${key}`} name={key} value={values[key]??''} required={key==='reference'?kind==='opening_ytd':key!=='until'} type={['from','until'].includes(key)?'date':'text'} inputMode={['value','units','amount','taxable_earnings','tax_withheld','social_base','employee_social','employer_social'].includes(key)?'decimal':undefined} maxLength={key==='reason'?500:160} onChange={e=>setValues({...values,[key]:e.target.value})}/>}</label>};
 return <form action={action} onReset={e=>e.preventDefault()} className={styles.form}><h2>{kindNames[kind]}</h2><p>الحالة: {statusNames[state.status]??'مسودة'}</p><input type="hidden" name="tenant" value={tenant}/><input type="hidden" name="employer" value={employer}/><input type="hidden" name="kind" value={kind}/><input type="hidden" name="period" value={periodInput?period.id:''}/>
 <fieldset disabled={pending} className={styles.fields}>{!['component','policy'].includes(kind)?<label htmlFor="input-employment">الموظف<select id="input-employment" name="employment" value={values.employment} onChange={e=>setValues({...values,employment:e.target.value})} disabled={Boolean(state.head)}>{record&&!employees.some(e=>e.id===values.employment)&&<option value={values.employment}>الموظف المحدد في السجل</option>}{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select>{state.head&&<input type="hidden" name="employment" value={values.employment}/>}</label>:<input type="hidden" name="employment" value=""/>}
 {periodInput?<><input type="hidden" name="from" value={values.from}/><input type="hidden" name="until" value={values.until}/></>:<>{field('from')}{field('until')}</>}
 {inputFields[kind].map(k=>field(k,k==='component_id'?components:undefined))}</fieldset>
 {kind==='manual_units'&&<p>تحضير الوحدات لا يصرف مالًا. يلزم اعتمادها؛ الحضور ليس شرطًا لاستخدام هذا المسار.</p>}{kind==='opening_ytd'&&<p>أدخل جميع القيم من مرجع مراجَع؛ الصفر تصريح بقيمة صفرية وليس بديلًا عن بيانات مجهولة.</p>}{kind==='policy'&&<p>تحدد مرة واحدة للشركة. الراتب الشهري الكامل للفترة العادية يُدفع كاملًا؛ تفاصيل الحساب والفترة الانتقالية تظهر عند إتاحة الحساب.</p>}{kind==='component'&&<p>معاملة الضريبة والتأمينات بيانات للمراجعة؛ لا تعني اعتمادًا قانونيًا. لا يدعم النظام معادلات حرة.</p>}
 {state.error&&<p role="alert">{state.error}</p>}{state.saved&&<p role="status">تم حفظ السجل في حالته الظاهرة. لم يُطبّق في راتب أو صرف.</p>}
 <div className={styles.actions}>{canSave&&!frozen&&(!periodInput||!approved)&&<button className="primary-button" name="operation" value="save" disabled={pending}>حفظ المدخل</button>}{canApprove&&state.head&&!frozen&&!approved&&periodInput&&<button className="primary-button" name="operation" value="approve" disabled={pending}>اعتماد المدخل</button>}{canSave&&state.head&&!frozen&&periodInput&&<button className="secondary-button" name="operation" value="cancel" disabled={pending}>إلغاء المدخل</button>}<Link className="secondary-button" href={back}>العودة إلى المدخلات</Link></div></form>;
}
