import { Button, ButtonLink, Disclosure, Input, Message, PageHeader, Panel, RecordCard, Select, Avatar, Badge } from '@/components/ui';
import {EmployerSelector} from '../EmployerSelector';
import {normalizeEmployerScope} from '../employer-context';
import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PageFrame} from '@/components/context-navigation';
import { getWorkspaceClient as createSupabaseServerClient, getWorkspaceUser } from '@/lib/workspace-access';
import {uuid,displayDate} from '../rules';
import {InputForm} from './InputForm';
import {employeeSelection} from './employee-selection';
import {CorrectionForm} from './CorrectionForm';
import {kindNames,statusNames,type InputKind,type InputRecord} from './rules';
import styles from '../payroll.module.css';
export const dynamic='force-dynamic';
type Period={id:string;starts_on:string;ends_on:string};
type Employee={id:string;full_name:string;employee_code:string;pay_basis:string;readiness:string};
type Workspace={access:Record<string,boolean>;period:Period;employees:Employee[];records:(InputRecord&{employee_name:string|null})[];records_more:boolean;component_choices:{id:string;name:string;behavior:string;classification:string;calculation:string;active:boolean;effective_from:string;effective_until:string|null}[];component_choices_more:boolean};
export default async function InputsPage({params,searchParams}:{params:Promise<{tenantId:string}>;searchParams:Promise<Record<string,string|undefined>>}) {
 const {tenantId}=await params;if(!uuid(tenantId))notFound();const query=await searchParams;
 const path=`/tenant/${tenantId}/payroll/inputs`,keep=Object.fromEntries(Object.entries(query).filter((x):x is [string,string]=>typeof x[1]==='string'));
 const employerDestination=normalizeEmployerScope(path,'inputs',query);if(employerDestination)redirect(employerDestination);
 const href=(extra:Record<string,string>)=>`${path}?${new URLSearchParams({...keep,...extra})}`;
 const failure=(text:string)=><PageFrame><Panel className={styles.card} dir="rtl"><PageHeader  title={<>مدخلات الرواتب</>} /><Message tone="bad" role="alert">{text}</Message><Link href={href({})}>إعادة المحاولة بنفس الاختيار</Link></Panel></PageFrame>;
 for(const key of ['employer','period','after','records_after','head','after_id','employee','review_after','review_employee'])if(query[key]&&!uuid(query[key]!))return failure('راجع رابط الجهة والفترة ثم أعد المحاولة.');
 if((query.review_q?.length??0)>120||(query.review_view&&query.review_view!=='all'&&query.review_view!=='attention'))return failure('راجع بحث وقائمة مراجعة الرواتب.');
 const reviewContext=Object.fromEntries(['review_view','review_q','review_after','review_employee'].filter(key=>query[key]!==undefined).map(key=>[key,query[key]!]));
 const client=await createSupabaseServerClient();if(!client)return failure('تعذر الاتصال ببيانات الرواتب.');const {data:{user}}=await getWorkspaceUser(client);if(!user)redirect(`/auth/login?next=${encodeURIComponent(href({}))}`);
 const employers=await client.rpc('payroll_input_employers',{p_tenant:tenantId,p_query:query.employer_q??'',p_after_name:query.after_name??null,p_after_id:query.after_id??null});
 if(employers.error||!employers.data)return failure('تعذر تحميل الجهات أو لم يعد الحساب مخولًا. راجع مسؤول الشركة أو أعد المحاولة.');
 const employer=query.employer??employers.data.unique_employer??'';
 if(!employer)return <PageFrame><div dir="rtl" className={styles.workspace}><PageHeader  title={<>اختر جهة مدخلات الرواتب</>} /><form method="get" className={styles.filters}><label>البحث عن جهة<Input name="employer_q" defaultValue={query.employer_q??''} maxLength={120}/></label><Button variant="ghost" type="submit" >بحث</Button></form>{employers.data.items.length===0?<p>لا توجد جهة مطابقة. راجع إعداد الجهات مع مسؤول الشركة.</p>:<ul>{employers.data.items.map((e:{id:string;name:string})=><li key={e.id}><Link href={href({employer:e.id})}>{e.name}</Link></li>)}</ul>}{employers.data.items.length===30&&<Link href={href({after_id:employers.data.items[29].id,after_name:employers.data.items[29].name})}>جهات إضافية</Link>}</div></PageFrame>;
 const periodsResult=await client.rpc('payroll_input_periods',{p_tenant:tenantId,p_employer:employer,p_before:query.before??null});if(periodsResult.error)return failure('تعذر تحميل الفترات المحفوظة.');const periods=periodsResult.data as Period[];
 const period=query.period||periods[0]?.id;
 const calendar=`/tenant/${tenantId}/payroll?${new URLSearchParams({employer})}`;
 if(!period)return <PageFrame><Panel className={styles.card} dir="rtl"><PageHeader  title={<>مدخلات الرواتب</>} description={<> يلزم تحديد فترة محفوظة أولًا. المسؤول عن الإعداد: مدير دورة الرواتب. </>} /><Link href={calendar}>العودة إلى دورة الجهة</Link></Panel></PageFrame>;
 const result=await client.rpc('payroll_input_workspace',{p_tenant:tenantId,p_employer:employer,p_period:period,p_query:query.q??'',p_after:query.after??null,p_record_after:query.records_after??null,p_limit:30});if(result.error||!result.data)return failure('تعذر تحميل مدخلات هذه الفترة. الاختيار والبحث محفوظان في الرابط.');
 const work=result.data as Workspace,access=work.access,records=work.records;
 const correctionResult=access['payroll.view']?await client.rpc('payroll_correction_items',{p_tenant:tenantId,p_employer:employer,p_period:period}):null;
 const corrections=(correctionResult?.data??[]) as {employment_id:string;name:string;requested:boolean}[];
 const kind=query.kind as InputKind|undefined,record=query.head?records.find(r=>r.id===query.head):undefined;
 if(query.head&&!record)return failure('السجل المطلوب خارج صفحة النتائج الحالية. ارجع إلى قائمة المدخلات وافتحه من صفحته.');
 if(kind&&!Object.hasOwn(kindNames,kind))return failure('نوع المدخل غير معروف.');
 const permission=(k:InputKind,approve=false)=>access[k==='component'||k==='policy'?'payroll_config.manage':k==='adjustment'?approve?'employee_finance.approve':'employee_finance.manage':k==='recurring'&&approve?'employee_finance.approve':k==='manual_units'&&approve?'payroll.approve':'payroll.prepare']===true;
 const employeeName=(id:string|null)=>work.employees.find(e=>e.id===id)?.full_name??'الموظف المحدد';
 const clear={head:'',kind:''},back=href(clear);
 const formEmployees=employeeSelection(work.employees,record?.employment_id??query.employee);
 if(kind&&['manual_units','opening_ytd','statutory_context','recurring','adjustment'].includes(kind)&&!record&&!formEmployees)return <PageFrame><Panel className={styles.card} dir="rtl"><PageHeader  title={<>اختيار الموظف للمدخل</>} /><Message tone="bad" role="alert">الموظف المحدد غير موجود في نتائج هذه الصفحة. ابحث باسمه أو كوده؛ لن يُفتح مدخل لموظف آخر.</Message><form method="get" className={styles.filters}>{Object.entries({employer,period,employee:query.employee??'',kind,...reviewContext}).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<label>اسم الموظف أو كوده<Input name="q" defaultValue={query.q??''} maxLength={120}/></label><Button variant="ghost" type="submit" >البحث عن الموظف المحدد</Button></form><Link href={back}>العودة إلى المدخلات</Link></Panel></PageFrame>;
  const reviewBack=`/tenant/${tenantId}/payroll/runs?${new URLSearchParams({employer,period,q:query.review_q??query.q??'',view:query.review_view??'attention',after:query.review_after??'',employee:query.review_employee??''})}`;
  return <PageFrame><div dir="rtl" className={styles.workspace}><div><PageHeader  title={<>تحضير مدخلات الرواتب</>} description={<> {employers.data.items.find((e:{id:string;name:string})=>e.id===employer)?.name??'الجهة المحددة'} </>} /><p>{displayDate(work.period.starts_on)} — {displayDate(work.period.ends_on)}</p><EmployerSelector path={path} page="inputs" employer={employer} name={employers.data.items.find((e:{id:string;name:string})=>e.id===employer)?.name??'الجهة المحددة'} choices={employers.data.items} context={{...query,period}} singleEmployer={employers.data.unique_employer===employer}/><nav className={styles.actions} aria-label="متابعة فترة الرواتب"><ButtonLink variant="ghost" href={reviewBack}>مراجعة الفترة</ButtonLink><ButtonLink variant="ghost" href={calendar}>الدورة والفترات</ButtonLink><ButtonLink variant="ghost" href={path}>تغيير الجهة</ButtonLink></nav></div>
 <form method="get" className={styles.filters}><input type="hidden" name="employer" value={employer}/>{Object.entries(reviewContext).map(([key,value])=><input key={key} type="hidden" name={key} value={value}/>)}<label>الفترة<Select name="period" defaultValue={period}>{!periods.some(p=>p.id===period)&&<option value={period}>الفترة المحددة</option>}{periods.map(p=><option value={p.id} key={p.id}>{displayDate(p.starts_on)} — {displayDate(p.ends_on)}</option>)}</Select></label><label>البحث عن موظف<Input name="q" defaultValue={query.q??''} maxLength={120}/></label><Button variant="ghost" type="submit" >عرض المدخلات</Button></form>
 {periods.length===24&&<Link href={href({before:periods[23].starts_on,period:'',...clear})}>فترات أقدم</Link>}
 {!access.enabled&&<Message tone="info" role="status">خدمة الرواتب غير مفعلة؛ لا يمكن إعداد مدخلات جديدة. التاريخ المحفوظ متاح حسب صلاحياتك.</Message>}
<Panel className={styles.taskLauncher} aria-label="مدخلات وإعدادات الرواتب"><h2>ماذا تريد تجهيزُه؟</h2><p>إعدادات الشركة: مكوّنات الراتب وسياسة احتساب الفترة. بيانات الضريبة والتأمينات تخص كل موظف.</p>{access.enabled&&<nav className={styles.actions} aria-label="إضافة مدخل">{(Object.keys(kindNames) as InputKind[]).filter(k=>permission(k)&&!(k==='policy'&&records.some(r=>r.kind==='policy'))).map(k=><ButtonLink variant="ghost" key={k}  href={href({kind:k,head:''})}>{kindNames[k]}</ButtonLink>)}</nav>}</Panel>
 <nav className={styles.reviewNavigation} aria-label="أقسام مدخلات الرواتب"><a href="#payroll-input-prerequisites">قبل الحساب</a><a href="#payroll-input-employees">الموظفون</a>{corrections.length>0&&<a href="#payroll-input-corrections">مسؤوليات التصحيح</a>}<a href="#payroll-input-records">المدخلات المحفوظة</a>{kind&&<a href="#payroll-input-editor">المدخل المحدد</a>}</nav>
 <Panel id="payroll-input-prerequisites" className={styles.card}><h2>ما يلزم قبل الحساب</h2><p>{records.some(r=>r.kind==='policy')?'سياسة الشركة محفوظة.':'سياسة احتساب الجزء من الفترة غير محددة؛ المسؤول: مدير إعداد الرواتب.'}</p><p>يُفحص التأهيل المالي والقانوني على الحساب الحالي في مراجعة الرواتب؛ يتطلب التثبيت تأهيل الحساب واعتماده وصلاحية المسؤول المخول.</p><p>اختر مصدر أيام واحدًا للأجر اليومي. راجع أثر الحضور والإجازات في صفحة مراجعة الرواتب؛ غياب الخدمة الاختيارية لا يمنع إدخال إجمالي يدوي موثق.</p></Panel>
 <section id="payroll-input-employees"><Disclosure summary={<>الموظفون المؤهلون لهذه الفترة</>} open={!kind}>{work.employees.length===0?<p>لا توجد علاقات توظيف مؤهلة مطابقة. راجع البحث أو أهلية الموظفين مع الموارد البشرية.</p>:<ul className={styles.cardGrid}>{work.employees.map(e=><RecordCard className={styles.card} key={e.id}><div className={styles.recordHeading}><Avatar name={e.full_name}/><h3>{e.full_name} · <bdi>{e.employee_code}</bdi></h3></div><p>{e.pay_basis==='daily'?'أجر يومي':'أجر شهري'} · {e.readiness==='compensation_missing'?'بيانات الأجر غير مكتملة؛ المسؤول: الموارد البشرية.':e.readiness==='approved_units_missing'?'يلزم اعتماد وحدات مستحقة؛ المسؤول: معد ومعتمد الرواتب.':'مدخلات قابلة للمراجعة؛ لم يُحسب مبلغ.'}</p>{access['payroll.prepare']&&e.pay_basis==='daily'&&<Link href={href({kind:'manual_units',head:'',employee:e.id})}>تحضير الوحدات المستحقة</Link>}</RecordCard>)}</ul>}{work.employees.length===30&&<Link href={href({after:work.employees[29].id,...clear})}>موظفون إضافيون</Link>}{query.after&&<Link href={href({after:'',...clear})}>أول صفحة موظفين</Link>}</Disclosure></section>
 {correctionResult?.error&&<Message tone="bad" role="alert">تعذر تحميل مسؤوليات التصحيح لهذه الفترة. أعد المحاولة قبل مراجعة تاريخها.</Message>}
 {corrections.length>0&&<section id="payroll-input-corrections"><h2>تاريخ راتب محمي ومسؤولية التصحيح</h2>{corrections.map(c=><Panel as="div" className={styles.card} key={c.employment_id}><p>{c.name} · {c.requested?'يوجد طلب تصحيح موثق.':'التغييرات المادية تتطلب طلب تصحيح.'}</p>{access['payroll.correct']&&access.enabled&&!c.requested&&<CorrectionForm tenant={tenantId} employer={employer} period={period} employment={c.employment_id} name={c.name}/>}</Panel>)}{corrections.length===50&&<p>النتائج محدودة؛ تواصل مع مسؤول الرواتب لمتابعة بقية مسؤوليات الفترة.</p>}</section>}
 <section id="payroll-input-records"><Disclosure summary={<>المدخلات المحفوظة</>} open={!kind}>{records.length===0?<p>لم تُحفظ مدخلات لهذه الجهة والفترة بعد.</p>:<ul className={styles.cardGrid}>{records.map(r=><RecordCard key={r.id} className={styles.card}><h3>{kindNames[r.kind]}{r.employee_name?` · ${r.employee_name}`:''}</h3><p>{String(r.data.name??r.data.reason)}</p><Badge tone={r.status==='approved'||r.status==='applied'?'ok':'neutral'}>{statusNames[r.status]}</Badge><p>تبدأ {displayDate(r.effective_from)}{r.effective_until?` وتنتهي قبل ${displayDate(r.effective_until)}`:''}</p><Link href={href({kind:r.kind,head:r.id})}>عرض المدخل ومراجعته</Link></RecordCard>)}</ul>}{work.records_more&&<Link href={href({records_after:records[records.length-1].id,...clear})}>مدخلات إضافية</Link>}{query.records_after&&<Link href={href({records_after:'',...clear})}>أول صفحة مدخلات</Link>}</Disclosure></section>

 {kind&&['recurring','adjustment'].includes(kind)&&!record&&work.component_choices_more&&<Link href={href({records_after:work.component_choices[work.component_choices.length-1].id})}>مكوّنات إضافية للاختيار</Link>}
 {kind&&<InputForm key={`${tenantId}:${employer}:${period}:${kind}:${record?.id??'new'}:${query.employee??''}`} tenant={tenantId} employer={employer} period={work.period} kind={kind} record={record} insurancePeriods={periods.map(p=>({id:p.id,name:`${displayDate(p.starts_on)} - ${displayDate(p.ends_on)}`}))} employees={(formEmployees??work.employees).map(e=>({id:e.id,name:employeeName(e.id)}))} components={work.component_choices.filter(c=>kind==='recurring'?c.behavior==='recurring':c.behavior==='period_input'&&c.calculation==='fixed'&&c.classification!=='employer_cost').map(c=>({id:c.id,name:c.name,classification:c.classification}))} carryComponents={work.component_choices.filter(c=>c.behavior==='period_input'&&c.calculation==='fixed'&&c.classification==='deduction').map(c=>({id:c.id,name:c.name}))} canSaveDebt={access.enabled&&access['employee_finance.manage']===true} canSave={access.enabled&&permission(kind)} canApprove={access.enabled&&permission(kind,true)} back={back} timeEnabled={access.time_enabled===true} newEntry={href({kind:'manual_units',head:'',employee:record?.employment_id??query.employee??''})}/>}
 </div></PageFrame>;
}
